// Package mailapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package mailapi

// MailCreateV4AttachmentsJSONBody defines parameters for MailCreateV4Attachments.
type MailCreateV4AttachmentsJSONBody struct {
	ContentID  *string `json:"ContentID,omitempty"`
	DataPacket *string `json:"DataPacket,omitempty"`
	Filename   *string `json:"Filename,omitempty"`
	KeyPackets *string `json:"KeyPackets,omitempty"`
	MIMEType   *string `json:"MIMEType,omitempty"`
	MessageID  *string `json:"MessageID,omitempty"`
}

// MailDeleteV4AttachmentParams defines parameters for MailDeleteV4Attachment.
type MailDeleteV4AttachmentParams struct {
	MessageID *string `form:"MessageID,omitempty" json:"MessageID,omitempty"`
}

// MailListV4ConversationsParams defines parameters for MailListV4Conversations.
type MailListV4ConversationsParams struct {
	Location     *string `form:"Location,omitempty" json:"Location,omitempty"`
	Page         *string `form:"Page,omitempty" json:"Page,omitempty"`
	PageSize     *string `form:"PageSize,omitempty" json:"PageSize,omitempty"`
	Limit        *string `form:"Limit,omitempty" json:"Limit,omitempty"`
	LabelID      *string `form:"LabelID,omitempty" json:"LabelID,omitempty"`
	Sort         *string `form:"Sort,omitempty" json:"Sort,omitempty"`
	Desc         *string `form:"Desc,omitempty" json:"Desc,omitempty"`
	Begin        *string `form:"Begin,omitempty" json:"Begin,omitempty"`
	End          *string `form:"End,omitempty" json:"End,omitempty"`
	BeginID      *string `form:"BeginID,omitempty" json:"BeginID,omitempty"`
	EndID        *string `form:"EndID,omitempty" json:"EndID,omitempty"`
	Keyword      *string `form:"Keyword,omitempty" json:"Keyword,omitempty"`
	Recipients   *string `form:"Recipients,omitempty" json:"Recipients,omitempty"`
	To           *string `form:"To,omitempty" json:"To,omitempty"`
	From         *string `form:"From,omitempty" json:"From,omitempty"`
	Subject      *string `form:"Subject,omitempty" json:"Subject,omitempty"`
	Attachments  *string `form:"Attachments,omitempty" json:"Attachments,omitempty"`
	Starred      *string `form:"Starred,omitempty" json:"Starred,omitempty"`
	Unread       *string `form:"Unread,omitempty" json:"Unread,omitempty"`
	AddressID    *string `form:"AddressID,omitempty" json:"AddressID,omitempty"`
	ID           *string `form:"ID,omitempty" json:"ID,omitempty"`
	AutoWildcard *string `form:"AutoWildcard,omitempty" json:"AutoWildcard,omitempty"`
	Anchor       *string `form:"Anchor,omitempty" json:"Anchor,omitempty"`
	AnchorID     *string `form:"AnchorID,omitempty" json:"AnchorID,omitempty"`
}

// MailListV4ConversationsCountParams defines parameters for MailListV4ConversationsCount.
type MailListV4ConversationsCountParams struct {
	AddressID *string `form:"AddressID,omitempty" json:"AddressID,omitempty"`
}

// MailUpdateV4ConversationsDeleteJSONBody defines parameters for MailUpdateV4ConversationsDelete.
type MailUpdateV4ConversationsDeleteJSONBody struct {
	IDs *string `json:"IDs,omitempty"`
}

// MailUpdateV4ConversationsExpireJSONBody defines parameters for MailUpdateV4ConversationsExpire.
type MailUpdateV4ConversationsExpireJSONBody struct {
	IDs *string `json:"IDs,omitempty"`
}

// MailUpdateV4ConversationsLabelJSONBody defines parameters for MailUpdateV4ConversationsLabel.
type MailUpdateV4ConversationsLabelJSONBody struct {
	IDs     *string `json:"IDs,omitempty"`
	LabelID *string `json:"LabelID,omitempty"`
}

// MailUpdateV4ConversationsSnoozeJSONBody defines parameters for MailUpdateV4ConversationsSnooze.
type MailUpdateV4ConversationsSnoozeJSONBody struct {
	IDs *string `json:"IDs,omitempty"`
}

// MailUpdateV4ConversationsUnlabelJSONBody defines parameters for MailUpdateV4ConversationsUnlabel.
type MailUpdateV4ConversationsUnlabelJSONBody struct {
	LabelID *string `json:"LabelID,omitempty"`
}

// MailUpdateV4ConversationsUnreadJSONBody defines parameters for MailUpdateV4ConversationsUnread.
type MailUpdateV4ConversationsUnreadJSONBody struct {
	IDs *string `json:"IDs,omitempty"`
}

// MailCreateV4EoReplyJSONBody defines parameters for MailCreateV4EoReply.
type MailCreateV4EoReplyJSONBody struct {
	Body      *string `json:"Body,omitempty"`
	ReplyBody *string `json:"ReplyBody,omitempty"`
}

// MailCreateV4FiltersJSONBody defines parameters for MailCreateV4Filters.
type MailCreateV4FiltersJSONBody struct {
	Name  *string `json:"Name,omitempty"`
	Sieve *string `json:"Sieve,omitempty"`
}

// MailUpdateV4FiltersCheckJSONBody defines parameters for MailUpdateV4FiltersCheck.
type MailUpdateV4FiltersCheckJSONBody struct {
	Sieve *string `json:"Sieve,omitempty"`
}

// MailUpdateV4FilterJSONBody defines parameters for MailUpdateV4Filter.
type MailUpdateV4FilterJSONBody struct {
	Name    *string `json:"Name,omitempty"`
	Sieve   *string `json:"Sieve,omitempty"`
	Simple  *string `json:"Simple,omitempty"`
	Status  *string `json:"Status,omitempty"`
	Tree    *string `json:"Tree,omitempty"`
	Version *string `json:"Version,omitempty"`
}

// MailCreateV4ForwardingsJSONBody defines parameters for MailCreateV4Forwardings.
type MailCreateV4ForwardingsJSONBody struct {
	ActivationToken     *string `json:"ActivationToken,omitempty"`
	ForwardeeEmail      *string `json:"ForwardeeEmail,omitempty"`
	ForwardeePrivateKey *string `json:"ForwardeePrivateKey,omitempty"`
	ForwarderAddressID  *string `json:"ForwarderAddressID,omitempty"`
	ProxyInstances      *string `json:"ProxyInstances,omitempty"`
	Tree                *string `json:"Tree,omitempty"`
	Type                *string `json:"Type,omitempty"`
	Version             *string `json:"Version,omitempty"`
}

// MailListV4ForwardingsIncomingParams defines parameters for MailListV4ForwardingsIncoming.
type MailListV4ForwardingsIncomingParams struct {
	Page     *string `form:"Page,omitempty" json:"Page,omitempty"`
	PageSize *string `form:"PageSize,omitempty" json:"PageSize,omitempty"`
}

// MailListV4ForwardingsOutgoingParams defines parameters for MailListV4ForwardingsOutgoing.
type MailListV4ForwardingsOutgoingParams struct {
	Page     *string `form:"Page,omitempty" json:"Page,omitempty"`
	PageSize *string `form:"PageSize,omitempty" json:"PageSize,omitempty"`
}

// MailUpdateV4ForwardingJSONBody defines parameters for MailUpdateV4Forwarding.
type MailUpdateV4ForwardingJSONBody struct {
	ActivationToken     *string `json:"ActivationToken,omitempty"`
	ForwardeePrivateKey *string `json:"ForwardeePrivateKey,omitempty"`
	ProxyInstances      *string `json:"ProxyInstances,omitempty"`
}

// MailUpdateV4ForwardingsFilterJSONBody defines parameters for MailUpdateV4ForwardingsFilter.
type MailUpdateV4ForwardingsFilterJSONBody struct {
	Tree *string `json:"Tree,omitempty"`
}

// MailListV4IncomingdefaultsParams defines parameters for MailListV4Incomingdefaults.
type MailListV4IncomingdefaultsParams struct {
	Location *string `form:"Location,omitempty" json:"Location,omitempty"`
	Page     *string `form:"Page,omitempty" json:"Page,omitempty"`
	PageSize *string `form:"PageSize,omitempty" json:"PageSize,omitempty"`
}

// MailUpdateV4IncomingdefaultJSONBody defines parameters for MailUpdateV4Incomingdefault.
type MailUpdateV4IncomingdefaultJSONBody struct {
	Domain *string `json:"Domain,omitempty"`
	Email  *string `json:"Email,omitempty"`
}

// MailListV4MessagesParams defines parameters for MailListV4Messages.
type MailListV4MessagesParams struct {
	Location                 *string `form:"Location,omitempty" json:"Location,omitempty"`
	Page                     *string `form:"Page,omitempty" json:"Page,omitempty"`
	PageSize                 *string `form:"PageSize,omitempty" json:"PageSize,omitempty"`
	Limit                    *string `form:"Limit,omitempty" json:"Limit,omitempty"`
	LabelID                  *string `form:"LabelID,omitempty" json:"LabelID,omitempty"`
	Sort                     *string `form:"Sort,omitempty" json:"Sort,omitempty"`
	Desc                     *string `form:"Desc,omitempty" json:"Desc,omitempty"`
	Begin                    *string `form:"Begin,omitempty" json:"Begin,omitempty"`
	End                      *string `form:"End,omitempty" json:"End,omitempty"`
	BeginID                  *string `form:"BeginID,omitempty" json:"BeginID,omitempty"`
	EndID                    *string `form:"EndID,omitempty" json:"EndID,omitempty"`
	Keyword                  *string `form:"Keyword,omitempty" json:"Keyword,omitempty"`
	Recipients               *string `form:"Recipients,omitempty" json:"Recipients,omitempty"`
	To                       *string `form:"To,omitempty" json:"To,omitempty"`
	From                     *string `form:"From,omitempty" json:"From,omitempty"`
	Subject                  *string `form:"Subject,omitempty" json:"Subject,omitempty"`
	Attachments              *string `form:"Attachments,omitempty" json:"Attachments,omitempty"`
	Starred                  *string `form:"Starred,omitempty" json:"Starred,omitempty"`
	Unread                   *string `form:"Unread,omitempty" json:"Unread,omitempty"`
	AddressID                *string `form:"AddressID,omitempty" json:"AddressID,omitempty"`
	ID                       *string `form:"ID,omitempty" json:"ID,omitempty"`
	AutoWildcard             *string `form:"AutoWildcard,omitempty" json:"AutoWildcard,omitempty"`
	Anchor                   *string `form:"Anchor,omitempty" json:"Anchor,omitempty"`
	AnchorID                 *string `form:"AnchorID,omitempty" json:"AnchorID,omitempty"`
	NewsletterSubscriptionID *string `form:"NewsletterSubscriptionID,omitempty" json:"NewsletterSubscriptionID,omitempty"`
}

// MailCreateV4MessagesJSONBody defines parameters for MailCreateV4Messages.
type MailCreateV4MessagesJSONBody struct {
	Action   *string `json:"Action,omitempty"`
	Message  *string `json:"Message,omitempty"`
	ParentID *string `json:"ParentID,omitempty"`
}

// MailCreateV4MessagesApplyFiltersJSONBody defines parameters for MailCreateV4MessagesApplyFilters.
type MailCreateV4MessagesApplyFiltersJSONBody struct {
	AllFilters    *string `json:"AllFilters,omitempty"`
	AllowList     *string `json:"AllowList,omitempty"`
	BlockList     *string `json:"BlockList,omitempty"`
	FilterIDs     *string `json:"FilterIDs,omitempty"`
	SearchContext *string `json:"SearchContext,omitempty"`
	Sieve         *string `json:"Sieve,omitempty"`
	SpamList      *string `json:"SpamList,omitempty"`
	Version       *string `json:"Version,omitempty"`
}

// MailCreateV4MessagesBatchLabelJSONBody defines parameters for MailCreateV4MessagesBatchLabel.
type MailCreateV4MessagesBatchLabelJSONBody struct {
	AddLabelIDs   *string `json:"AddLabelIDs,omitempty"`
	SearchContext *string `json:"SearchContext,omitempty"`
}

// MailCreateV4MessagesBatchMoveJSONBody defines parameters for MailCreateV4MessagesBatchMove.
type MailCreateV4MessagesBatchMoveJSONBody struct {
	SearchContext *string `json:"SearchContext,omitempty"`
}

// MailListV4MessagesCountParams defines parameters for MailListV4MessagesCount.
type MailListV4MessagesCountParams struct {
	AddressID *string `form:"AddressID,omitempty" json:"AddressID,omitempty"`
}

// MailUpdateV4MessagesDeleteJSONBody defines parameters for MailUpdateV4MessagesDelete.
type MailUpdateV4MessagesDeleteJSONBody struct {
	IDs *[]interface{} `json:"IDs,omitempty"`
}

// MailDeleteV4MessagesEmptyParams defines parameters for MailDeleteV4MessagesEmpty.
type MailDeleteV4MessagesEmptyParams struct {
	LabelID *string `form:"LabelID,omitempty" json:"LabelID,omitempty"`
}

// MailUpdateV4MessagesExpireJSONBody defines parameters for MailUpdateV4MessagesExpire.
type MailUpdateV4MessagesExpireJSONBody struct {
	IDs *string `json:"IDs,omitempty"`
}

// MailUpdateV4MessagesForwardJSONBody defines parameters for MailUpdateV4MessagesForward.
type MailUpdateV4MessagesForwardJSONBody struct {
	IDs *[]interface{} `json:"IDs,omitempty"`
}

// MailUpdateV4MessagesLabelJSONBody defines parameters for MailUpdateV4MessagesLabel.
type MailUpdateV4MessagesLabelJSONBody struct {
	IDs     *[]interface{} `json:"IDs,omitempty"`
	LabelID *string        `json:"LabelID,omitempty"`
}

// MailUpdateV4MessagesReadJSONBody defines parameters for MailUpdateV4MessagesRead.
type MailUpdateV4MessagesReadJSONBody struct {
	IDs *[]interface{} `json:"IDs,omitempty"`
}

// MailCreateV4MessagesSendDirectJSONBody defines parameters for MailCreateV4MessagesSendDirect.
type MailCreateV4MessagesSendDirectJSONBody struct {
	Action           *string `json:"Action,omitempty"`
	AttachmentKeys   *string `json:"AttachmentKeys,omitempty"`
	AutoSaveContacts *string `json:"AutoSaveContacts,omitempty"`
	ExpirationTime   *string `json:"ExpirationTime,omitempty"`
	ExpiresIn        *string `json:"ExpiresIn,omitempty"`
	Message          *string `json:"Message,omitempty"`
	ParentID         *string `json:"ParentID,omitempty"`
}

// MailUpdateV4MessagesUnforwardJSONBody defines parameters for MailUpdateV4MessagesUnforward.
type MailUpdateV4MessagesUnforwardJSONBody struct {
	IDs *[]interface{} `json:"IDs,omitempty"`
}

// MailUpdateV4MessagesUnlabelJSONBody defines parameters for MailUpdateV4MessagesUnlabel.
type MailUpdateV4MessagesUnlabelJSONBody struct {
	IDs     *[]interface{} `json:"IDs,omitempty"`
	LabelID *string        `json:"LabelID,omitempty"`
}

// MailCreateV4MessageJSONBody defines parameters for MailCreateV4Message.
type MailCreateV4MessageJSONBody struct {
	AutoSaveContacts *string `json:"AutoSaveContacts,omitempty"`
	DelaySeconds     *string `json:"DelaySeconds,omitempty"`
	ExpirationTime   *string `json:"ExpirationTime,omitempty"`
	ExpiresIn        *string `json:"ExpiresIn,omitempty"`
	Packages         *string `json:"Packages,omitempty"`
}

// MailUpdateV4MessageJSONBody defines parameters for MailUpdateV4Message.
type MailUpdateV4MessageJSONBody struct {
	Message *string `json:"Message,omitempty"`
}

// MailCreateV4MessagesBodyJSONBody defines parameters for MailCreateV4MessagesBody.
type MailCreateV4MessagesBodyJSONBody struct {
	Body *string `json:"Body,omitempty"`
}

// MailCreateV4SmtptokensJSONBody defines parameters for MailCreateV4Smtptokens.
type MailCreateV4SmtptokensJSONBody struct {
	AddressID *string `json:"AddressID,omitempty"`
	Name      *string `json:"Name,omitempty"`
}

// MailCreateV4AttachmentsJSONRequestBody defines body for MailCreateV4Attachments for application/json ContentType.
type MailCreateV4AttachmentsJSONRequestBody MailCreateV4AttachmentsJSONBody

// MailUpdateV4ConversationsDeleteJSONRequestBody defines body for MailUpdateV4ConversationsDelete for application/json ContentType.
type MailUpdateV4ConversationsDeleteJSONRequestBody MailUpdateV4ConversationsDeleteJSONBody

// MailUpdateV4ConversationsExpireJSONRequestBody defines body for MailUpdateV4ConversationsExpire for application/json ContentType.
type MailUpdateV4ConversationsExpireJSONRequestBody MailUpdateV4ConversationsExpireJSONBody

// MailUpdateV4ConversationsLabelJSONRequestBody defines body for MailUpdateV4ConversationsLabel for application/json ContentType.
type MailUpdateV4ConversationsLabelJSONRequestBody MailUpdateV4ConversationsLabelJSONBody

// MailUpdateV4ConversationsSnoozeJSONRequestBody defines body for MailUpdateV4ConversationsSnooze for application/json ContentType.
type MailUpdateV4ConversationsSnoozeJSONRequestBody MailUpdateV4ConversationsSnoozeJSONBody

// MailUpdateV4ConversationsUnlabelJSONRequestBody defines body for MailUpdateV4ConversationsUnlabel for application/json ContentType.
type MailUpdateV4ConversationsUnlabelJSONRequestBody MailUpdateV4ConversationsUnlabelJSONBody

// MailUpdateV4ConversationsUnreadJSONRequestBody defines body for MailUpdateV4ConversationsUnread for application/json ContentType.
type MailUpdateV4ConversationsUnreadJSONRequestBody MailUpdateV4ConversationsUnreadJSONBody

// MailCreateV4EoReplyJSONRequestBody defines body for MailCreateV4EoReply for application/json ContentType.
type MailCreateV4EoReplyJSONRequestBody MailCreateV4EoReplyJSONBody

// MailCreateV4FiltersJSONRequestBody defines body for MailCreateV4Filters for application/json ContentType.
type MailCreateV4FiltersJSONRequestBody MailCreateV4FiltersJSONBody

// MailUpdateV4FiltersCheckJSONRequestBody defines body for MailUpdateV4FiltersCheck for application/json ContentType.
type MailUpdateV4FiltersCheckJSONRequestBody MailUpdateV4FiltersCheckJSONBody

// MailUpdateV4FilterJSONRequestBody defines body for MailUpdateV4Filter for application/json ContentType.
type MailUpdateV4FilterJSONRequestBody MailUpdateV4FilterJSONBody

// MailCreateV4ForwardingsJSONRequestBody defines body for MailCreateV4Forwardings for application/json ContentType.
type MailCreateV4ForwardingsJSONRequestBody MailCreateV4ForwardingsJSONBody

// MailUpdateV4ForwardingJSONRequestBody defines body for MailUpdateV4Forwarding for application/json ContentType.
type MailUpdateV4ForwardingJSONRequestBody MailUpdateV4ForwardingJSONBody

// MailUpdateV4ForwardingsFilterJSONRequestBody defines body for MailUpdateV4ForwardingsFilter for application/json ContentType.
type MailUpdateV4ForwardingsFilterJSONRequestBody MailUpdateV4ForwardingsFilterJSONBody

// MailUpdateV4IncomingdefaultJSONRequestBody defines body for MailUpdateV4Incomingdefault for application/json ContentType.
type MailUpdateV4IncomingdefaultJSONRequestBody MailUpdateV4IncomingdefaultJSONBody

// MailCreateV4MessagesJSONRequestBody defines body for MailCreateV4Messages for application/json ContentType.
type MailCreateV4MessagesJSONRequestBody MailCreateV4MessagesJSONBody

// MailCreateV4MessagesApplyFiltersJSONRequestBody defines body for MailCreateV4MessagesApplyFilters for application/json ContentType.
type MailCreateV4MessagesApplyFiltersJSONRequestBody MailCreateV4MessagesApplyFiltersJSONBody

// MailCreateV4MessagesBatchLabelJSONRequestBody defines body for MailCreateV4MessagesBatchLabel for application/json ContentType.
type MailCreateV4MessagesBatchLabelJSONRequestBody MailCreateV4MessagesBatchLabelJSONBody

// MailCreateV4MessagesBatchMoveJSONRequestBody defines body for MailCreateV4MessagesBatchMove for application/json ContentType.
type MailCreateV4MessagesBatchMoveJSONRequestBody MailCreateV4MessagesBatchMoveJSONBody

// MailUpdateV4MessagesDeleteJSONRequestBody defines body for MailUpdateV4MessagesDelete for application/json ContentType.
type MailUpdateV4MessagesDeleteJSONRequestBody MailUpdateV4MessagesDeleteJSONBody

// MailUpdateV4MessagesExpireJSONRequestBody defines body for MailUpdateV4MessagesExpire for application/json ContentType.
type MailUpdateV4MessagesExpireJSONRequestBody MailUpdateV4MessagesExpireJSONBody

// MailUpdateV4MessagesForwardJSONRequestBody defines body for MailUpdateV4MessagesForward for application/json ContentType.
type MailUpdateV4MessagesForwardJSONRequestBody MailUpdateV4MessagesForwardJSONBody

// MailUpdateV4MessagesLabelJSONRequestBody defines body for MailUpdateV4MessagesLabel for application/json ContentType.
type MailUpdateV4MessagesLabelJSONRequestBody MailUpdateV4MessagesLabelJSONBody

// MailUpdateV4MessagesReadJSONRequestBody defines body for MailUpdateV4MessagesRead for application/json ContentType.
type MailUpdateV4MessagesReadJSONRequestBody MailUpdateV4MessagesReadJSONBody

// MailCreateV4MessagesSendDirectJSONRequestBody defines body for MailCreateV4MessagesSendDirect for application/json ContentType.
type MailCreateV4MessagesSendDirectJSONRequestBody MailCreateV4MessagesSendDirectJSONBody

// MailUpdateV4MessagesUnforwardJSONRequestBody defines body for MailUpdateV4MessagesUnforward for application/json ContentType.
type MailUpdateV4MessagesUnforwardJSONRequestBody MailUpdateV4MessagesUnforwardJSONBody

// MailUpdateV4MessagesUnlabelJSONRequestBody defines body for MailUpdateV4MessagesUnlabel for application/json ContentType.
type MailUpdateV4MessagesUnlabelJSONRequestBody MailUpdateV4MessagesUnlabelJSONBody

// MailCreateV4MessageJSONRequestBody defines body for MailCreateV4Message for application/json ContentType.
type MailCreateV4MessageJSONRequestBody MailCreateV4MessageJSONBody

// MailUpdateV4MessageJSONRequestBody defines body for MailUpdateV4Message for application/json ContentType.
type MailUpdateV4MessageJSONRequestBody MailUpdateV4MessageJSONBody

// MailCreateV4MessagesBodyJSONRequestBody defines body for MailCreateV4MessagesBody for application/json ContentType.
type MailCreateV4MessagesBodyJSONRequestBody MailCreateV4MessagesBodyJSONBody

// MailCreateV4SmtptokensJSONRequestBody defines body for MailCreateV4Smtptokens for application/json ContentType.
type MailCreateV4SmtptokensJSONRequestBody MailCreateV4SmtptokensJSONBody
