// Package lumoapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package lumoapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// OtherCreateAiV1FeedbackWithBody performs a POST /ai/v1/feedback (the `OtherCreateAiV1Feedback` operationId) request,
	// with any type of body and a specified content type.
	OtherCreateAiV1FeedbackWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OtherCreateAiV1Feedback performs a POST /ai/v1/feedback (the `OtherCreateAiV1Feedback` operationId) request.
	// Takes a body of the `application/json` content type.
	OtherCreateAiV1Feedback(ctx context.Context, body OtherCreateAiV1FeedbackJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// OtherCreateAiV1FeedbackWithBody performs a POST /ai/v1/feedback (the `OtherCreateAiV1Feedback` operationId) request,
// with any type of body and a specified content type.
func (c *Client) OtherCreateAiV1FeedbackWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOtherCreateAiV1FeedbackRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// OtherCreateAiV1Feedback performs a POST /ai/v1/feedback (the `OtherCreateAiV1Feedback` operationId) request.
// Takes a body of the `application/json` content type.
func (c *Client) OtherCreateAiV1Feedback(ctx context.Context, body OtherCreateAiV1FeedbackJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOtherCreateAiV1FeedbackRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewOtherCreateAiV1FeedbackRequest calls the generic OtherCreateAiV1Feedback builder with application/json body
func NewOtherCreateAiV1FeedbackRequest(server string, body OtherCreateAiV1FeedbackJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewOtherCreateAiV1FeedbackRequestWithBody(server, "application/json", bodyReader)
}

// NewOtherCreateAiV1FeedbackRequestWithBody constructs an http.Request for the OtherCreateAiV1Feedback method, with any body, and a specified content type
func NewOtherCreateAiV1FeedbackRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ai/v1/feedback")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// OtherCreateAiV1FeedbackWithBodyWithResponse performs a POST /ai/v1/feedback (the `OtherCreateAiV1Feedback` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	OtherCreateAiV1FeedbackWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OtherCreateAiV1FeedbackResponse, error)

	// OtherCreateAiV1FeedbackWithResponse performs a POST /ai/v1/feedback (the `OtherCreateAiV1Feedback` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	OtherCreateAiV1FeedbackWithResponse(ctx context.Context, body OtherCreateAiV1FeedbackJSONRequestBody, reqEditors ...RequestEditorFn) (*OtherCreateAiV1FeedbackResponse, error)
}

type OtherCreateAiV1FeedbackResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r OtherCreateAiV1FeedbackResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r OtherCreateAiV1FeedbackResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OtherCreateAiV1FeedbackResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r OtherCreateAiV1FeedbackResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// OtherCreateAiV1FeedbackWithBodyWithResponse performs a POST /ai/v1/feedback (the `OtherCreateAiV1Feedback` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) OtherCreateAiV1FeedbackWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OtherCreateAiV1FeedbackResponse, error) {
	rsp, err := c.OtherCreateAiV1FeedbackWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOtherCreateAiV1FeedbackResponse(rsp)
}

// OtherCreateAiV1FeedbackWithResponse performs a POST /ai/v1/feedback (the `OtherCreateAiV1Feedback` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) OtherCreateAiV1FeedbackWithResponse(ctx context.Context, body OtherCreateAiV1FeedbackJSONRequestBody, reqEditors ...RequestEditorFn) (*OtherCreateAiV1FeedbackResponse, error) {
	rsp, err := c.OtherCreateAiV1Feedback(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOtherCreateAiV1FeedbackResponse(rsp)
}

// ParseOtherCreateAiV1FeedbackResponse parses an HTTP response from a OtherCreateAiV1FeedbackWithResponse call
func ParseOtherCreateAiV1FeedbackResponse(rsp *http.Response) (*OtherCreateAiV1FeedbackResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OtherCreateAiV1FeedbackResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
