// Package lumoapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package lumoapi

// OtherCreateAiV1FeedbackJSONBody defines parameters for OtherCreateAiV1Feedback.
type OtherCreateAiV1FeedbackJSONBody struct {
	Body               *string `json:"Body,omitempty"`
	Category           *string `json:"Category,omitempty"`
	Component          *string `json:"Component,omitempty"`
	Environment        *string `json:"Environment,omitempty"`
	HasGeneratedImages *string `json:"HasGeneratedImages,omitempty"`
	ModelID            *string `json:"ModelID,omitempty"`
	ModelOutput        *string `json:"ModelOutput,omitempty"`
	Prompt             *string `json:"Prompt,omitempty"`
	RequestedModel     *string `json:"RequestedModel,omitempty"`
	Sentiment          *string `json:"Sentiment,omitempty"`
}

// OtherCreateAiV1FeedbackJSONRequestBody defines body for OtherCreateAiV1Feedback for application/json ContentType.
type OtherCreateAiV1FeedbackJSONRequestBody OtherCreateAiV1FeedbackJSONBody
