// Package vpnapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package vpnapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// VpnCreateV1BusinessMembersUsageWithBody performs a POST /vpn/v1/business/members/usage (the `VpnCreateV1BusinessMembersUsage` operationId) request,
	// with any type of body and a specified content type.
	VpnCreateV1BusinessMembersUsageWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// VpnCreateV1BusinessMembersUsage performs a POST /vpn/v1/business/members/usage (the `VpnCreateV1BusinessMembersUsage` operationId) request.
	// Takes a body of the `application/json` content type.
	VpnCreateV1BusinessMembersUsage(ctx context.Context, body VpnCreateV1BusinessMembersUsageJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// VpnListV1Config performs a GET /vpn/v1/config (the `VpnListV1Config` operationId) request.
	VpnListV1Config(ctx context.Context, params *VpnListV1ConfigParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// VpnListV1LogicalsCount performs a GET /vpn/v1/logicals/count (the `VpnListV1LogicalsCount` operationId) request.
	VpnListV1LogicalsCount(ctx context.Context, params *VpnListV1LogicalsCountParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// VpnCreateV1BusinessMembersUsageWithBody performs a POST /vpn/v1/business/members/usage (the `VpnCreateV1BusinessMembersUsage` operationId) request,
// with any type of body and a specified content type.
func (c *Client) VpnCreateV1BusinessMembersUsageWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewVpnCreateV1BusinessMembersUsageRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// VpnCreateV1BusinessMembersUsage performs a POST /vpn/v1/business/members/usage (the `VpnCreateV1BusinessMembersUsage` operationId) request.
// Takes a body of the `application/json` content type.
func (c *Client) VpnCreateV1BusinessMembersUsage(ctx context.Context, body VpnCreateV1BusinessMembersUsageJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewVpnCreateV1BusinessMembersUsageRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// VpnListV1Config performs a GET /vpn/v1/config (the `VpnListV1Config` operationId) request.
func (c *Client) VpnListV1Config(ctx context.Context, params *VpnListV1ConfigParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewVpnListV1ConfigRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// VpnListV1LogicalsCount performs a GET /vpn/v1/logicals/count (the `VpnListV1LogicalsCount` operationId) request.
func (c *Client) VpnListV1LogicalsCount(ctx context.Context, params *VpnListV1LogicalsCountParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewVpnListV1LogicalsCountRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewVpnCreateV1BusinessMembersUsageRequest calls the generic VpnCreateV1BusinessMembersUsage builder with application/json body
func NewVpnCreateV1BusinessMembersUsageRequest(server string, body VpnCreateV1BusinessMembersUsageJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewVpnCreateV1BusinessMembersUsageRequestWithBody(server, "application/json", bodyReader)
}

// NewVpnCreateV1BusinessMembersUsageRequestWithBody constructs an http.Request for the VpnCreateV1BusinessMembersUsage method, with any body, and a specified content type
func NewVpnCreateV1BusinessMembersUsageRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/vpn/v1/business/members/usage")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewVpnListV1ConfigRequest constructs an http.Request for the VpnListV1Config method
func NewVpnListV1ConfigRequest(server string, params *VpnListV1ConfigParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/vpn/v1/config")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.LogicalID != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "LogicalID", *params.LogicalID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.ServerID != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "ServerID", *params.ServerID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Country != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "Country", *params.Country, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Category != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "Category", *params.Category, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Tier != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "Tier", *params.Tier, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Platform != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "Platform", *params.Platform, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewVpnListV1LogicalsCountRequest constructs an http.Request for the VpnListV1LogicalsCount method
func NewVpnListV1LogicalsCountRequest(server string, params *VpnListV1LogicalsCountParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/vpn/v1/logicals/count")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.GroupBy != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "GroupBy", *params.GroupBy, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// VpnCreateV1BusinessMembersUsageWithBodyWithResponse performs a POST /vpn/v1/business/members/usage (the `VpnCreateV1BusinessMembersUsage` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	VpnCreateV1BusinessMembersUsageWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*VpnCreateV1BusinessMembersUsageResponse, error)

	// VpnCreateV1BusinessMembersUsageWithResponse performs a POST /vpn/v1/business/members/usage (the `VpnCreateV1BusinessMembersUsage` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	VpnCreateV1BusinessMembersUsageWithResponse(ctx context.Context, body VpnCreateV1BusinessMembersUsageJSONRequestBody, reqEditors ...RequestEditorFn) (*VpnCreateV1BusinessMembersUsageResponse, error)

	// VpnListV1ConfigWithResponse performs a GET /vpn/v1/config (the `VpnListV1Config` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	VpnListV1ConfigWithResponse(ctx context.Context, params *VpnListV1ConfigParams, reqEditors ...RequestEditorFn) (*VpnListV1ConfigResponse, error)

	// VpnListV1LogicalsCountWithResponse performs a GET /vpn/v1/logicals/count (the `VpnListV1LogicalsCount` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	VpnListV1LogicalsCountWithResponse(ctx context.Context, params *VpnListV1LogicalsCountParams, reqEditors ...RequestEditorFn) (*VpnListV1LogicalsCountResponse, error)
}

type VpnCreateV1BusinessMembersUsageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r VpnCreateV1BusinessMembersUsageResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r VpnCreateV1BusinessMembersUsageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r VpnCreateV1BusinessMembersUsageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r VpnCreateV1BusinessMembersUsageResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type VpnListV1ConfigResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r VpnListV1ConfigResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r VpnListV1ConfigResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r VpnListV1ConfigResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r VpnListV1ConfigResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type VpnListV1LogicalsCountResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r VpnListV1LogicalsCountResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r VpnListV1LogicalsCountResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r VpnListV1LogicalsCountResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r VpnListV1LogicalsCountResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// VpnCreateV1BusinessMembersUsageWithBodyWithResponse performs a POST /vpn/v1/business/members/usage (the `VpnCreateV1BusinessMembersUsage` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) VpnCreateV1BusinessMembersUsageWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*VpnCreateV1BusinessMembersUsageResponse, error) {
	rsp, err := c.VpnCreateV1BusinessMembersUsageWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVpnCreateV1BusinessMembersUsageResponse(rsp)
}

// VpnCreateV1BusinessMembersUsageWithResponse performs a POST /vpn/v1/business/members/usage (the `VpnCreateV1BusinessMembersUsage` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) VpnCreateV1BusinessMembersUsageWithResponse(ctx context.Context, body VpnCreateV1BusinessMembersUsageJSONRequestBody, reqEditors ...RequestEditorFn) (*VpnCreateV1BusinessMembersUsageResponse, error) {
	rsp, err := c.VpnCreateV1BusinessMembersUsage(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVpnCreateV1BusinessMembersUsageResponse(rsp)
}

// VpnListV1ConfigWithResponse performs a GET /vpn/v1/config (the `VpnListV1Config` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) VpnListV1ConfigWithResponse(ctx context.Context, params *VpnListV1ConfigParams, reqEditors ...RequestEditorFn) (*VpnListV1ConfigResponse, error) {
	rsp, err := c.VpnListV1Config(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVpnListV1ConfigResponse(rsp)
}

// VpnListV1LogicalsCountWithResponse performs a GET /vpn/v1/logicals/count (the `VpnListV1LogicalsCount` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) VpnListV1LogicalsCountWithResponse(ctx context.Context, params *VpnListV1LogicalsCountParams, reqEditors ...RequestEditorFn) (*VpnListV1LogicalsCountResponse, error) {
	rsp, err := c.VpnListV1LogicalsCount(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVpnListV1LogicalsCountResponse(rsp)
}

// ParseVpnCreateV1BusinessMembersUsageResponse parses an HTTP response from a VpnCreateV1BusinessMembersUsageWithResponse call
func ParseVpnCreateV1BusinessMembersUsageResponse(rsp *http.Response) (*VpnCreateV1BusinessMembersUsageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &VpnCreateV1BusinessMembersUsageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseVpnListV1ConfigResponse parses an HTTP response from a VpnListV1ConfigWithResponse call
func ParseVpnListV1ConfigResponse(rsp *http.Response) (*VpnListV1ConfigResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &VpnListV1ConfigResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseVpnListV1LogicalsCountResponse parses an HTTP response from a VpnListV1LogicalsCountWithResponse call
func ParseVpnListV1LogicalsCountResponse(rsp *http.Response) (*VpnListV1LogicalsCountResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &VpnListV1LogicalsCountResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
