// Package vpnapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package vpnapi

// VpnCreateV1BusinessMembersUsageJSONBody defines parameters for VpnCreateV1BusinessMembersUsage.
type VpnCreateV1BusinessMembersUsageJSONBody struct {
	MemberIDs *string `json:"MemberIDs,omitempty"`
}

// VpnListV1ConfigParams defines parameters for VpnListV1Config.
type VpnListV1ConfigParams struct {
	LogicalID *string `form:"LogicalID,omitempty" json:"LogicalID,omitempty"`
	ServerID  *string `form:"ServerID,omitempty" json:"ServerID,omitempty"`
	Country   *string `form:"Country,omitempty" json:"Country,omitempty"`
	Category  *string `form:"Category,omitempty" json:"Category,omitempty"`
	Tier      *string `form:"Tier,omitempty" json:"Tier,omitempty"`
	Platform  *string `form:"Platform,omitempty" json:"Platform,omitempty"`
}

// VpnListV1LogicalsCountParams defines parameters for VpnListV1LogicalsCount.
type VpnListV1LogicalsCountParams struct {
	GroupBy *string `form:"GroupBy,omitempty" json:"GroupBy,omitempty"`
}

// VpnCreateV1BusinessMembersUsageJSONRequestBody defines body for VpnCreateV1BusinessMembersUsage for application/json ContentType.
type VpnCreateV1BusinessMembersUsageJSONRequestBody VpnCreateV1BusinessMembersUsageJSONBody
