// Package domainsapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package domainsapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// CoreListV4Domains performs a GET /core/v4/domains (the `CoreListV4Domains` operationId) request.
	CoreListV4Domains(ctx context.Context, params *CoreListV4DomainsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CoreCreateV4DomainsWithBody performs a POST /core/v4/domains (the `CoreCreateV4Domains` operationId) request,
	// with any type of body and a specified content type.
	CoreCreateV4DomainsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CoreCreateV4Domains performs a POST /core/v4/domains (the `CoreCreateV4Domains` operationId) request.
	// Takes a body of the `application/json` content type.
	CoreCreateV4Domains(ctx context.Context, body CoreCreateV4DomainsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CoreListV4DomainsAvailable performs a GET /core/v4/domains/available (the `CoreListV4DomainsAvailable` operationId) request.
	CoreListV4DomainsAvailable(ctx context.Context, params *CoreListV4DomainsAvailableParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CoreDeleteV4Domain performs a DELETE /core/v4/domains/{domainId} (the `CoreDeleteV4Domain` operationId) request.
	CoreDeleteV4Domain(ctx context.Context, domainId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CoreGetV4Domain performs a GET /core/v4/domains/{domainId} (the `CoreGetV4Domain` operationId) request.
	CoreGetV4Domain(ctx context.Context, domainId string, params *CoreGetV4DomainParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CoreListV4DomainsAddresses performs a GET /core/v4/domains/{domainId}/addresses (the `CoreListV4DomainsAddresses` operationId) request.
	CoreListV4DomainsAddresses(ctx context.Context, domainId string, params *CoreListV4DomainsAddressesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CoreUpdateV4DomainsCatchallWithBody performs a PUT /core/v4/domains/{domainId}/catchall (the `CoreUpdateV4DomainsCatchall` operationId) request,
	// with any type of body and a specified content type.
	CoreUpdateV4DomainsCatchallWithBody(ctx context.Context, domainId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CoreUpdateV4DomainsCatchall performs a PUT /core/v4/domains/{domainId}/catchall (the `CoreUpdateV4DomainsCatchall` operationId) request.
	// Takes a body of the `application/json` content type.
	CoreUpdateV4DomainsCatchall(ctx context.Context, domainId string, body CoreUpdateV4DomainsCatchallJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CoreListV4DomainsClaimedaddresses performs a GET /core/v4/domains/{domainId}/claimedAddresses (the `CoreListV4DomainsClaimedaddresses` operationId) request.
	CoreListV4DomainsClaimedaddresses(ctx context.Context, domainId string, params *CoreListV4DomainsClaimedaddressesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CoreUpdateV4DomainsFlagsWithBody performs a PUT /core/v4/domains/{domainId}/flags (the `CoreUpdateV4DomainsFlags` operationId) request,
	// with any type of body and a specified content type.
	CoreUpdateV4DomainsFlagsWithBody(ctx context.Context, domainId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CoreUpdateV4DomainsFlags performs a PUT /core/v4/domains/{domainId}/flags (the `CoreUpdateV4DomainsFlags` operationId) request.
	// Takes a body of the `application/json` content type.
	CoreUpdateV4DomainsFlags(ctx context.Context, domainId string, body CoreUpdateV4DomainsFlagsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DomainsListDomains performs a GET /domains (the `DomainsListDomains` operationId) request.
	DomainsListDomains(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DomainsCreateDomainsWithBody performs a POST /domains (the `DomainsCreateDomains` operationId) request,
	// with any type of body and a specified content type.
	DomainsCreateDomainsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DomainsCreateDomains performs a POST /domains (the `DomainsCreateDomains` operationId) request.
	// Takes a body of the `application/json` content type.
	DomainsCreateDomains(ctx context.Context, body DomainsCreateDomainsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DomainsDeleteDomain performs a DELETE /domains/{domainId} (the `DomainsDeleteDomain` operationId) request.
	DomainsDeleteDomain(ctx context.Context, domainId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DomainsGetDomain performs a GET /domains/{domainId} (the `DomainsGetDomain` operationId) request.
	DomainsGetDomain(ctx context.Context, domainId string, params *DomainsGetDomainParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// CoreListV4Domains performs a GET /core/v4/domains (the `CoreListV4Domains` operationId) request.
func (c *Client) CoreListV4Domains(ctx context.Context, params *CoreListV4DomainsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCoreListV4DomainsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CoreCreateV4DomainsWithBody performs a POST /core/v4/domains (the `CoreCreateV4Domains` operationId) request,
// with any type of body and a specified content type.
func (c *Client) CoreCreateV4DomainsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCoreCreateV4DomainsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CoreCreateV4Domains performs a POST /core/v4/domains (the `CoreCreateV4Domains` operationId) request.
// Takes a body of the `application/json` content type.
func (c *Client) CoreCreateV4Domains(ctx context.Context, body CoreCreateV4DomainsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCoreCreateV4DomainsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CoreListV4DomainsAvailable performs a GET /core/v4/domains/available (the `CoreListV4DomainsAvailable` operationId) request.
func (c *Client) CoreListV4DomainsAvailable(ctx context.Context, params *CoreListV4DomainsAvailableParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCoreListV4DomainsAvailableRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CoreDeleteV4Domain performs a DELETE /core/v4/domains/{domainId} (the `CoreDeleteV4Domain` operationId) request.
func (c *Client) CoreDeleteV4Domain(ctx context.Context, domainId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCoreDeleteV4DomainRequest(c.Server, domainId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CoreGetV4Domain performs a GET /core/v4/domains/{domainId} (the `CoreGetV4Domain` operationId) request.
func (c *Client) CoreGetV4Domain(ctx context.Context, domainId string, params *CoreGetV4DomainParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCoreGetV4DomainRequest(c.Server, domainId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CoreListV4DomainsAddresses performs a GET /core/v4/domains/{domainId}/addresses (the `CoreListV4DomainsAddresses` operationId) request.
func (c *Client) CoreListV4DomainsAddresses(ctx context.Context, domainId string, params *CoreListV4DomainsAddressesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCoreListV4DomainsAddressesRequest(c.Server, domainId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CoreUpdateV4DomainsCatchallWithBody performs a PUT /core/v4/domains/{domainId}/catchall (the `CoreUpdateV4DomainsCatchall` operationId) request,
// with any type of body and a specified content type.
func (c *Client) CoreUpdateV4DomainsCatchallWithBody(ctx context.Context, domainId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCoreUpdateV4DomainsCatchallRequestWithBody(c.Server, domainId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CoreUpdateV4DomainsCatchall performs a PUT /core/v4/domains/{domainId}/catchall (the `CoreUpdateV4DomainsCatchall` operationId) request.
// Takes a body of the `application/json` content type.
func (c *Client) CoreUpdateV4DomainsCatchall(ctx context.Context, domainId string, body CoreUpdateV4DomainsCatchallJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCoreUpdateV4DomainsCatchallRequest(c.Server, domainId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CoreListV4DomainsClaimedaddresses performs a GET /core/v4/domains/{domainId}/claimedAddresses (the `CoreListV4DomainsClaimedaddresses` operationId) request.
func (c *Client) CoreListV4DomainsClaimedaddresses(ctx context.Context, domainId string, params *CoreListV4DomainsClaimedaddressesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCoreListV4DomainsClaimedaddressesRequest(c.Server, domainId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CoreUpdateV4DomainsFlagsWithBody performs a PUT /core/v4/domains/{domainId}/flags (the `CoreUpdateV4DomainsFlags` operationId) request,
// with any type of body and a specified content type.
func (c *Client) CoreUpdateV4DomainsFlagsWithBody(ctx context.Context, domainId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCoreUpdateV4DomainsFlagsRequestWithBody(c.Server, domainId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CoreUpdateV4DomainsFlags performs a PUT /core/v4/domains/{domainId}/flags (the `CoreUpdateV4DomainsFlags` operationId) request.
// Takes a body of the `application/json` content type.
func (c *Client) CoreUpdateV4DomainsFlags(ctx context.Context, domainId string, body CoreUpdateV4DomainsFlagsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCoreUpdateV4DomainsFlagsRequest(c.Server, domainId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DomainsListDomains performs a GET /domains (the `DomainsListDomains` operationId) request.
func (c *Client) DomainsListDomains(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDomainsListDomainsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DomainsCreateDomainsWithBody performs a POST /domains (the `DomainsCreateDomains` operationId) request,
// with any type of body and a specified content type.
func (c *Client) DomainsCreateDomainsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDomainsCreateDomainsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DomainsCreateDomains performs a POST /domains (the `DomainsCreateDomains` operationId) request.
// Takes a body of the `application/json` content type.
func (c *Client) DomainsCreateDomains(ctx context.Context, body DomainsCreateDomainsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDomainsCreateDomainsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DomainsDeleteDomain performs a DELETE /domains/{domainId} (the `DomainsDeleteDomain` operationId) request.
func (c *Client) DomainsDeleteDomain(ctx context.Context, domainId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDomainsDeleteDomainRequest(c.Server, domainId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DomainsGetDomain performs a GET /domains/{domainId} (the `DomainsGetDomain` operationId) request.
func (c *Client) DomainsGetDomain(ctx context.Context, domainId string, params *DomainsGetDomainParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDomainsGetDomainRequest(c.Server, domainId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCoreListV4DomainsRequest constructs an http.Request for the CoreListV4Domains method
func NewCoreListV4DomainsRequest(server string, params *CoreListV4DomainsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/core/v4/domains")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "PageSize", *params.PageSize, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "Page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCoreCreateV4DomainsRequest calls the generic CoreCreateV4Domains builder with application/json body
func NewCoreCreateV4DomainsRequest(server string, body CoreCreateV4DomainsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCoreCreateV4DomainsRequestWithBody(server, "application/json", bodyReader)
}

// NewCoreCreateV4DomainsRequestWithBody constructs an http.Request for the CoreCreateV4Domains method, with any body, and a specified content type
func NewCoreCreateV4DomainsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/core/v4/domains")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCoreListV4DomainsAvailableRequest constructs an http.Request for the CoreListV4DomainsAvailable method
func NewCoreListV4DomainsAvailableRequest(server string, params *CoreListV4DomainsAvailableParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/core/v4/domains/available")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Type != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "Type", *params.Type, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCoreDeleteV4DomainRequest constructs an http.Request for the CoreDeleteV4Domain method
func NewCoreDeleteV4DomainRequest(server string, domainId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "domainId", domainId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/core/v4/domains/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCoreGetV4DomainRequest constructs an http.Request for the CoreGetV4Domain method
func NewCoreGetV4DomainRequest(server string, domainId string, params *CoreGetV4DomainParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "domainId", domainId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/core/v4/domains/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Refresh != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "Refresh", *params.Refresh, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCoreListV4DomainsAddressesRequest constructs an http.Request for the CoreListV4DomainsAddresses method
func NewCoreListV4DomainsAddressesRequest(server string, domainId string, params *CoreListV4DomainsAddressesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "domainId", domainId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/core/v4/domains/%s/addresses", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "Page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "PageSize", *params.PageSize, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "number", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCoreUpdateV4DomainsCatchallRequest calls the generic CoreUpdateV4DomainsCatchall builder with application/json body
func NewCoreUpdateV4DomainsCatchallRequest(server string, domainId string, body CoreUpdateV4DomainsCatchallJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCoreUpdateV4DomainsCatchallRequestWithBody(server, domainId, "application/json", bodyReader)
}

// NewCoreUpdateV4DomainsCatchallRequestWithBody constructs an http.Request for the CoreUpdateV4DomainsCatchall method, with any body, and a specified content type
func NewCoreUpdateV4DomainsCatchallRequestWithBody(server string, domainId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "domainId", domainId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/core/v4/domains/%s/catchall", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCoreListV4DomainsClaimedaddressesRequest constructs an http.Request for the CoreListV4DomainsClaimedaddresses method
func NewCoreListV4DomainsClaimedaddressesRequest(server string, domainId string, params *CoreListV4DomainsClaimedaddressesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "domainId", domainId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/core/v4/domains/%s/claimedAddresses", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "Page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "PageSize", *params.PageSize, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "number", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCoreUpdateV4DomainsFlagsRequest calls the generic CoreUpdateV4DomainsFlags builder with application/json body
func NewCoreUpdateV4DomainsFlagsRequest(server string, domainId string, body CoreUpdateV4DomainsFlagsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCoreUpdateV4DomainsFlagsRequestWithBody(server, domainId, "application/json", bodyReader)
}

// NewCoreUpdateV4DomainsFlagsRequestWithBody constructs an http.Request for the CoreUpdateV4DomainsFlags method, with any body, and a specified content type
func NewCoreUpdateV4DomainsFlagsRequestWithBody(server string, domainId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "domainId", domainId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/core/v4/domains/%s/flags", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDomainsListDomainsRequest constructs an http.Request for the DomainsListDomains method
func NewDomainsListDomainsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDomainsCreateDomainsRequest calls the generic DomainsCreateDomains builder with application/json body
func NewDomainsCreateDomainsRequest(server string, body DomainsCreateDomainsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewDomainsCreateDomainsRequestWithBody(server, "application/json", bodyReader)
}

// NewDomainsCreateDomainsRequestWithBody constructs an http.Request for the DomainsCreateDomains method, with any body, and a specified content type
func NewDomainsCreateDomainsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDomainsDeleteDomainRequest constructs an http.Request for the DomainsDeleteDomain method
func NewDomainsDeleteDomainRequest(server string, domainId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "domainId", domainId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDomainsGetDomainRequest constructs an http.Request for the DomainsGetDomain method
func NewDomainsGetDomainRequest(server string, domainId string, params *DomainsGetDomainParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "domainId", domainId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Refresh != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "Refresh", *params.Refresh, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// CoreListV4DomainsWithResponse performs a GET /core/v4/domains (the `CoreListV4Domains` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	CoreListV4DomainsWithResponse(ctx context.Context, params *CoreListV4DomainsParams, reqEditors ...RequestEditorFn) (*CoreListV4DomainsResponse, error)

	// CoreCreateV4DomainsWithBodyWithResponse performs a POST /core/v4/domains (the `CoreCreateV4Domains` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	CoreCreateV4DomainsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CoreCreateV4DomainsResponse, error)

	// CoreCreateV4DomainsWithResponse performs a POST /core/v4/domains (the `CoreCreateV4Domains` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	CoreCreateV4DomainsWithResponse(ctx context.Context, body CoreCreateV4DomainsJSONRequestBody, reqEditors ...RequestEditorFn) (*CoreCreateV4DomainsResponse, error)

	// CoreListV4DomainsAvailableWithResponse performs a GET /core/v4/domains/available (the `CoreListV4DomainsAvailable` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	CoreListV4DomainsAvailableWithResponse(ctx context.Context, params *CoreListV4DomainsAvailableParams, reqEditors ...RequestEditorFn) (*CoreListV4DomainsAvailableResponse, error)

	// CoreDeleteV4DomainWithResponse performs a DELETE /core/v4/domains/{domainId} (the `CoreDeleteV4Domain` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	CoreDeleteV4DomainWithResponse(ctx context.Context, domainId string, reqEditors ...RequestEditorFn) (*CoreDeleteV4DomainResponse, error)

	// CoreGetV4DomainWithResponse performs a GET /core/v4/domains/{domainId} (the `CoreGetV4Domain` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	CoreGetV4DomainWithResponse(ctx context.Context, domainId string, params *CoreGetV4DomainParams, reqEditors ...RequestEditorFn) (*CoreGetV4DomainResponse, error)

	// CoreListV4DomainsAddressesWithResponse performs a GET /core/v4/domains/{domainId}/addresses (the `CoreListV4DomainsAddresses` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	CoreListV4DomainsAddressesWithResponse(ctx context.Context, domainId string, params *CoreListV4DomainsAddressesParams, reqEditors ...RequestEditorFn) (*CoreListV4DomainsAddressesResponse, error)

	// CoreUpdateV4DomainsCatchallWithBodyWithResponse performs a PUT /core/v4/domains/{domainId}/catchall (the `CoreUpdateV4DomainsCatchall` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	CoreUpdateV4DomainsCatchallWithBodyWithResponse(ctx context.Context, domainId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CoreUpdateV4DomainsCatchallResponse, error)

	// CoreUpdateV4DomainsCatchallWithResponse performs a PUT /core/v4/domains/{domainId}/catchall (the `CoreUpdateV4DomainsCatchall` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	CoreUpdateV4DomainsCatchallWithResponse(ctx context.Context, domainId string, body CoreUpdateV4DomainsCatchallJSONRequestBody, reqEditors ...RequestEditorFn) (*CoreUpdateV4DomainsCatchallResponse, error)

	// CoreListV4DomainsClaimedaddressesWithResponse performs a GET /core/v4/domains/{domainId}/claimedAddresses (the `CoreListV4DomainsClaimedaddresses` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	CoreListV4DomainsClaimedaddressesWithResponse(ctx context.Context, domainId string, params *CoreListV4DomainsClaimedaddressesParams, reqEditors ...RequestEditorFn) (*CoreListV4DomainsClaimedaddressesResponse, error)

	// CoreUpdateV4DomainsFlagsWithBodyWithResponse performs a PUT /core/v4/domains/{domainId}/flags (the `CoreUpdateV4DomainsFlags` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	CoreUpdateV4DomainsFlagsWithBodyWithResponse(ctx context.Context, domainId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CoreUpdateV4DomainsFlagsResponse, error)

	// CoreUpdateV4DomainsFlagsWithResponse performs a PUT /core/v4/domains/{domainId}/flags (the `CoreUpdateV4DomainsFlags` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	CoreUpdateV4DomainsFlagsWithResponse(ctx context.Context, domainId string, body CoreUpdateV4DomainsFlagsJSONRequestBody, reqEditors ...RequestEditorFn) (*CoreUpdateV4DomainsFlagsResponse, error)

	// DomainsListDomainsWithResponse performs a GET /domains (the `DomainsListDomains` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	DomainsListDomainsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*DomainsListDomainsResponse, error)

	// DomainsCreateDomainsWithBodyWithResponse performs a POST /domains (the `DomainsCreateDomains` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	DomainsCreateDomainsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DomainsCreateDomainsResponse, error)

	// DomainsCreateDomainsWithResponse performs a POST /domains (the `DomainsCreateDomains` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	DomainsCreateDomainsWithResponse(ctx context.Context, body DomainsCreateDomainsJSONRequestBody, reqEditors ...RequestEditorFn) (*DomainsCreateDomainsResponse, error)

	// DomainsDeleteDomainWithResponse performs a DELETE /domains/{domainId} (the `DomainsDeleteDomain` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	DomainsDeleteDomainWithResponse(ctx context.Context, domainId string, reqEditors ...RequestEditorFn) (*DomainsDeleteDomainResponse, error)

	// DomainsGetDomainWithResponse performs a GET /domains/{domainId} (the `DomainsGetDomain` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	DomainsGetDomainWithResponse(ctx context.Context, domainId string, params *DomainsGetDomainParams, reqEditors ...RequestEditorFn) (*DomainsGetDomainResponse, error)
}

type CoreListV4DomainsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		Code    *string `json:"Code,omitempty"`
		Domains *struct {
			CheckTime *float32 `json:"CheckTime,omitempty"`
			DKIM      *struct {
				// Config Contains the domain's currently configured DKIM public keys and metadata
				Config *string                                               `json:"Config,omitempty"`
				State  *CoreListV4Domains200JSONResponseBodyDomainsDKIMState `json:"State,omitempty"`
			} `json:"DKIM,omitempty"`
			DmarcState *CoreListV4Domains200JSONResponseBodyDomainsDmarcState `json:"DmarcState,omitempty"`
			DomainName *string                                                `json:"DomainName,omitempty"`

			// Flags DomainFlagsOutput
			Flags          *map[string]interface{}                                 `json:"Flags,omitempty"`
			ID             *string                                                 `json:"ID,omitempty"`
			LastActiveTime *float32                                                `json:"LastActiveTime,omitempty"`
			MxState        *CoreListV4Domains200JSONResponseBodyDomainsMxState     `json:"MxState,omitempty"`
			SpfState       *CoreListV4Domains200JSONResponseBodyDomainsSpfState    `json:"SpfState,omitempty"`
			State          *CoreListV4Domains200JSONResponseBodyDomainsState       `json:"State,omitempty"`
			Type           *CoreListV4Domains200JSONResponseBodyDomainsType        `json:"Type,omitempty"`
			VerifyCode     *string                                                 `json:"VerifyCode,omitempty"`
			VerifyState    *CoreListV4Domains200JSONResponseBodyDomainsVerifyState `json:"VerifyState,omitempty"`
			WarnTime       *float32                                                `json:"WarnTime,omitempty"`
		} `json:"Domains,omitempty"`
		Total *float32 `json:"Total,omitempty"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r CoreListV4DomainsResponse) GetJSON200() *struct {
	Code    *string `json:"Code,omitempty"`
	Domains *struct {
		CheckTime *float32 `json:"CheckTime,omitempty"`
		DKIM      *struct {
			// Config Contains the domain's currently configured DKIM public keys and metadata
			Config *string                                               `json:"Config,omitempty"`
			State  *CoreListV4Domains200JSONResponseBodyDomainsDKIMState `json:"State,omitempty"`
		} `json:"DKIM,omitempty"`
		DmarcState *CoreListV4Domains200JSONResponseBodyDomainsDmarcState `json:"DmarcState,omitempty"`
		DomainName *string                                                `json:"DomainName,omitempty"`

		// Flags DomainFlagsOutput
		Flags          *map[string]interface{}                                 `json:"Flags,omitempty"`
		ID             *string                                                 `json:"ID,omitempty"`
		LastActiveTime *float32                                                `json:"LastActiveTime,omitempty"`
		MxState        *CoreListV4Domains200JSONResponseBodyDomainsMxState     `json:"MxState,omitempty"`
		SpfState       *CoreListV4Domains200JSONResponseBodyDomainsSpfState    `json:"SpfState,omitempty"`
		State          *CoreListV4Domains200JSONResponseBodyDomainsState       `json:"State,omitempty"`
		Type           *CoreListV4Domains200JSONResponseBodyDomainsType        `json:"Type,omitempty"`
		VerifyCode     *string                                                 `json:"VerifyCode,omitempty"`
		VerifyState    *CoreListV4Domains200JSONResponseBodyDomainsVerifyState `json:"VerifyState,omitempty"`
		WarnTime       *float32                                                `json:"WarnTime,omitempty"`
	} `json:"Domains,omitempty"`
	Total *float32 `json:"Total,omitempty"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r CoreListV4DomainsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CoreListV4DomainsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CoreListV4DomainsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CoreListV4DomainsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CoreCreateV4DomainsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r CoreCreateV4DomainsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CoreCreateV4DomainsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CoreCreateV4DomainsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CoreCreateV4DomainsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CoreListV4DomainsAvailableResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r CoreListV4DomainsAvailableResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CoreListV4DomainsAvailableResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CoreListV4DomainsAvailableResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CoreListV4DomainsAvailableResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CoreDeleteV4DomainResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON422 the response for an HTTP 422 `application/json` response
	JSON422 *struct {
		Code  *float32 `json:"Code,omitempty"`
		Error *string  `json:"Error,omitempty"`
	}
}

// GetJSON422 returns the response for an HTTP 422 `application/json` response
func (r CoreDeleteV4DomainResponse) GetJSON422() *struct {
	Code  *float32 `json:"Code,omitempty"`
	Error *string  `json:"Error,omitempty"`
} {
	return r.JSON422
}

// GetBody returns the raw response body bytes
func (r CoreDeleteV4DomainResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CoreDeleteV4DomainResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CoreDeleteV4DomainResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CoreDeleteV4DomainResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CoreGetV4DomainResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r CoreGetV4DomainResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CoreGetV4DomainResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CoreGetV4DomainResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CoreGetV4DomainResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CoreListV4DomainsAddressesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r CoreListV4DomainsAddressesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CoreListV4DomainsAddressesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CoreListV4DomainsAddressesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CoreListV4DomainsAddressesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CoreUpdateV4DomainsCatchallResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r CoreUpdateV4DomainsCatchallResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CoreUpdateV4DomainsCatchallResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CoreUpdateV4DomainsCatchallResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CoreUpdateV4DomainsCatchallResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CoreListV4DomainsClaimedaddressesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r CoreListV4DomainsClaimedaddressesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CoreListV4DomainsClaimedaddressesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CoreListV4DomainsClaimedaddressesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CoreListV4DomainsClaimedaddressesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CoreUpdateV4DomainsFlagsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r CoreUpdateV4DomainsFlagsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CoreUpdateV4DomainsFlagsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CoreUpdateV4DomainsFlagsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CoreUpdateV4DomainsFlagsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DomainsListDomainsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r DomainsListDomainsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DomainsListDomainsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DomainsListDomainsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DomainsListDomainsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DomainsCreateDomainsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r DomainsCreateDomainsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DomainsCreateDomainsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DomainsCreateDomainsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DomainsCreateDomainsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DomainsDeleteDomainResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r DomainsDeleteDomainResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DomainsDeleteDomainResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DomainsDeleteDomainResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DomainsDeleteDomainResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DomainsGetDomainResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r DomainsGetDomainResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DomainsGetDomainResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DomainsGetDomainResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DomainsGetDomainResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// CoreListV4DomainsWithResponse performs a GET /core/v4/domains (the `CoreListV4Domains` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) CoreListV4DomainsWithResponse(ctx context.Context, params *CoreListV4DomainsParams, reqEditors ...RequestEditorFn) (*CoreListV4DomainsResponse, error) {
	rsp, err := c.CoreListV4Domains(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCoreListV4DomainsResponse(rsp)
}

// CoreCreateV4DomainsWithBodyWithResponse performs a POST /core/v4/domains (the `CoreCreateV4Domains` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) CoreCreateV4DomainsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CoreCreateV4DomainsResponse, error) {
	rsp, err := c.CoreCreateV4DomainsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCoreCreateV4DomainsResponse(rsp)
}

// CoreCreateV4DomainsWithResponse performs a POST /core/v4/domains (the `CoreCreateV4Domains` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) CoreCreateV4DomainsWithResponse(ctx context.Context, body CoreCreateV4DomainsJSONRequestBody, reqEditors ...RequestEditorFn) (*CoreCreateV4DomainsResponse, error) {
	rsp, err := c.CoreCreateV4Domains(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCoreCreateV4DomainsResponse(rsp)
}

// CoreListV4DomainsAvailableWithResponse performs a GET /core/v4/domains/available (the `CoreListV4DomainsAvailable` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) CoreListV4DomainsAvailableWithResponse(ctx context.Context, params *CoreListV4DomainsAvailableParams, reqEditors ...RequestEditorFn) (*CoreListV4DomainsAvailableResponse, error) {
	rsp, err := c.CoreListV4DomainsAvailable(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCoreListV4DomainsAvailableResponse(rsp)
}

// CoreDeleteV4DomainWithResponse performs a DELETE /core/v4/domains/{domainId} (the `CoreDeleteV4Domain` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) CoreDeleteV4DomainWithResponse(ctx context.Context, domainId string, reqEditors ...RequestEditorFn) (*CoreDeleteV4DomainResponse, error) {
	rsp, err := c.CoreDeleteV4Domain(ctx, domainId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCoreDeleteV4DomainResponse(rsp)
}

// CoreGetV4DomainWithResponse performs a GET /core/v4/domains/{domainId} (the `CoreGetV4Domain` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) CoreGetV4DomainWithResponse(ctx context.Context, domainId string, params *CoreGetV4DomainParams, reqEditors ...RequestEditorFn) (*CoreGetV4DomainResponse, error) {
	rsp, err := c.CoreGetV4Domain(ctx, domainId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCoreGetV4DomainResponse(rsp)
}

// CoreListV4DomainsAddressesWithResponse performs a GET /core/v4/domains/{domainId}/addresses (the `CoreListV4DomainsAddresses` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) CoreListV4DomainsAddressesWithResponse(ctx context.Context, domainId string, params *CoreListV4DomainsAddressesParams, reqEditors ...RequestEditorFn) (*CoreListV4DomainsAddressesResponse, error) {
	rsp, err := c.CoreListV4DomainsAddresses(ctx, domainId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCoreListV4DomainsAddressesResponse(rsp)
}

// CoreUpdateV4DomainsCatchallWithBodyWithResponse performs a PUT /core/v4/domains/{domainId}/catchall (the `CoreUpdateV4DomainsCatchall` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) CoreUpdateV4DomainsCatchallWithBodyWithResponse(ctx context.Context, domainId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CoreUpdateV4DomainsCatchallResponse, error) {
	rsp, err := c.CoreUpdateV4DomainsCatchallWithBody(ctx, domainId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCoreUpdateV4DomainsCatchallResponse(rsp)
}

// CoreUpdateV4DomainsCatchallWithResponse performs a PUT /core/v4/domains/{domainId}/catchall (the `CoreUpdateV4DomainsCatchall` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) CoreUpdateV4DomainsCatchallWithResponse(ctx context.Context, domainId string, body CoreUpdateV4DomainsCatchallJSONRequestBody, reqEditors ...RequestEditorFn) (*CoreUpdateV4DomainsCatchallResponse, error) {
	rsp, err := c.CoreUpdateV4DomainsCatchall(ctx, domainId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCoreUpdateV4DomainsCatchallResponse(rsp)
}

// CoreListV4DomainsClaimedaddressesWithResponse performs a GET /core/v4/domains/{domainId}/claimedAddresses (the `CoreListV4DomainsClaimedaddresses` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) CoreListV4DomainsClaimedaddressesWithResponse(ctx context.Context, domainId string, params *CoreListV4DomainsClaimedaddressesParams, reqEditors ...RequestEditorFn) (*CoreListV4DomainsClaimedaddressesResponse, error) {
	rsp, err := c.CoreListV4DomainsClaimedaddresses(ctx, domainId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCoreListV4DomainsClaimedaddressesResponse(rsp)
}

// CoreUpdateV4DomainsFlagsWithBodyWithResponse performs a PUT /core/v4/domains/{domainId}/flags (the `CoreUpdateV4DomainsFlags` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) CoreUpdateV4DomainsFlagsWithBodyWithResponse(ctx context.Context, domainId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CoreUpdateV4DomainsFlagsResponse, error) {
	rsp, err := c.CoreUpdateV4DomainsFlagsWithBody(ctx, domainId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCoreUpdateV4DomainsFlagsResponse(rsp)
}

// CoreUpdateV4DomainsFlagsWithResponse performs a PUT /core/v4/domains/{domainId}/flags (the `CoreUpdateV4DomainsFlags` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) CoreUpdateV4DomainsFlagsWithResponse(ctx context.Context, domainId string, body CoreUpdateV4DomainsFlagsJSONRequestBody, reqEditors ...RequestEditorFn) (*CoreUpdateV4DomainsFlagsResponse, error) {
	rsp, err := c.CoreUpdateV4DomainsFlags(ctx, domainId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCoreUpdateV4DomainsFlagsResponse(rsp)
}

// DomainsListDomainsWithResponse performs a GET /domains (the `DomainsListDomains` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) DomainsListDomainsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*DomainsListDomainsResponse, error) {
	rsp, err := c.DomainsListDomains(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDomainsListDomainsResponse(rsp)
}

// DomainsCreateDomainsWithBodyWithResponse performs a POST /domains (the `DomainsCreateDomains` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) DomainsCreateDomainsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DomainsCreateDomainsResponse, error) {
	rsp, err := c.DomainsCreateDomainsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDomainsCreateDomainsResponse(rsp)
}

// DomainsCreateDomainsWithResponse performs a POST /domains (the `DomainsCreateDomains` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) DomainsCreateDomainsWithResponse(ctx context.Context, body DomainsCreateDomainsJSONRequestBody, reqEditors ...RequestEditorFn) (*DomainsCreateDomainsResponse, error) {
	rsp, err := c.DomainsCreateDomains(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDomainsCreateDomainsResponse(rsp)
}

// DomainsDeleteDomainWithResponse performs a DELETE /domains/{domainId} (the `DomainsDeleteDomain` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) DomainsDeleteDomainWithResponse(ctx context.Context, domainId string, reqEditors ...RequestEditorFn) (*DomainsDeleteDomainResponse, error) {
	rsp, err := c.DomainsDeleteDomain(ctx, domainId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDomainsDeleteDomainResponse(rsp)
}

// DomainsGetDomainWithResponse performs a GET /domains/{domainId} (the `DomainsGetDomain` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) DomainsGetDomainWithResponse(ctx context.Context, domainId string, params *DomainsGetDomainParams, reqEditors ...RequestEditorFn) (*DomainsGetDomainResponse, error) {
	rsp, err := c.DomainsGetDomain(ctx, domainId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDomainsGetDomainResponse(rsp)
}

// ParseCoreListV4DomainsResponse parses an HTTP response from a CoreListV4DomainsWithResponse call
func ParseCoreListV4DomainsResponse(rsp *http.Response) (*CoreListV4DomainsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CoreListV4DomainsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Code    *string `json:"Code,omitempty"`
			Domains *struct {
				CheckTime *float32 `json:"CheckTime,omitempty"`
				DKIM      *struct {
					// Config Contains the domain's currently configured DKIM public keys and metadata
					Config *string                                               `json:"Config,omitempty"`
					State  *CoreListV4Domains200JSONResponseBodyDomainsDKIMState `json:"State,omitempty"`
				} `json:"DKIM,omitempty"`
				DmarcState *CoreListV4Domains200JSONResponseBodyDomainsDmarcState `json:"DmarcState,omitempty"`
				DomainName *string                                                `json:"DomainName,omitempty"`

				// Flags DomainFlagsOutput
				Flags          *map[string]interface{}                                 `json:"Flags,omitempty"`
				ID             *string                                                 `json:"ID,omitempty"`
				LastActiveTime *float32                                                `json:"LastActiveTime,omitempty"`
				MxState        *CoreListV4Domains200JSONResponseBodyDomainsMxState     `json:"MxState,omitempty"`
				SpfState       *CoreListV4Domains200JSONResponseBodyDomainsSpfState    `json:"SpfState,omitempty"`
				State          *CoreListV4Domains200JSONResponseBodyDomainsState       `json:"State,omitempty"`
				Type           *CoreListV4Domains200JSONResponseBodyDomainsType        `json:"Type,omitempty"`
				VerifyCode     *string                                                 `json:"VerifyCode,omitempty"`
				VerifyState    *CoreListV4Domains200JSONResponseBodyDomainsVerifyState `json:"VerifyState,omitempty"`
				WarnTime       *float32                                                `json:"WarnTime,omitempty"`
			} `json:"Domains,omitempty"`
			Total *float32 `json:"Total,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCoreCreateV4DomainsResponse parses an HTTP response from a CoreCreateV4DomainsWithResponse call
func ParseCoreCreateV4DomainsResponse(rsp *http.Response) (*CoreCreateV4DomainsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CoreCreateV4DomainsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseCoreListV4DomainsAvailableResponse parses an HTTP response from a CoreListV4DomainsAvailableWithResponse call
func ParseCoreListV4DomainsAvailableResponse(rsp *http.Response) (*CoreListV4DomainsAvailableResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CoreListV4DomainsAvailableResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseCoreDeleteV4DomainResponse parses an HTTP response from a CoreDeleteV4DomainWithResponse call
func ParseCoreDeleteV4DomainResponse(rsp *http.Response) (*CoreDeleteV4DomainResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CoreDeleteV4DomainResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			Code  *float32 `json:"Code,omitempty"`
			Error *string  `json:"Error,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseCoreGetV4DomainResponse parses an HTTP response from a CoreGetV4DomainWithResponse call
func ParseCoreGetV4DomainResponse(rsp *http.Response) (*CoreGetV4DomainResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CoreGetV4DomainResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseCoreListV4DomainsAddressesResponse parses an HTTP response from a CoreListV4DomainsAddressesWithResponse call
func ParseCoreListV4DomainsAddressesResponse(rsp *http.Response) (*CoreListV4DomainsAddressesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CoreListV4DomainsAddressesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseCoreUpdateV4DomainsCatchallResponse parses an HTTP response from a CoreUpdateV4DomainsCatchallWithResponse call
func ParseCoreUpdateV4DomainsCatchallResponse(rsp *http.Response) (*CoreUpdateV4DomainsCatchallResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CoreUpdateV4DomainsCatchallResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseCoreListV4DomainsClaimedaddressesResponse parses an HTTP response from a CoreListV4DomainsClaimedaddressesWithResponse call
func ParseCoreListV4DomainsClaimedaddressesResponse(rsp *http.Response) (*CoreListV4DomainsClaimedaddressesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CoreListV4DomainsClaimedaddressesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseCoreUpdateV4DomainsFlagsResponse parses an HTTP response from a CoreUpdateV4DomainsFlagsWithResponse call
func ParseCoreUpdateV4DomainsFlagsResponse(rsp *http.Response) (*CoreUpdateV4DomainsFlagsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CoreUpdateV4DomainsFlagsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseDomainsListDomainsResponse parses an HTTP response from a DomainsListDomainsWithResponse call
func ParseDomainsListDomainsResponse(rsp *http.Response) (*DomainsListDomainsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DomainsListDomainsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseDomainsCreateDomainsResponse parses an HTTP response from a DomainsCreateDomainsWithResponse call
func ParseDomainsCreateDomainsResponse(rsp *http.Response) (*DomainsCreateDomainsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DomainsCreateDomainsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseDomainsDeleteDomainResponse parses an HTTP response from a DomainsDeleteDomainWithResponse call
func ParseDomainsDeleteDomainResponse(rsp *http.Response) (*DomainsDeleteDomainResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DomainsDeleteDomainResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseDomainsGetDomainResponse parses an HTTP response from a DomainsGetDomainWithResponse call
func ParseDomainsGetDomainResponse(rsp *http.Response) (*DomainsGetDomainResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DomainsGetDomainResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
