// Package calendarapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package calendarapi

// Defines values for CoreGetV4Event200JSONResponseBodyCode.
const (
	CoreGetV4Event200JSONResponseBodyCodeN1000 CoreGetV4Event200JSONResponseBodyCode = 1000
)

// Valid indicates whether the value is a known member of the CoreGetV4Event200JSONResponseBodyCode enum.
func (e CoreGetV4Event200JSONResponseBodyCode) Valid() bool {
	switch e {
	case CoreGetV4Event200JSONResponseBodyCodeN1000:
		return true
	default:
		return false
	}
}

// Defines values for CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingFilterVersion.
const (
	CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingFilterVersionN2 CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingFilterVersion = 2
)

// Valid indicates whether the value is a known member of the CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingFilterVersion enum.
func (e CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingFilterVersion) Valid() bool {
	switch e {
	case CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingFilterVersionN2:
		return true
	default:
		return false
	}
}

// Defines values for CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingState.
const (
	CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingStateN0 CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingState = 0
	CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingStateN1 CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingState = 1
	CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingStateN2 CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingState = 2
	CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingStateN3 CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingState = 3
	CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingStateN4 CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingState = 4
)

// Valid indicates whether the value is a known member of the CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingState enum.
func (e CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingState) Valid() bool {
	switch e {
	case CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingStateN0:
		return true
	case CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingStateN1:
		return true
	case CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingStateN2:
		return true
	case CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingStateN3:
		return true
	case CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingStateN4:
		return true
	default:
		return false
	}
}

// Defines values for CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingType.
const (
	CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingTypeN1 CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingType = 1
	CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingTypeN2 CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingType = 2
	CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingTypeN3 CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingType = 3
)

// Valid indicates whether the value is a known member of the CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingType enum.
func (e CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingType) Valid() bool {
	switch e {
	case CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingTypeN1:
		return true
	case CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingTypeN2:
		return true
	case CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingTypeN3:
		return true
	default:
		return false
	}
}

// Defines values for CoreGetV4Event200JSONResponseBodyMailSettingsHideEmbeddedImages.
const (
	CoreGetV4Event200JSONResponseBodyMailSettingsHideEmbeddedImagesN0 CoreGetV4Event200JSONResponseBodyMailSettingsHideEmbeddedImages = 0
	CoreGetV4Event200JSONResponseBodyMailSettingsHideEmbeddedImagesN1 CoreGetV4Event200JSONResponseBodyMailSettingsHideEmbeddedImages = 1
)

// Valid indicates whether the value is a known member of the CoreGetV4Event200JSONResponseBodyMailSettingsHideEmbeddedImages enum.
func (e CoreGetV4Event200JSONResponseBodyMailSettingsHideEmbeddedImages) Valid() bool {
	switch e {
	case CoreGetV4Event200JSONResponseBodyMailSettingsHideEmbeddedImagesN0:
		return true
	case CoreGetV4Event200JSONResponseBodyMailSettingsHideEmbeddedImagesN1:
		return true
	default:
		return false
	}
}

// Defines values for CoreGetV4Event200JSONResponseBodyMailSettingsHideRemoteImages.
const (
	CoreGetV4Event200JSONResponseBodyMailSettingsHideRemoteImagesN0 CoreGetV4Event200JSONResponseBodyMailSettingsHideRemoteImages = 0
	CoreGetV4Event200JSONResponseBodyMailSettingsHideRemoteImagesN1 CoreGetV4Event200JSONResponseBodyMailSettingsHideRemoteImages = 1
)

// Valid indicates whether the value is a known member of the CoreGetV4Event200JSONResponseBodyMailSettingsHideRemoteImages enum.
func (e CoreGetV4Event200JSONResponseBodyMailSettingsHideRemoteImages) Valid() bool {
	switch e {
	case CoreGetV4Event200JSONResponseBodyMailSettingsHideRemoteImagesN0:
		return true
	case CoreGetV4Event200JSONResponseBodyMailSettingsHideRemoteImagesN1:
		return true
	default:
		return false
	}
}

// Defines values for CoreGetV4Event200JSONResponseBodyMailSettingsHideSenderImages.
const (
	CoreGetV4Event200JSONResponseBodyMailSettingsHideSenderImagesN0 CoreGetV4Event200JSONResponseBodyMailSettingsHideSenderImages = 0
	CoreGetV4Event200JSONResponseBodyMailSettingsHideSenderImagesN1 CoreGetV4Event200JSONResponseBodyMailSettingsHideSenderImages = 1
)

// Valid indicates whether the value is a known member of the CoreGetV4Event200JSONResponseBodyMailSettingsHideSenderImages enum.
func (e CoreGetV4Event200JSONResponseBodyMailSettingsHideSenderImages) Valid() bool {
	switch e {
	case CoreGetV4Event200JSONResponseBodyMailSettingsHideSenderImagesN0:
		return true
	case CoreGetV4Event200JSONResponseBodyMailSettingsHideSenderImagesN1:
		return true
	default:
		return false
	}
}

// Defines values for CoreGetV4Event200JSONResponseBodyMailSettingsNextMessageOnMove.
const (
	CoreGetV4Event200JSONResponseBodyMailSettingsNextMessageOnMoveN0 CoreGetV4Event200JSONResponseBodyMailSettingsNextMessageOnMove = 0
	CoreGetV4Event200JSONResponseBodyMailSettingsNextMessageOnMoveN1 CoreGetV4Event200JSONResponseBodyMailSettingsNextMessageOnMove = 1
	CoreGetV4Event200JSONResponseBodyMailSettingsNextMessageOnMoveN2 CoreGetV4Event200JSONResponseBodyMailSettingsNextMessageOnMove = 2
)

// Valid indicates whether the value is a known member of the CoreGetV4Event200JSONResponseBodyMailSettingsNextMessageOnMove enum.
func (e CoreGetV4Event200JSONResponseBodyMailSettingsNextMessageOnMove) Valid() bool {
	switch e {
	case CoreGetV4Event200JSONResponseBodyMailSettingsNextMessageOnMoveN0:
		return true
	case CoreGetV4Event200JSONResponseBodyMailSettingsNextMessageOnMoveN1:
		return true
	case CoreGetV4Event200JSONResponseBodyMailSettingsNextMessageOnMoveN2:
		return true
	default:
		return false
	}
}

// Defines values for CoreGetV4Event200JSONResponseBodyMore.
const (
	CoreGetV4Event200JSONResponseBodyMoreN0 CoreGetV4Event200JSONResponseBodyMore = 0
	CoreGetV4Event200JSONResponseBodyMoreN1 CoreGetV4Event200JSONResponseBodyMore = 1
)

// Valid indicates whether the value is a known member of the CoreGetV4Event200JSONResponseBodyMore enum.
func (e CoreGetV4Event200JSONResponseBodyMore) Valid() bool {
	switch e {
	case CoreGetV4Event200JSONResponseBodyMoreN0:
		return true
	case CoreGetV4Event200JSONResponseBodyMoreN1:
		return true
	default:
		return false
	}
}

// Defines values for CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingFilterVersion.
const (
	CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingFilterVersionN2 CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingFilterVersion = 2
)

// Valid indicates whether the value is a known member of the CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingFilterVersion enum.
func (e CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingFilterVersion) Valid() bool {
	switch e {
	case CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingFilterVersionN2:
		return true
	default:
		return false
	}
}

// Defines values for CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingState.
const (
	CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingStateN0 CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingState = 0
	CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingStateN1 CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingState = 1
	CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingStateN2 CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingState = 2
	CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingStateN3 CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingState = 3
	CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingStateN4 CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingState = 4
)

// Valid indicates whether the value is a known member of the CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingState enum.
func (e CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingState) Valid() bool {
	switch e {
	case CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingStateN0:
		return true
	case CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingStateN1:
		return true
	case CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingStateN2:
		return true
	case CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingStateN3:
		return true
	case CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingStateN4:
		return true
	default:
		return false
	}
}

// Defines values for CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingType.
const (
	CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingTypeN1 CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingType = 1
	CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingTypeN2 CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingType = 2
	CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingTypeN3 CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingType = 3
)

// Valid indicates whether the value is a known member of the CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingType enum.
func (e CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingType) Valid() bool {
	switch e {
	case CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingTypeN1:
		return true
	case CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingTypeN2:
		return true
	case CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingTypeN3:
		return true
	default:
		return false
	}
}

// Defines values for CoreGetV4Event200JSONResponseBodyUserSettingsAIAssistantFlags.
const (
	CoreGetV4Event200JSONResponseBodyUserSettingsAIAssistantFlagsN0 CoreGetV4Event200JSONResponseBodyUserSettingsAIAssistantFlags = 0
	CoreGetV4Event200JSONResponseBodyUserSettingsAIAssistantFlagsN1 CoreGetV4Event200JSONResponseBodyUserSettingsAIAssistantFlags = 1
	CoreGetV4Event200JSONResponseBodyUserSettingsAIAssistantFlagsN2 CoreGetV4Event200JSONResponseBodyUserSettingsAIAssistantFlags = 2
	CoreGetV4Event200JSONResponseBodyUserSettingsAIAssistantFlagsN3 CoreGetV4Event200JSONResponseBodyUserSettingsAIAssistantFlags = 3
)

// Valid indicates whether the value is a known member of the CoreGetV4Event200JSONResponseBodyUserSettingsAIAssistantFlags enum.
func (e CoreGetV4Event200JSONResponseBodyUserSettingsAIAssistantFlags) Valid() bool {
	switch e {
	case CoreGetV4Event200JSONResponseBodyUserSettingsAIAssistantFlagsN0:
		return true
	case CoreGetV4Event200JSONResponseBodyUserSettingsAIAssistantFlagsN1:
		return true
	case CoreGetV4Event200JSONResponseBodyUserSettingsAIAssistantFlagsN2:
		return true
	case CoreGetV4Event200JSONResponseBodyUserSettingsAIAssistantFlagsN3:
		return true
	default:
		return false
	}
}

// Defines values for CoreGetV4Event200JSONResponseBodyUserSettingsSessionAccountRecovery.
const (
	CoreGetV4Event200JSONResponseBodyUserSettingsSessionAccountRecoveryN0 CoreGetV4Event200JSONResponseBodyUserSettingsSessionAccountRecovery = 0
	CoreGetV4Event200JSONResponseBodyUserSettingsSessionAccountRecoveryN1 CoreGetV4Event200JSONResponseBodyUserSettingsSessionAccountRecovery = 1
)

// Valid indicates whether the value is a known member of the CoreGetV4Event200JSONResponseBodyUserSettingsSessionAccountRecovery enum.
func (e CoreGetV4Event200JSONResponseBodyUserSettingsSessionAccountRecovery) Valid() bool {
	switch e {
	case CoreGetV4Event200JSONResponseBodyUserSettingsSessionAccountRecoveryN0:
		return true
	case CoreGetV4Event200JSONResponseBodyUserSettingsSessionAccountRecoveryN1:
		return true
	default:
		return false
	}
}

// Defines values for CoreCreateV4MembersJSONBodyMaxAI.
const (
	CoreCreateV4MembersJSONBodyMaxAIN0 CoreCreateV4MembersJSONBodyMaxAI = 0
	CoreCreateV4MembersJSONBodyMaxAIN1 CoreCreateV4MembersJSONBodyMaxAI = 1
)

// Valid indicates whether the value is a known member of the CoreCreateV4MembersJSONBodyMaxAI enum.
func (e CoreCreateV4MembersJSONBodyMaxAI) Valid() bool {
	switch e {
	case CoreCreateV4MembersJSONBodyMaxAIN0:
		return true
	case CoreCreateV4MembersJSONBodyMaxAIN1:
		return true
	default:
		return false
	}
}

// Defines values for CoreCreateV4MembersJSONBodyMaxLumo.
const (
	CoreCreateV4MembersJSONBodyMaxLumoN0 CoreCreateV4MembersJSONBodyMaxLumo = 0
	CoreCreateV4MembersJSONBodyMaxLumoN1 CoreCreateV4MembersJSONBodyMaxLumo = 1
)

// Valid indicates whether the value is a known member of the CoreCreateV4MembersJSONBodyMaxLumo enum.
func (e CoreCreateV4MembersJSONBodyMaxLumo) Valid() bool {
	switch e {
	case CoreCreateV4MembersJSONBodyMaxLumoN0:
		return true
	case CoreCreateV4MembersJSONBodyMaxLumoN1:
		return true
	default:
		return false
	}
}

// Defines values for CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONBodyPermissions.
const (
	CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONBodyPermissionsN2 CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONBodyPermissions = 2
	CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONBodyPermissionsN8 CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONBodyPermissions = 8
)

// Valid indicates whether the value is a known member of the CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONBodyPermissions enum.
func (e CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONBodyPermissions) Valid() bool {
	switch e {
	case CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONBodyPermissionsN2:
		return true
	case CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONBodyPermissionsN8:
		return true
	default:
		return false
	}
}

// Defines values for CoreCreateV4MembersInvitationsJSONBodyMaxAI.
const (
	CoreCreateV4MembersInvitationsJSONBodyMaxAIN0 CoreCreateV4MembersInvitationsJSONBodyMaxAI = 0
	CoreCreateV4MembersInvitationsJSONBodyMaxAIN1 CoreCreateV4MembersInvitationsJSONBodyMaxAI = 1
)

// Valid indicates whether the value is a known member of the CoreCreateV4MembersInvitationsJSONBodyMaxAI enum.
func (e CoreCreateV4MembersInvitationsJSONBodyMaxAI) Valid() bool {
	switch e {
	case CoreCreateV4MembersInvitationsJSONBodyMaxAIN0:
		return true
	case CoreCreateV4MembersInvitationsJSONBodyMaxAIN1:
		return true
	default:
		return false
	}
}

// Defines values for CoreCreateV4MembersInvitationsJSONBodyMaxLumo.
const (
	CoreCreateV4MembersInvitationsJSONBodyMaxLumoN0 CoreCreateV4MembersInvitationsJSONBodyMaxLumo = 0
	CoreCreateV4MembersInvitationsJSONBodyMaxLumoN1 CoreCreateV4MembersInvitationsJSONBodyMaxLumo = 1
)

// Valid indicates whether the value is a known member of the CoreCreateV4MembersInvitationsJSONBodyMaxLumo enum.
func (e CoreCreateV4MembersInvitationsJSONBodyMaxLumo) Valid() bool {
	switch e {
	case CoreCreateV4MembersInvitationsJSONBodyMaxLumoN0:
		return true
	case CoreCreateV4MembersInvitationsJSONBodyMaxLumoN1:
		return true
	default:
		return false
	}
}

// Defines values for CoreUpdateV4MembersPermissionsJSONBodyAction.
const (
	CoreUpdateV4MembersPermissionsJSONBodyActionN0 CoreUpdateV4MembersPermissionsJSONBodyAction = 0
	CoreUpdateV4MembersPermissionsJSONBodyActionN1 CoreUpdateV4MembersPermissionsJSONBodyAction = 1
)

// Valid indicates whether the value is a known member of the CoreUpdateV4MembersPermissionsJSONBodyAction enum.
func (e CoreUpdateV4MembersPermissionsJSONBodyAction) Valid() bool {
	switch e {
	case CoreUpdateV4MembersPermissionsJSONBodyActionN0:
		return true
	case CoreUpdateV4MembersPermissionsJSONBodyActionN1:
		return true
	default:
		return false
	}
}

// Defines values for CoreUpdateV4MembersPermissionsJSONBodyPermission.
const (
	CoreUpdateV4MembersPermissionsJSONBodyPermissionN1 CoreUpdateV4MembersPermissionsJSONBodyPermission = 1
)

// Valid indicates whether the value is a known member of the CoreUpdateV4MembersPermissionsJSONBodyPermission enum.
func (e CoreUpdateV4MembersPermissionsJSONBodyPermission) Valid() bool {
	switch e {
	case CoreUpdateV4MembersPermissionsJSONBodyPermissionN1:
		return true
	default:
		return false
	}
}

// Defines values for CoreUpdateV4MembersAiJSONBodyMaxAI.
const (
	CoreUpdateV4MembersAiJSONBodyMaxAIN0 CoreUpdateV4MembersAiJSONBodyMaxAI = 0
	CoreUpdateV4MembersAiJSONBodyMaxAIN1 CoreUpdateV4MembersAiJSONBodyMaxAI = 1
)

// Valid indicates whether the value is a known member of the CoreUpdateV4MembersAiJSONBodyMaxAI enum.
func (e CoreUpdateV4MembersAiJSONBodyMaxAI) Valid() bool {
	switch e {
	case CoreUpdateV4MembersAiJSONBodyMaxAIN0:
		return true
	case CoreUpdateV4MembersAiJSONBodyMaxAIN1:
		return true
	default:
		return false
	}
}

// Defines values for CoreUpdateV4MembersLumoJSONBodyMaxLumo.
const (
	CoreUpdateV4MembersLumoJSONBodyMaxLumoN0 CoreUpdateV4MembersLumoJSONBodyMaxLumo = 0
	CoreUpdateV4MembersLumoJSONBodyMaxLumoN1 CoreUpdateV4MembersLumoJSONBodyMaxLumo = 1
)

// Valid indicates whether the value is a known member of the CoreUpdateV4MembersLumoJSONBodyMaxLumo enum.
func (e CoreUpdateV4MembersLumoJSONBodyMaxLumo) Valid() bool {
	switch e {
	case CoreUpdateV4MembersLumoJSONBodyMaxLumoN0:
		return true
	case CoreUpdateV4MembersLumoJSONBodyMaxLumoN1:
		return true
	default:
		return false
	}
}

// Defines values for DriveCreateUrlsAuth200JSONResponseBodySharePublicPermissions.
const (
	DriveCreateUrlsAuth200JSONResponseBodySharePublicPermissionsN4 DriveCreateUrlsAuth200JSONResponseBodySharePublicPermissions = 4
	DriveCreateUrlsAuth200JSONResponseBodySharePublicPermissionsN6 DriveCreateUrlsAuth200JSONResponseBodySharePublicPermissions = 6
)

// Valid indicates whether the value is a known member of the DriveCreateUrlsAuth200JSONResponseBodySharePublicPermissions enum.
func (e DriveCreateUrlsAuth200JSONResponseBodySharePublicPermissions) Valid() bool {
	switch e {
	case DriveCreateUrlsAuth200JSONResponseBodySharePublicPermissionsN4:
		return true
	case DriveCreateUrlsAuth200JSONResponseBodySharePublicPermissionsN6:
		return true
	default:
		return false
	}
}

// Defines values for DriveCreateUrlsBlocksJSONBodyThumbnailListType.
const (
	DriveCreateUrlsBlocksJSONBodyThumbnailListTypeN1 DriveCreateUrlsBlocksJSONBodyThumbnailListType = 1
	DriveCreateUrlsBlocksJSONBodyThumbnailListTypeN2 DriveCreateUrlsBlocksJSONBodyThumbnailListType = 2
	DriveCreateUrlsBlocksJSONBodyThumbnailListTypeN3 DriveCreateUrlsBlocksJSONBodyThumbnailListType = 3
)

// Valid indicates whether the value is a known member of the DriveCreateUrlsBlocksJSONBodyThumbnailListType enum.
func (e DriveCreateUrlsBlocksJSONBodyThumbnailListType) Valid() bool {
	switch e {
	case DriveCreateUrlsBlocksJSONBodyThumbnailListTypeN1:
		return true
	case DriveCreateUrlsBlocksJSONBodyThumbnailListTypeN2:
		return true
	case DriveCreateUrlsBlocksJSONBodyThumbnailListTypeN3:
		return true
	default:
		return false
	}
}

// Defines values for DriveCreateUrlsBlocks200JSONResponseBodyThumbnailLinkThumbnailType.
const (
	DriveCreateUrlsBlocks200JSONResponseBodyThumbnailLinkThumbnailTypeN1 DriveCreateUrlsBlocks200JSONResponseBodyThumbnailLinkThumbnailType = 1
	DriveCreateUrlsBlocks200JSONResponseBodyThumbnailLinkThumbnailTypeN2 DriveCreateUrlsBlocks200JSONResponseBodyThumbnailLinkThumbnailType = 2
	DriveCreateUrlsBlocks200JSONResponseBodyThumbnailLinkThumbnailTypeN3 DriveCreateUrlsBlocks200JSONResponseBodyThumbnailLinkThumbnailType = 3
)

// Valid indicates whether the value is a known member of the DriveCreateUrlsBlocks200JSONResponseBodyThumbnailLinkThumbnailType enum.
func (e DriveCreateUrlsBlocks200JSONResponseBodyThumbnailLinkThumbnailType) Valid() bool {
	switch e {
	case DriveCreateUrlsBlocks200JSONResponseBodyThumbnailLinkThumbnailTypeN1:
		return true
	case DriveCreateUrlsBlocks200JSONResponseBodyThumbnailLinkThumbnailTypeN2:
		return true
	case DriveCreateUrlsBlocks200JSONResponseBodyThumbnailLinkThumbnailTypeN3:
		return true
	default:
		return false
	}
}

// Defines values for DriveCreateUrlsBlocks200JSONResponseBodyThumbnailLinksThumbnailType.
const (
	DriveCreateUrlsBlocks200JSONResponseBodyThumbnailLinksThumbnailTypeN1 DriveCreateUrlsBlocks200JSONResponseBodyThumbnailLinksThumbnailType = 1
	DriveCreateUrlsBlocks200JSONResponseBodyThumbnailLinksThumbnailTypeN2 DriveCreateUrlsBlocks200JSONResponseBodyThumbnailLinksThumbnailType = 2
	DriveCreateUrlsBlocks200JSONResponseBodyThumbnailLinksThumbnailTypeN3 DriveCreateUrlsBlocks200JSONResponseBodyThumbnailLinksThumbnailType = 3
)

// Valid indicates whether the value is a known member of the DriveCreateUrlsBlocks200JSONResponseBodyThumbnailLinksThumbnailType enum.
func (e DriveCreateUrlsBlocks200JSONResponseBodyThumbnailLinksThumbnailType) Valid() bool {
	switch e {
	case DriveCreateUrlsBlocks200JSONResponseBodyThumbnailLinksThumbnailTypeN1:
		return true
	case DriveCreateUrlsBlocks200JSONResponseBodyThumbnailLinksThumbnailTypeN2:
		return true
	case DriveCreateUrlsBlocks200JSONResponseBodyThumbnailLinksThumbnailTypeN3:
		return true
	default:
		return false
	}
}

// Defines values for DriveGetUrlsFile200JSONResponseBodyRevisionState.
const (
	DriveGetUrlsFile200JSONResponseBodyRevisionStateN0 DriveGetUrlsFile200JSONResponseBodyRevisionState = 0
	DriveGetUrlsFile200JSONResponseBodyRevisionStateN1 DriveGetUrlsFile200JSONResponseBodyRevisionState = 1
	DriveGetUrlsFile200JSONResponseBodyRevisionStateN2 DriveGetUrlsFile200JSONResponseBodyRevisionState = 2
)

// Valid indicates whether the value is a known member of the DriveGetUrlsFile200JSONResponseBodyRevisionState enum.
func (e DriveGetUrlsFile200JSONResponseBodyRevisionState) Valid() bool {
	switch e {
	case DriveGetUrlsFile200JSONResponseBodyRevisionStateN0:
		return true
	case DriveGetUrlsFile200JSONResponseBodyRevisionStateN1:
		return true
	case DriveGetUrlsFile200JSONResponseBodyRevisionStateN2:
		return true
	default:
		return false
	}
}

// Defines values for DriveGetUrlsFile200JSONResponseBodyRevisionThumbnail.
const (
	DriveGetUrlsFile200JSONResponseBodyRevisionThumbnailN0 DriveGetUrlsFile200JSONResponseBodyRevisionThumbnail = 0
	DriveGetUrlsFile200JSONResponseBodyRevisionThumbnailN1 DriveGetUrlsFile200JSONResponseBodyRevisionThumbnail = 1
)

// Valid indicates whether the value is a known member of the DriveGetUrlsFile200JSONResponseBodyRevisionThumbnail enum.
func (e DriveGetUrlsFile200JSONResponseBodyRevisionThumbnail) Valid() bool {
	switch e {
	case DriveGetUrlsFile200JSONResponseBodyRevisionThumbnailN0:
		return true
	case DriveGetUrlsFile200JSONResponseBodyRevisionThumbnailN1:
		return true
	default:
		return false
	}
}

// Defines values for DriveGetUrlsFile200JSONResponseBodyRevisionThumbnailsType.
const (
	DriveGetUrlsFile200JSONResponseBodyRevisionThumbnailsTypeN1 DriveGetUrlsFile200JSONResponseBodyRevisionThumbnailsType = 1
	DriveGetUrlsFile200JSONResponseBodyRevisionThumbnailsTypeN2 DriveGetUrlsFile200JSONResponseBodyRevisionThumbnailsType = 2
	DriveGetUrlsFile200JSONResponseBodyRevisionThumbnailsTypeN3 DriveGetUrlsFile200JSONResponseBodyRevisionThumbnailsType = 3
)

// Valid indicates whether the value is a known member of the DriveGetUrlsFile200JSONResponseBodyRevisionThumbnailsType enum.
func (e DriveGetUrlsFile200JSONResponseBodyRevisionThumbnailsType) Valid() bool {
	switch e {
	case DriveGetUrlsFile200JSONResponseBodyRevisionThumbnailsTypeN1:
		return true
	case DriveGetUrlsFile200JSONResponseBodyRevisionThumbnailsTypeN2:
		return true
	case DriveGetUrlsFile200JSONResponseBodyRevisionThumbnailsTypeN3:
		return true
	default:
		return false
	}
}

// Defines values for DriveUpdateUrlsFilesRevisionJSONBodyPhotoTags.
const (
	DriveUpdateUrlsFilesRevisionJSONBodyPhotoTagsN0 DriveUpdateUrlsFilesRevisionJSONBodyPhotoTags = 0
	DriveUpdateUrlsFilesRevisionJSONBodyPhotoTagsN1 DriveUpdateUrlsFilesRevisionJSONBodyPhotoTags = 1
	DriveUpdateUrlsFilesRevisionJSONBodyPhotoTagsN2 DriveUpdateUrlsFilesRevisionJSONBodyPhotoTags = 2
	DriveUpdateUrlsFilesRevisionJSONBodyPhotoTagsN3 DriveUpdateUrlsFilesRevisionJSONBodyPhotoTags = 3
	DriveUpdateUrlsFilesRevisionJSONBodyPhotoTagsN4 DriveUpdateUrlsFilesRevisionJSONBodyPhotoTags = 4
	DriveUpdateUrlsFilesRevisionJSONBodyPhotoTagsN5 DriveUpdateUrlsFilesRevisionJSONBodyPhotoTags = 5
	DriveUpdateUrlsFilesRevisionJSONBodyPhotoTagsN6 DriveUpdateUrlsFilesRevisionJSONBodyPhotoTags = 6
	DriveUpdateUrlsFilesRevisionJSONBodyPhotoTagsN7 DriveUpdateUrlsFilesRevisionJSONBodyPhotoTags = 7
	DriveUpdateUrlsFilesRevisionJSONBodyPhotoTagsN8 DriveUpdateUrlsFilesRevisionJSONBodyPhotoTags = 8
	DriveUpdateUrlsFilesRevisionJSONBodyPhotoTagsN9 DriveUpdateUrlsFilesRevisionJSONBodyPhotoTags = 9
)

// Valid indicates whether the value is a known member of the DriveUpdateUrlsFilesRevisionJSONBodyPhotoTags enum.
func (e DriveUpdateUrlsFilesRevisionJSONBodyPhotoTags) Valid() bool {
	switch e {
	case DriveUpdateUrlsFilesRevisionJSONBodyPhotoTagsN0:
		return true
	case DriveUpdateUrlsFilesRevisionJSONBodyPhotoTagsN1:
		return true
	case DriveUpdateUrlsFilesRevisionJSONBodyPhotoTagsN2:
		return true
	case DriveUpdateUrlsFilesRevisionJSONBodyPhotoTagsN3:
		return true
	case DriveUpdateUrlsFilesRevisionJSONBodyPhotoTagsN4:
		return true
	case DriveUpdateUrlsFilesRevisionJSONBodyPhotoTagsN5:
		return true
	case DriveUpdateUrlsFilesRevisionJSONBodyPhotoTagsN6:
		return true
	case DriveUpdateUrlsFilesRevisionJSONBodyPhotoTagsN7:
		return true
	case DriveUpdateUrlsFilesRevisionJSONBodyPhotoTagsN8:
		return true
	case DriveUpdateUrlsFilesRevisionJSONBodyPhotoTagsN9:
		return true
	default:
		return false
	}
}

// Defines values for DriveListUrlsFoldersChildrenParamsThumbnails.
const (
	DriveListUrlsFoldersChildrenParamsThumbnailsN0 DriveListUrlsFoldersChildrenParamsThumbnails = 0
	DriveListUrlsFoldersChildrenParamsThumbnailsN1 DriveListUrlsFoldersChildrenParamsThumbnails = 1
)

// Valid indicates whether the value is a known member of the DriveListUrlsFoldersChildrenParamsThumbnails enum.
func (e DriveListUrlsFoldersChildrenParamsThumbnails) Valid() bool {
	switch e {
	case DriveListUrlsFoldersChildrenParamsThumbnailsN0:
		return true
	case DriveListUrlsFoldersChildrenParamsThumbnailsN1:
		return true
	default:
		return false
	}
}

// Defines values for DriveListUrlsFoldersChildrenParamsDesc.
const (
	DriveListUrlsFoldersChildrenParamsDescN0 DriveListUrlsFoldersChildrenParamsDesc = 0
	DriveListUrlsFoldersChildrenParamsDescN1 DriveListUrlsFoldersChildrenParamsDesc = 1
)

// Valid indicates whether the value is a known member of the DriveListUrlsFoldersChildrenParamsDesc enum.
func (e DriveListUrlsFoldersChildrenParamsDesc) Valid() bool {
	switch e {
	case DriveListUrlsFoldersChildrenParamsDescN0:
		return true
	case DriveListUrlsFoldersChildrenParamsDescN1:
		return true
	default:
		return false
	}
}

// Defines values for DriveListUrlsFoldersChildrenParamsShowAll.
const (
	DriveListUrlsFoldersChildrenParamsShowAllN0 DriveListUrlsFoldersChildrenParamsShowAll = 0
	DriveListUrlsFoldersChildrenParamsShowAllN1 DriveListUrlsFoldersChildrenParamsShowAll = 1
)

// Valid indicates whether the value is a known member of the DriveListUrlsFoldersChildrenParamsShowAll enum.
func (e DriveListUrlsFoldersChildrenParamsShowAll) Valid() bool {
	switch e {
	case DriveListUrlsFoldersChildrenParamsShowAllN0:
		return true
	case DriveListUrlsFoldersChildrenParamsShowAllN1:
		return true
	default:
		return false
	}
}

// Defines values for DriveListUrlsFoldersChildrenParamsFoldersOnly.
const (
	DriveListUrlsFoldersChildrenParamsFoldersOnlyN0 DriveListUrlsFoldersChildrenParamsFoldersOnly = 0
	DriveListUrlsFoldersChildrenParamsFoldersOnlyN1 DriveListUrlsFoldersChildrenParamsFoldersOnly = 1
)

// Valid indicates whether the value is a known member of the DriveListUrlsFoldersChildrenParamsFoldersOnly enum.
func (e DriveListUrlsFoldersChildrenParamsFoldersOnly) Valid() bool {
	switch e {
	case DriveListUrlsFoldersChildrenParamsFoldersOnlyN0:
		return true
	case DriveListUrlsFoldersChildrenParamsFoldersOnlyN1:
		return true
	default:
		return false
	}
}

// Defines values for DriveCreateUrlsFoldersDeleteMultiple200JSONResponseBodyResponseCode.
const (
	DriveCreateUrlsFoldersDeleteMultiple200JSONResponseBodyResponseCodeN1000 DriveCreateUrlsFoldersDeleteMultiple200JSONResponseBodyResponseCode = 1000
)

// Valid indicates whether the value is a known member of the DriveCreateUrlsFoldersDeleteMultiple200JSONResponseBodyResponseCode enum.
func (e DriveCreateUrlsFoldersDeleteMultiple200JSONResponseBodyResponseCode) Valid() bool {
	switch e {
	case DriveCreateUrlsFoldersDeleteMultiple200JSONResponseBodyResponseCodeN1000:
		return true
	default:
		return false
	}
}

// Defines values for DriveListUrlsInfo200JSONResponseBodyVendorType.
const (
	DriveListUrlsInfo200JSONResponseBodyVendorTypeN0 DriveListUrlsInfo200JSONResponseBodyVendorType = 0
	DriveListUrlsInfo200JSONResponseBodyVendorTypeN1 DriveListUrlsInfo200JSONResponseBodyVendorType = 1
	DriveListUrlsInfo200JSONResponseBodyVendorTypeN2 DriveListUrlsInfo200JSONResponseBodyVendorType = 2
)

// Valid indicates whether the value is a known member of the DriveListUrlsInfo200JSONResponseBodyVendorType enum.
func (e DriveListUrlsInfo200JSONResponseBodyVendorType) Valid() bool {
	switch e {
	case DriveListUrlsInfo200JSONResponseBodyVendorTypeN0:
		return true
	case DriveListUrlsInfo200JSONResponseBodyVendorTypeN1:
		return true
	case DriveListUrlsInfo200JSONResponseBodyVendorTypeN2:
		return true
	default:
		return false
	}
}

// Defines values for DriveCreateV2UrlsBookmark200JSONResponseBodyBookmarkShareURLState.
const (
	DriveCreateV2UrlsBookmark200JSONResponseBodyBookmarkShareURLStateN1 DriveCreateV2UrlsBookmark200JSONResponseBodyBookmarkShareURLState = 1
	DriveCreateV2UrlsBookmark200JSONResponseBodyBookmarkShareURLStateN3 DriveCreateV2UrlsBookmark200JSONResponseBodyBookmarkShareURLState = 3
)

// Valid indicates whether the value is a known member of the DriveCreateV2UrlsBookmark200JSONResponseBodyBookmarkShareURLState enum.
func (e DriveCreateV2UrlsBookmark200JSONResponseBodyBookmarkShareURLState) Valid() bool {
	switch e {
	case DriveCreateV2UrlsBookmark200JSONResponseBodyBookmarkShareURLStateN1:
		return true
	case DriveCreateV2UrlsBookmark200JSONResponseBodyBookmarkShareURLStateN3:
		return true
	default:
		return false
	}
}

// AuthDeleteV4Params defines parameters for AuthDeleteV4.
type AuthDeleteV4Params struct {
	AuthDevice *int `form:"AuthDevice,omitempty" json:"AuthDevice,omitempty"`
}

// CalendarListV1Params defines parameters for CalendarListV1.
type CalendarListV1Params struct {
	OrderBy *string `form:"OrderBy,omitempty" json:"OrderBy,omitempty"`
}

// CalendarGetV1BookingExternalParams defines parameters for CalendarGetV1BookingExternal.
type CalendarGetV1BookingExternalParams struct {
	Start     *string `form:"Start,omitempty" json:"Start,omitempty"`
	StartTime *string `form:"startTime,omitempty" json:"startTime,omitempty"`
	End       *string `form:"End,omitempty" json:"End,omitempty"`
	EndTime   *string `form:"endTime,omitempty" json:"endTime,omitempty"`
}

// CalendarListV1BookingExternalNextSlotParams defines parameters for CalendarListV1BookingExternalNextSlot.
type CalendarListV1BookingExternalNextSlotParams struct {
	StartTime *string `form:"StartTime,omitempty" json:"StartTime,omitempty"`
}

// CalendarUpdateV1EventsAcceptJSONBody defines parameters for CalendarUpdateV1EventsAccept.
type CalendarUpdateV1EventsAcceptJSONBody struct {
	Signature *string `json:"Signature,omitempty"`
}

// CalendarCreateV1KeysResetJSONBody defines parameters for CalendarCreateV1KeysReset.
type CalendarCreateV1KeysResetJSONBody struct {
	CalendarKeys *string `json:"CalendarKeys,omitempty"`
}

// CalendarCreateV1SubscriptionValidateJSONBody defines parameters for CalendarCreateV1SubscriptionValidate.
type CalendarCreateV1SubscriptionValidateJSONBody struct {
	URL *string `json:"URL,omitempty"`
}

// CalendarCreateV1VideoconferencesJSONBody defines parameters for CalendarCreateV1Videoconferences.
type CalendarCreateV1VideoconferencesJSONBody struct {
	Provider *string `json:"Provider,omitempty"`
}

// CalendarUpdateV1InvitationsAcceptJSONBody defines parameters for CalendarUpdateV1InvitationsAccept.
type CalendarUpdateV1InvitationsAcceptJSONBody struct {
	Signature *string `json:"Signature,omitempty"`
}

// CalendarCreateV1InvitationsJoinJSONBody defines parameters for CalendarCreateV1InvitationsJoin.
type CalendarCreateV1InvitationsJoinJSONBody struct {
	Color                       *string `json:"Color,omitempty"`
	DefaultFullDayNotifications *string `json:"DefaultFullDayNotifications,omitempty"`
	PassphraseKeyPacket         *string `json:"PassphraseKeyPacket,omitempty"`
	Signature                   *string `json:"Signature,omitempty"`
}

// CalendarUpdateV1KeyJSONBody defines parameters for CalendarUpdateV1Key.
type CalendarUpdateV1KeyJSONBody struct {
	PrivateKey *string `json:"PrivateKey,omitempty"`
}

// CalendarCreateV1MembersJSONBody defines parameters for CalendarCreateV1Members.
type CalendarCreateV1MembersJSONBody struct {
	AddressID *string `json:"AddressID,omitempty"`
	Members   *string `json:"Members,omitempty"`
	Signature *string `json:"Signature,omitempty"`
}

// CalendarUpdateV1UrlJSONBody defines parameters for CalendarUpdateV1Url.
type CalendarUpdateV1UrlJSONBody struct {
	EncryptedPurpose *string `json:"EncryptedPurpose,omitempty"`
}

// CoreGetV4EventParams defines parameters for CoreGetV4Event.
type CoreGetV4EventParams struct {
	MessageCounts      *bool `form:"MessageCounts,omitempty" json:"MessageCounts,omitempty"`
	ConversationCounts *bool `form:"ConversationCounts,omitempty" json:"ConversationCounts,omitempty"`
}

// CoreGetV4Event200JSONResponseBodyCode defines parameters for CoreGetV4Event.
type CoreGetV4Event200JSONResponseBodyCode int

// CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingFilterVersion defines parameters for CoreGetV4Event.
type CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingFilterVersion int

// CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingState defines parameters for CoreGetV4Event.
type CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingState int

// CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingType defines parameters for CoreGetV4Event.
type CoreGetV4Event200JSONResponseBodyIncomingAddressForwardingType int

// CoreGetV4Event200JSONResponseBodyMailSettingsHideEmbeddedImages defines parameters for CoreGetV4Event.
type CoreGetV4Event200JSONResponseBodyMailSettingsHideEmbeddedImages int

// CoreGetV4Event200JSONResponseBodyMailSettingsHideRemoteImages defines parameters for CoreGetV4Event.
type CoreGetV4Event200JSONResponseBodyMailSettingsHideRemoteImages int

// CoreGetV4Event200JSONResponseBodyMailSettingsHideSenderImages defines parameters for CoreGetV4Event.
type CoreGetV4Event200JSONResponseBodyMailSettingsHideSenderImages int

// CoreGetV4Event200JSONResponseBodyMailSettingsNextMessageOnMove defines parameters for CoreGetV4Event.
type CoreGetV4Event200JSONResponseBodyMailSettingsNextMessageOnMove int

// CoreGetV4Event200JSONResponseBodyMore defines parameters for CoreGetV4Event.
type CoreGetV4Event200JSONResponseBodyMore int

// CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingFilterVersion defines parameters for CoreGetV4Event.
type CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingFilterVersion int

// CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingState defines parameters for CoreGetV4Event.
type CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingState int

// CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingType defines parameters for CoreGetV4Event.
type CoreGetV4Event200JSONResponseBodyOutgoingAddressForwardingType int

// CoreGetV4Event200JSONResponseBodyUserSettingsAIAssistantFlags defines parameters for CoreGetV4Event.
type CoreGetV4Event200JSONResponseBodyUserSettingsAIAssistantFlags int

// CoreGetV4Event200JSONResponseBodyUserSettingsSessionAccountRecovery defines parameters for CoreGetV4Event.
type CoreGetV4Event200JSONResponseBodyUserSettingsSessionAccountRecovery int

// CoreListV4KeysParams defines parameters for CoreListV4Keys.
type CoreListV4KeysParams struct {
	Email       *string `form:"Email,omitempty" json:"Email,omitempty"`
	Fingerprint *string `form:"Fingerprint,omitempty" json:"Fingerprint,omitempty"`
}

// CoreCreateV4KeysJSONBody defines parameters for CoreCreateV4Keys.
type CoreCreateV4KeysJSONBody struct {
	AddressForwardingID *string  `json:"AddressForwardingID,omitempty"`
	AddressID           *string  `json:"AddressID,omitempty"`
	GroupMemberID       *string  `json:"GroupMemberID,omitempty"`
	OrgSignature        *string  `json:"OrgSignature,omitempty"`
	OrgToken            *string  `json:"OrgToken,omitempty"`
	Primary             *float32 `json:"Primary,omitempty"`
	PrivateKey          *string  `json:"PrivateKey,omitempty"`
	Signature           *string  `json:"Signature,omitempty"`
	SignedKeyList       *struct {
		Data      *string `json:"Data,omitempty"`
		Signature *string `json:"Signature,omitempty"`
	} `json:"SignedKeyList,omitempty"`
	Token *string `json:"Token,omitempty"`
}

// CoreCreateV4KeysAddressDeleteJSONBody defines parameters for CoreCreateV4KeysAddressDelete.
type CoreCreateV4KeysAddressDeleteJSONBody struct {
	SignedKeyList *struct {
		Data      *string `json:"Data,omitempty"`
		Signature *string `json:"Signature,omitempty"`
	} `json:"SignedKeyList,omitempty"`
}

// CoreListV4KeysAllParams defines parameters for CoreListV4KeysAll.
type CoreListV4KeysAllParams struct {
	Email        *string `form:"Email,omitempty" json:"Email,omitempty"`
	InternalOnly *string `form:"InternalOnly,omitempty" json:"InternalOnly,omitempty"`
}

// CoreCreateV4KeysMigrateJSONBody defines parameters for CoreCreateV4KeysMigrate.
type CoreCreateV4KeysMigrateJSONBody struct {
	ID             *string `json:"ID,omitempty"`
	PrivateKey     *string `json:"PrivateKey,omitempty"`
	Signature      *string `json:"Signature,omitempty"`
	SignedKeyLists *struct {
		Data      *string `json:"Data,omitempty"`
		Signature *string `json:"Signature,omitempty"`
	} `json:"SignedKeyLists,omitempty"`
	Token *string `json:"Token,omitempty"`
}

// CoreUpdateV4KeysPrivateJSONBody defines parameters for CoreUpdateV4KeysPrivate.
type CoreUpdateV4KeysPrivateJSONBody struct {
	Auth *struct {
		ModulusID *string  `json:"ModulusID,omitempty"`
		Salt      *string  `json:"Salt,omitempty"`
		Verifier  *string  `json:"Verifier,omitempty"`
		Version   *float32 `json:"Version,omitempty"`
	} `json:"Auth,omitempty"`
	ClientEphemeral *string `json:"ClientEphemeral,omitempty"`
	ClientProof     *string `json:"ClientProof,omitempty"`
	EncryptedSecret *string `json:"EncryptedSecret,omitempty"`

	// FIDO2 Optional, for inline re-authentication, either this or the TwoFactorCode
	FIDO2           *string `json:"FIDO2,omitempty"`
	ID              *string `json:"ID,omitempty"`
	KeySalt         *string `json:"KeySalt,omitempty"`
	OrganizationKey *string `json:"OrganizationKey,omitempty"`
	PrivateKey      *string `json:"PrivateKey,omitempty"`
	SRPSession      *string `json:"SRPSession,omitempty"`
	TwoFactorCode   *string `json:"TwoFactorCode,omitempty"`
}

// CoreCreateV4KeysResetJSONBody defines parameters for CoreCreateV4KeysReset.
type CoreCreateV4KeysResetJSONBody struct {
	AddressID   *string `json:"AddressID,omitempty"`
	AddressList *struct {
		Data      *string `json:"Data,omitempty"`
		Signature *string `json:"Signature,omitempty"`
	} `json:"AddressList,omitempty"`

	// Auth Include to enable 1 password mode, otherwise 2 password mode
	Auth               *string `json:"Auth,omitempty"`
	KeySalt            *string `json:"KeySalt,omitempty"`
	OrgActivationToken *string `json:"OrgActivationToken,omitempty"`
	OrgPrimaryUserKey  *string `json:"OrgPrimaryUserKey,omitempty"`
	PrimaryKey         *string `json:"PrimaryKey,omitempty"`
	PrivateKey         *string `json:"PrivateKey,omitempty"`
	Signature          *string `json:"Signature,omitempty"`

	// SignedKeyList In the signed key list there is only the new keys
	SignedKeyList *string `json:"SignedKeyList,omitempty"`
	Token         *string `json:"Token,omitempty"`
	Username      *string `json:"Username,omitempty"`
}

// CoreCreateV4KeysSetupJSONBody defines parameters for CoreCreateV4KeysSetup.
type CoreCreateV4KeysSetupJSONBody struct {
	AddressKeys *struct {
		AddressID     *string `json:"AddressID,omitempty"`
		PrivateKey    *string `json:"PrivateKey,omitempty"`
		Revision      *string `json:"Revision,omitempty"`
		Signature     *string `json:"Signature,omitempty"`
		SignedKeyList *struct {
			Data      *string `json:"Data,omitempty"`
			Signature *string `json:"Signature,omitempty"`
		} `json:"SignedKeyList,omitempty"`
		Token *string `json:"Token,omitempty"`
	} `json:"AddressKeys,omitempty"`
	AddressList *struct {
		Data      *string `json:"Data,omitempty"`
		Signature *string `json:"Signature,omitempty"`
	} `json:"AddressList,omitempty"`

	// Auth include to enable 1 password mode, otherwise 2 password mode
	Auth               *string `json:"Auth,omitempty"`
	EncryptedSecret    *string `json:"EncryptedSecret,omitempty"`
	KeySalt            *string `json:"KeySalt,omitempty"`
	OrgActivationToken *string `json:"OrgActivationToken,omitempty"`
	OrgPrimaryUserKey  *string `json:"OrgPrimaryUserKey,omitempty"`
	PrimaryKey         *string `json:"PrimaryKey,omitempty"`
}

// CoreCreateV4KeysSetupParams defines parameters for CoreCreateV4KeysSetup.
type CoreCreateV4KeysSetupParams struct {
	AsyncUserInitialization *float32 `form:"AsyncUserInitialization,omitempty" json:"AsyncUserInitialization,omitempty"`
}

// CoreListV4KeysSignedkeylistParams defines parameters for CoreListV4KeysSignedkeylist.
type CoreListV4KeysSignedkeylistParams struct {
	Email      *string  `form:"Email,omitempty" json:"Email,omitempty"`
	Identifier *string  `form:"Identifier,omitempty" json:"Identifier,omitempty"`
	Revision   *float32 `form:"Revision,omitempty" json:"Revision,omitempty"`
}

// CoreListV4KeysSignedkeylistsParams defines parameters for CoreListV4KeysSignedkeylists.
type CoreListV4KeysSignedkeylistsParams struct {
	Email         *string  `form:"Email,omitempty" json:"Email,omitempty"`
	Identifier    *string  `form:"Identifier,omitempty" json:"Identifier,omitempty"`
	AfterEpochID  *float32 `form:"AfterEpochID,omitempty" json:"AfterEpochID,omitempty"`
	AfterRevision *float32 `form:"AfterRevision,omitempty" json:"AfterRevision,omitempty"`
}

// CoreUpdateV4KeysTokensJSONBody defines parameters for CoreUpdateV4KeysTokens.
type CoreUpdateV4KeysTokensJSONBody struct {
	// AddressKeyTokens List of address key tokens encrypted to the primary user key
	AddressKeyTokens *string `json:"AddressKeyTokens,omitempty"`
}

// CoreCreateV4KeysUserJSONBody defines parameters for CoreCreateV4KeysUser.
type CoreCreateV4KeysUserJSONBody struct {
	Primary    *string `json:"Primary,omitempty"`
	PrivateKey *string `json:"PrivateKey,omitempty"`
}

// CoreUpdateV4KeysUserJSONBody defines parameters for CoreUpdateV4KeysUser.
type CoreUpdateV4KeysUserJSONBody struct {
	AddressKeyFingerprints *[]string `json:"AddressKeyFingerprints,omitempty"`
	PrivateKey             *string   `json:"PrivateKey,omitempty"`
	SignedKeyLists         *struct {
		Data      *string `json:"Data,omitempty"`
		Signature *string `json:"Signature,omitempty"`
	} `json:"SignedKeyLists,omitempty"`
}

// CoreUpdateV4KeyJSONBody defines parameters for CoreUpdateV4Key.
type CoreUpdateV4KeyJSONBody struct {
	PrivateKey    *string `json:"PrivateKey,omitempty"`
	SignedKeyList *struct {
		Data      *string `json:"Data,omitempty"`
		Signature *string `json:"Signature,omitempty"`
	} `json:"SignedKeyList,omitempty"`
}

// CoreUpdateV4KeysActivateJSONBody defines parameters for CoreUpdateV4KeysActivate.
type CoreUpdateV4KeysActivateJSONBody struct {
	PrivateKey    *string `json:"PrivateKey,omitempty"`
	SignedKeyList *struct {
		Data      *string `json:"Data,omitempty"`
		Signature *string `json:"Signature,omitempty"`
	} `json:"SignedKeyList,omitempty"`
}

// CoreUpdateV4KeysDeleteJSONBody defines parameters for CoreUpdateV4KeysDelete.
type CoreUpdateV4KeysDeleteJSONBody struct {
	SignedKeyList *struct {
		Data      *string `json:"Data,omitempty"`
		Signature *string `json:"Signature,omitempty"`
	} `json:"SignedKeyList,omitempty"`
}

// CoreUpdateV4KeysFlagsJSONBody defines parameters for CoreUpdateV4KeysFlags.
type CoreUpdateV4KeysFlagsJSONBody struct {
	Flags         *float32 `json:"Flags,omitempty"`
	SignedKeyList *struct {
		Data      *string `json:"Data,omitempty"`
		Signature *string `json:"Signature,omitempty"`
	} `json:"SignedKeyList,omitempty"`
}

// CoreUpdateV4KeysPrimaryJSONBody defines parameters for CoreUpdateV4KeysPrimary.
type CoreUpdateV4KeysPrimaryJSONBody struct {
	// Primary Whether the key should be made primary or non-primary
	Primary       *string `json:"Primary,omitempty"`
	SignedKeyList *struct {
		Data      *string `json:"Data,omitempty"`
		Signature *string `json:"Signature,omitempty"`
	} `json:"SignedKeyList,omitempty"`
}

// CoreListV4MembersParams defines parameters for CoreListV4Members.
type CoreListV4MembersParams struct {
	N1               *string `form:"1,omitempty" json:"1,omitempty"`
	IncludeAddresses *string `form:"IncludeAddresses,omitempty" json:"IncludeAddresses,omitempty"`
}

// CoreCreateV4MembersJSONBody defines parameters for CoreCreateV4Members.
type CoreCreateV4MembersJSONBody struct {
	Auth *string `json:"Auth,omitempty"`

	// Invitation Invitation object if created using magic link
	Invitation        *string                             `json:"Invitation,omitempty"`
	MaxAI             *CoreCreateV4MembersJSONBodyMaxAI   `json:"MaxAI,omitempty"`
	MaxLumo           *CoreCreateV4MembersJSONBodyMaxLumo `json:"MaxLumo,omitempty"`
	MaxSpace          *float32                            `json:"MaxSpace,omitempty"`
	MaxVPN            *float32                            `json:"MaxVPN,omitempty"`
	Name              *string                             `json:"Name,omitempty"`
	Private           *float32                            `json:"Private,omitempty"`
	TemporaryPassword *bool                               `json:"TemporaryPassword,omitempty"`

	// Type Either 1=PROTON or 2=MANAGED (default)
	Type     *string `json:"Type,omitempty"`
	Username *string `json:"Username,omitempty"`
}

// CoreCreateV4MembersJSONBodyMaxAI defines parameters for CoreCreateV4Members.
type CoreCreateV4MembersJSONBodyMaxAI int

// CoreCreateV4MembersJSONBodyMaxLumo defines parameters for CoreCreateV4Members.
type CoreCreateV4MembersJSONBodyMaxLumo int

// CoreCreateV4MembersAddressesAvailableJSONBody defines parameters for CoreCreateV4MembersAddressesAvailable.
type CoreCreateV4MembersAddressesAvailableJSONBody struct {
	AddressList *struct {
		Data      *string `json:"Data,omitempty"`
		Signature *string `json:"Signature,omitempty"`
	} `json:"AddressList,omitempty"`
	DisplayName       *string  `json:"DisplayName,omitempty"`
	Domain            *string  `json:"Domain,omitempty"`
	Local             *string  `json:"Local,omitempty"`
	MemberID          *string  `json:"MemberID,omitempty"`
	RequesterMemberId *float32 `json:"RequesterMemberId,omitempty"`
	Signature         *string  `json:"Signature,omitempty"`
}

// CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONBody defines parameters for CoreUpdateV4MembersAddressesPermissionsOrganizationSwitch.
type CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONBody struct {
	// IDs List of encrypted addressIDs
	IDs *[]string `json:"IDs,omitempty"`

	// Permissions Permissions bit to apply
	Permissions *[]CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONBodyPermissions `json:"Permissions,omitempty"`
}

// CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONBodyPermissions defines parameters for CoreUpdateV4MembersAddressesPermissionsOrganizationSwitch.
type CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONBodyPermissions int

// CoreCreateV4MembersInvitationsJSONBody defines parameters for CoreCreateV4MembersInvitations.
type CoreCreateV4MembersInvitationsJSONBody struct {
	Email    *string                                        `json:"Email,omitempty"`
	MaxAI    *CoreCreateV4MembersInvitationsJSONBodyMaxAI   `json:"MaxAI,omitempty"`
	MaxLumo  *CoreCreateV4MembersInvitationsJSONBodyMaxLumo `json:"MaxLumo,omitempty"`
	MaxSpace *float32                                       `json:"MaxSpace,omitempty"`
}

// CoreCreateV4MembersInvitationsJSONBodyMaxAI defines parameters for CoreCreateV4MembersInvitations.
type CoreCreateV4MembersInvitationsJSONBodyMaxAI int

// CoreCreateV4MembersInvitationsJSONBodyMaxLumo defines parameters for CoreCreateV4MembersInvitations.
type CoreCreateV4MembersInvitationsJSONBodyMaxLumo int

// CoreUpdateV4MembersInvitationJSONBody defines parameters for CoreUpdateV4MembersInvitation.
type CoreUpdateV4MembersInvitationJSONBody struct {
	MaxSpace *float32 `json:"MaxSpace,omitempty"`
}

// CoreCreateV4MembersMeUnprivatizeJSONBody defines parameters for CoreCreateV4MembersMeUnprivatize.
type CoreCreateV4MembersMeUnprivatizeJSONBody struct {
	// OrgActivationToken A 32-byte random token encoded as hex and encrypted to the organization key, signed with newly created address key. Context should be set to account.key-token.user-unprivatization
	OrgActivationToken *string `json:"OrgActivationToken,omitempty"`

	// OrgUserKeys The user keys encrypted to the token contained in OrgActivationToken
	OrgUserKeys *string `json:"OrgUserKeys,omitempty"`
}

// CoreUpdateV4MembersPermissionsJSONBody defines parameters for CoreUpdateV4MembersPermissions.
type CoreUpdateV4MembersPermissionsJSONBody struct {
	Action *CoreUpdateV4MembersPermissionsJSONBodyAction `json:"Action,omitempty"`

	// Ids List of MemberIds
	Ids        *[]string                                         `json:"Ids,omitempty"`
	Permission *CoreUpdateV4MembersPermissionsJSONBodyPermission `json:"Permission,omitempty"`
}

// CoreUpdateV4MembersPermissionsJSONBodyAction defines parameters for CoreUpdateV4MembersPermissions.
type CoreUpdateV4MembersPermissionsJSONBodyAction int

// CoreUpdateV4MembersPermissionsJSONBodyPermission defines parameters for CoreUpdateV4MembersPermissions.
type CoreUpdateV4MembersPermissionsJSONBodyPermission int

// CoreListV4MembersSearchParams defines parameters for CoreListV4MembersSearch.
type CoreListV4MembersSearchParams struct {
	Limit    *float32 `form:"Limit,omitempty" json:"Limit,omitempty"`
	Q        *string  `form:"Q,omitempty" json:"Q,omitempty"`
	Keywords *string  `form:"keywords,omitempty" json:"keywords,omitempty"`
}

// CoreListV4MembersSearchSummaryParams defines parameters for CoreListV4MembersSearchSummary.
type CoreListV4MembersSearchSummaryParams struct {
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// CoreGetV4MemberParams defines parameters for CoreGetV4Member.
type CoreGetV4MemberParams struct {
	IncludeAddresses *float32 `form:"IncludeAddresses,omitempty" json:"IncludeAddresses,omitempty"`
}

// CoreListV4MembersAddressesParams defines parameters for CoreListV4MembersAddresses.
type CoreListV4MembersAddressesParams struct {
	Page     *float32 `form:"Page,omitempty" json:"Page,omitempty"`
	PageSize *float32 `form:"PageSize,omitempty" json:"PageSize,omitempty"`
}

// CoreCreateV4MembersAddressesJSONBody defines parameters for CoreCreateV4MembersAddresses.
type CoreCreateV4MembersAddressesJSONBody struct {
	AddressList *struct {
		Data      *string `json:"Data,omitempty"`
		Signature *string `json:"Signature,omitempty"`
	} `json:"AddressList,omitempty"`
	DisplayName       *string  `json:"DisplayName,omitempty"`
	Domain            *string  `json:"Domain,omitempty"`
	Local             *string  `json:"Local,omitempty"`
	MemberID          *string  `json:"MemberID,omitempty"`
	RequesterMemberId *float32 `json:"RequesterMemberId,omitempty"`
	Signature         *string  `json:"Signature,omitempty"`
}

// CoreUpdateV4MembersAddressesOrderJSONBody defines parameters for CoreUpdateV4MembersAddressesOrder.
type CoreUpdateV4MembersAddressesOrderJSONBody struct {
	// AddressIDs Will amend the order of addresses with the order of the corresponding AddressIDs
	AddressIDs *[]string `json:"AddressIDs,omitempty"`
}

// CoreUpdateV4MembersAiJSONBody defines parameters for CoreUpdateV4MembersAi.
type CoreUpdateV4MembersAiJSONBody struct {
	MaxAI *CoreUpdateV4MembersAiJSONBodyMaxAI `json:"MaxAI,omitempty"`
}

// CoreUpdateV4MembersAiJSONBodyMaxAI defines parameters for CoreUpdateV4MembersAi.
type CoreUpdateV4MembersAiJSONBodyMaxAI int

// CoreListV4MembersAuthlogParams defines parameters for CoreListV4MembersAuthlog.
type CoreListV4MembersAuthlogParams struct {
	Page     *string `form:"Page,omitempty" json:"Page,omitempty"`
	PageSize *string `form:"PageSize,omitempty" json:"PageSize,omitempty"`
}

// CoreCreateV4MembersDevicesResetJSONBody defines parameters for CoreCreateV4MembersDevicesReset.
type CoreCreateV4MembersDevicesResetJSONBody struct {
	// AuthDeviceID The member's device making the request
	AuthDeviceID *string `json:"AuthDeviceID,omitempty"`

	// EncryptedSecret base64 encoded AES-GCM encrypted to a random secret
	EncryptedSecret *string `json:"EncryptedSecret,omitempty"`

	// UserKeys List of re-encrypted user keys secret to random generated secret (32 bytes, then hex encoded)
	UserKeys *string `json:"UserKeys,omitempty"`
}

// CoreCreateV4MembersKeysJSONBody defines parameters for CoreCreateV4MembersKeys.
type CoreCreateV4MembersKeysJSONBody struct {
	AddressID    *string  `json:"AddressID,omitempty"`
	OrgSignature *string  `json:"OrgSignature,omitempty"`
	Primary      *float32 `json:"Primary,omitempty"`
	PrivateKey   *string  `json:"PrivateKey,omitempty"`
	Signature    *string  `json:"Signature,omitempty"`
	Token        *string  `json:"Token,omitempty"`
}

// CoreCreateV4MembersKeysSetupJSONBody defines parameters for CoreCreateV4MembersKeysSetup.
type CoreCreateV4MembersKeysSetupJSONBody struct {
	AddressID   *string `json:"AddressID,omitempty"`
	AddressList *struct {
		Data      *string `json:"Data,omitempty"`
		Signature *string `json:"Signature,omitempty"`
	} `json:"AddressList,omitempty"`

	// Auth Null when the member cannot login via password
	Auth         *string `json:"Auth,omitempty"`
	KeySalt      *string `json:"KeySalt,omitempty"`
	OrgSignature *string `json:"OrgSignature,omitempty"`
	PrivateKey   *string `json:"PrivateKey,omitempty"`
	Signature    *string `json:"Signature,omitempty"`
	Token        *string `json:"Token,omitempty"`
	UserKey      *struct {
		OrgPrivateKey *string `json:"OrgPrivateKey,omitempty"`
		OrgToken      *string `json:"OrgToken,omitempty"`
		PrivateKey    *string `json:"PrivateKey,omitempty"`
	} `json:"UserKey,omitempty"`
}

// CoreCreateV4MembersKeysUnprivatizeJSONBody defines parameters for CoreCreateV4MembersKeysUnprivatize.
type CoreCreateV4MembersKeysUnprivatizeJSONBody struct {
	// AddressKeys A token and signature for each address key to access them via the org key
	AddressKeys               *string `json:"AddressKeys,omitempty"`
	OrganizationKeyActivation *struct {
		// Signature Signature of the token key packet by the user key of the member
		Signature *string `json:"Signature,omitempty"`

		// TokenKeyPacket Token key packet encrypted to the user key of the member
		TokenKeyPacket *string `json:"TokenKeyPacket,omitempty"`
	} `json:"OrganizationKeyActivation,omitempty"`
	UserKey *struct {
		OrgPrivateKey *string `json:"OrgPrivateKey,omitempty"`
		OrgToken      *string `json:"OrgToken,omitempty"`
	} `json:"UserKey,omitempty"`

	// UserKeys All active member's user keys, with a signed and encrypted token to access them via the org key
	UserKeys *string `json:"UserKeys,omitempty"`
}

// CoreUpdateV4MembersLumoJSONBody defines parameters for CoreUpdateV4MembersLumo.
type CoreUpdateV4MembersLumoJSONBody struct {
	MaxLumo *CoreUpdateV4MembersLumoJSONBodyMaxLumo `json:"MaxLumo,omitempty"`
}

// CoreUpdateV4MembersLumoJSONBodyMaxLumo defines parameters for CoreUpdateV4MembersLumo.
type CoreUpdateV4MembersLumoJSONBodyMaxLumo int

// CoreUpdateV4MembersRoleJSONBody defines parameters for CoreUpdateV4MembersRole.
type CoreUpdateV4MembersRoleJSONBody struct {
	OrganizationKeyActivation *struct {
		// Signature Signature of the token key packet by the user key of the member
		Signature *string `json:"Signature,omitempty"`

		// TokenKeyPacket Token key packet encrypted to the user key of the member
		TokenKeyPacket *string `json:"TokenKeyPacket,omitempty"`
	} `json:"OrganizationKeyActivation,omitempty"`
	OrganizationKeyInvitation *struct {
		// EncryptionAddressID The address ID of the address to which the token key packet is encrypted to
		EncryptionAddressID *string `json:"EncryptionAddressID,omitempty"`

		// Signature Signature of the token key packet by the inviters address key
		Signature *string `json:"Signature,omitempty"`

		// SignatureAddressID The address ID of the signature address key
		SignatureAddressID *string `json:"SignatureAddressID,omitempty"`

		// TokenKeyPacket Token key packet encrypted to the recipient's address key
		TokenKeyPacket *string `json:"TokenKeyPacket,omitempty"`
	} `json:"OrganizationKeyInvitation,omitempty"`
	Role *float32 `json:"Role,omitempty"`
}

// CoreCreateV4MembersUnprivatizeJSONBody defines parameters for CoreCreateV4MembersUnprivatize.
type CoreCreateV4MembersUnprivatizeJSONBody struct {
	// InvitationSignature The invitation signature
	InvitationSignature *string `json:"InvitationSignature,omitempty"`
}

// CoreListV4MembersVpnParams defines parameters for CoreListV4MembersVpn.
type CoreListV4MembersVpnParams struct {
	Page     *string `form:"Page,omitempty" json:"Page,omitempty"`
	PageSize *string `form:"PageSize,omitempty" json:"PageSize,omitempty"`
}

// DomainsCreateDomainsJSONBody defines parameters for DomainsCreateDomains.
type DomainsCreateDomainsJSONBody struct {
	Name *string `json:"Name,omitempty"`
}

// DomainsGetDomainParams defines parameters for DomainsGetDomain.
type DomainsGetDomainParams struct {
	Refresh *string `form:"Refresh,omitempty" json:"Refresh,omitempty"`
}

// DriveCreateUrlsAuthJSONBody defines parameters for DriveCreateUrlsAuth.
type DriveCreateUrlsAuthJSONBody struct {
	ClientEphemeral *string `json:"ClientEphemeral,omitempty"`
	ClientProof     *string `json:"ClientProof,omitempty"`
	SRPSession      *string `json:"SRPSession,omitempty"`
}

// DriveCreateUrlsAuth200JSONResponseBodySharePublicPermissions defines parameters for DriveCreateUrlsAuth.
type DriveCreateUrlsAuth200JSONResponseBodySharePublicPermissions int

// DriveCreateUrlsBlocksJSONBody defines parameters for DriveCreateUrlsBlocks.
type DriveCreateUrlsBlocksJSONBody struct {
	BlockList *struct {
		EncSignature *string `json:"EncSignature,omitempty"`
		Hash         *string `json:"Hash,omitempty"`

		// Index Index of block in list (must be consecutive starting at 1)
		Index    *float32 `json:"Index,omitempty"`
		Size     *float32 `json:"Size,omitempty"`
		Verifier *struct {
			// Token Derived from verificationCode from GET /verification endpoint: base64(xor(verificationCode, padWithZeros(dataPacket, 32)))
			Token *string `json:"Token,omitempty"`
		} `json:"Verifier,omitempty"`
	} `json:"BlockList,omitempty"`
	Hash           *string `json:"Hash,omitempty"`
	Index          *string `json:"Index,omitempty"`
	LinkID         *string `json:"LinkID,omitempty"`
	RevisionID     *string `json:"RevisionID,omitempty"`
	SignatureEmail *string `json:"SignatureEmail,omitempty"`
	Size           *string `json:"Size,omitempty"`
	ThumbnailList  *struct {
		Hash *string                                         `json:"Hash,omitempty"`
		Size *float32                                        `json:"Size,omitempty"`
		Type *DriveCreateUrlsBlocksJSONBodyThumbnailListType `json:"Type,omitempty"`
	} `json:"ThumbnailList,omitempty"`
	Token    *string `json:"Token,omitempty"`
	Verifier *string `json:"Verifier,omitempty"`
}

// DriveCreateUrlsBlocksJSONBodyThumbnailListType defines parameters for DriveCreateUrlsBlocks.
type DriveCreateUrlsBlocksJSONBodyThumbnailListType int

// DriveCreateUrlsBlocks200JSONResponseBodyThumbnailLinkThumbnailType defines parameters for DriveCreateUrlsBlocks.
type DriveCreateUrlsBlocks200JSONResponseBodyThumbnailLinkThumbnailType int

// DriveCreateUrlsBlocks200JSONResponseBodyThumbnailLinksThumbnailType defines parameters for DriveCreateUrlsBlocks.
type DriveCreateUrlsBlocks200JSONResponseBodyThumbnailLinksThumbnailType int

// DriveCreateUrlsDocumentsJSONBody defines parameters for DriveCreateUrlsDocuments.
type DriveCreateUrlsDocumentsJSONBody struct {
	ContentKeyPacket          *string `json:"ContentKeyPacket,omitempty"`
	ContentKeyPacketSignature *string `json:"ContentKeyPacketSignature,omitempty"`

	// DocumentType Document=1, Sheet=2
	DocumentType *string `json:"DocumentType,omitempty"`

	// Hash File/folder name Hash
	Hash                    *string `json:"Hash,omitempty"`
	ManifestSignature       *string `json:"ManifestSignature,omitempty"`
	Name                    *string `json:"Name,omitempty"`
	NodeKey                 *string `json:"NodeKey,omitempty"`
	NodePassphrase          *string `json:"NodePassphrase,omitempty"`
	NodePassphraseSignature *string `json:"NodePassphraseSignature,omitempty"`
	ParentLinkID            *string `json:"ParentLinkID,omitempty"`
	SignatureEmail          *string `json:"SignatureEmail,omitempty"`
}

// DriveCreateUrlsFileJSONBody defines parameters for DriveCreateUrlsFile.
type DriveCreateUrlsFileJSONBody struct {
	ClientEphemeral *string  `json:"ClientEphemeral,omitempty"`
	ClientProof     *string  `json:"ClientProof,omitempty"`
	FromBlockIndex  *float32 `json:"FromBlockIndex,omitempty"`
	PageSize        *float32 `json:"PageSize,omitempty"`
	SRPSession      *string  `json:"SRPSession,omitempty"`
}

// DriveCreateUrlsFilesJSONBody defines parameters for DriveCreateUrlsFiles.
type DriveCreateUrlsFilesJSONBody struct {
	ClientUID                 *string `json:"ClientUID,omitempty"`
	ContentKeyPacket          *string `json:"ContentKeyPacket,omitempty"`
	ContentKeyPacketSignature *string `json:"ContentKeyPacketSignature,omitempty"`

	// Hash File/folder name Hash
	Hash                    *string  `json:"Hash,omitempty"`
	IntendedUploadSize      *float32 `json:"IntendedUploadSize,omitempty"`
	MIMEType                *string  `json:"MIMEType,omitempty"`
	Name                    *string  `json:"Name,omitempty"`
	NodeKey                 *string  `json:"NodeKey,omitempty"`
	NodePassphrase          *string  `json:"NodePassphrase,omitempty"`
	NodePassphraseSignature *string  `json:"NodePassphraseSignature,omitempty"`
	ParentLinkID            *string  `json:"ParentLinkID,omitempty"`
	SignatureEmail          *string  `json:"SignatureEmail,omitempty"`
}

// DriveGetUrlsFileParams defines parameters for DriveGetUrlsFile.
type DriveGetUrlsFileParams struct {
	PageSize       *string `form:"PageSize,omitempty" json:"PageSize,omitempty"`
	FromBlockIndex *string `form:"FromBlockIndex,omitempty" json:"FromBlockIndex,omitempty"`
	NoBlockUrls    *string `form:"NoBlockUrls,omitempty" json:"NoBlockUrls,omitempty"`
}

// DriveGetUrlsFile200JSONResponseBodyRevisionState defines parameters for DriveGetUrlsFile.
type DriveGetUrlsFile200JSONResponseBodyRevisionState int

// DriveGetUrlsFile200JSONResponseBodyRevisionThumbnail defines parameters for DriveGetUrlsFile.
type DriveGetUrlsFile200JSONResponseBodyRevisionThumbnail int

// DriveGetUrlsFile200JSONResponseBodyRevisionThumbnailsType defines parameters for DriveGetUrlsFile.
type DriveGetUrlsFile200JSONResponseBodyRevisionThumbnailsType int

// DriveCreateUrlsFilesCheckavailablehashesJSONBody defines parameters for DriveCreateUrlsFilesCheckavailablehashes.
type DriveCreateUrlsFilesCheckavailablehashesJSONBody struct {
	ClientUID *[]string `json:"ClientUID,omitempty"`
	Hashes    *[]string `json:"Hashes,omitempty"`
}

// DriveUpdateUrlsFilesRevisionJSONBody defines parameters for DriveUpdateUrlsFilesRevision.
type DriveUpdateUrlsFilesRevisionJSONBody struct {
	ChecksumVerified  *bool   `json:"ChecksumVerified,omitempty"`
	ManifestSignature *string `json:"ManifestSignature,omitempty"`
	Photo             *struct {
		// CaptureTime Photo capture timestamp (in seconds), use negative values for times before 1970
		CaptureTime *float32 `json:"CaptureTime,omitempty"`

		// ContentHash Photo content hash, lowercase hex representation of HMAC SHA256 of SHA1 content using parent folder's hash key [ hmacSha256(folder hash key, sha1(plain content)) ]
		ContentHash     *string                                        `json:"ContentHash,omitempty"`
		Exif            *string                                        `json:"Exif,omitempty"`
		MainPhotoLinkID *string                                        `json:"MainPhotoLinkID,omitempty"`
		Tags            *DriveUpdateUrlsFilesRevisionJSONBodyPhotoTags `json:"Tags,omitempty"`
	} `json:"Photo,omitempty"`
	SignatureEmail *string `json:"SignatureEmail,omitempty"`

	// XAttr Extended attributes encrypted with link key
	XAttr *string `json:"XAttr,omitempty"`
}

// DriveUpdateUrlsFilesRevisionJSONBodyPhotoTags defines parameters for DriveUpdateUrlsFilesRevision.
type DriveUpdateUrlsFilesRevisionJSONBodyPhotoTags int

// DriveCreateUrlsFoldersJSONBody defines parameters for DriveCreateUrlsFolders.
type DriveCreateUrlsFoldersJSONBody struct {
	// Hash File/folder name Hash
	Hash *string `json:"Hash,omitempty"`
	Name *string `json:"Name,omitempty"`

	// NodeHashKey Node hash key (random bytes encoded in base64 format), encrypted and signed.
	NodeHashKey             *string `json:"NodeHashKey,omitempty"`
	NodeKey                 *string `json:"NodeKey,omitempty"`
	NodePassphrase          *string `json:"NodePassphrase,omitempty"`
	NodePassphraseSignature *string `json:"NodePassphraseSignature,omitempty"`
	ParentLinkID            *string `json:"ParentLinkID,omitempty"`
	SignatureEmail          *string `json:"SignatureEmail,omitempty"`
	XAttr                   *string `json:"XAttr,omitempty"`
}

// DriveListUrlsFoldersChildrenParams defines parameters for DriveListUrlsFoldersChildren.
type DriveListUrlsFoldersChildrenParams struct {
	Page        *string                                        `form:"Page,omitempty" json:"Page,omitempty"`
	Thumbnails  *DriveListUrlsFoldersChildrenParamsThumbnails  `form:"Thumbnails,omitempty" json:"Thumbnails,omitempty"`
	PageSize    *string                                        `form:"PageSize,omitempty" json:"PageSize,omitempty"`
	Sort        *string                                        `form:"Sort,omitempty" json:"Sort,omitempty"`
	Desc        *DriveListUrlsFoldersChildrenParamsDesc        `form:"Desc,omitempty" json:"Desc,omitempty"`
	ShowAll     *DriveListUrlsFoldersChildrenParamsShowAll     `form:"ShowAll,omitempty" json:"ShowAll,omitempty"`
	FoldersOnly *DriveListUrlsFoldersChildrenParamsFoldersOnly `form:"FoldersOnly,omitempty" json:"FoldersOnly,omitempty"`
}

// DriveListUrlsFoldersChildrenParamsThumbnails defines parameters for DriveListUrlsFoldersChildren.
type DriveListUrlsFoldersChildrenParamsThumbnails int

// DriveListUrlsFoldersChildrenParamsDesc defines parameters for DriveListUrlsFoldersChildren.
type DriveListUrlsFoldersChildrenParamsDesc int

// DriveListUrlsFoldersChildrenParamsShowAll defines parameters for DriveListUrlsFoldersChildren.
type DriveListUrlsFoldersChildrenParamsShowAll int

// DriveListUrlsFoldersChildrenParamsFoldersOnly defines parameters for DriveListUrlsFoldersChildren.
type DriveListUrlsFoldersChildrenParamsFoldersOnly int

// DriveCreateUrlsFoldersDeleteMultipleJSONBody defines parameters for DriveCreateUrlsFoldersDeleteMultiple.
type DriveCreateUrlsFoldersDeleteMultipleJSONBody struct {
	Links *struct {
		AuthorizationToken *string `json:"AuthorizationToken,omitempty"`
		LinkID             *string `json:"LinkID,omitempty"`
	} `json:"Links,omitempty"`
}

// DriveCreateUrlsFoldersDeleteMultiple200JSONResponseBodyResponseCode defines parameters for DriveCreateUrlsFoldersDeleteMultiple.
type DriveCreateUrlsFoldersDeleteMultiple200JSONResponseBodyResponseCode int

// DriveListUrlsInfo200JSONResponseBodyVendorType defines parameters for DriveListUrlsInfo.
type DriveListUrlsInfo200JSONResponseBodyVendorType int

// DriveCreateUrlsLinksFetchMetadataJSONBody defines parameters for DriveCreateUrlsLinksFetchMetadata.
type DriveCreateUrlsLinksFetchMetadataJSONBody struct {
	LinkIDs *string `json:"LinkIDs,omitempty"`
}

// DriveUpdateUrlsLinksRenameJSONBody defines parameters for DriveUpdateUrlsLinksRename.
type DriveUpdateUrlsLinksRenameJSONBody struct {
	AuthorizationToken *string `json:"AuthorizationToken,omitempty"`

	// Hash Name hash
	Hash     *string `json:"Hash,omitempty"`
	MIMEType *string `json:"MIMEType,omitempty"`

	// Name Name, reusing same session key as previously.
	Name               *string `json:"Name,omitempty"`
	NameSignatureEmail *string `json:"NameSignatureEmail,omitempty"`

	// OriginalHash Current name hash before move operation. Used to prevent race conditions.
	OriginalHash *string `json:"OriginalHash,omitempty"`
}

// DriveCreateUrlsSecurityJSONBody defines parameters for DriveCreateUrlsSecurity.
type DriveCreateUrlsSecurityJSONBody struct {
	Hashes *[]string `json:"Hashes,omitempty"`
}

// DriveCreateV2UrlsBookmarkJSONBody defines parameters for DriveCreateV2UrlsBookmark.
type DriveCreateV2UrlsBookmarkJSONBody struct {
	BookmarkShareURL *struct {
		AddressID            *string `json:"AddressID,omitempty"`
		AddressKeyID         *string `json:"AddressKeyID,omitempty"`
		EncryptedUrlPassword *string `json:"EncryptedUrlPassword,omitempty"`
	} `json:"BookmarkShareURL,omitempty"`
}

// DriveCreateV2UrlsBookmark200JSONResponseBodyBookmarkShareURLState defines parameters for DriveCreateV2UrlsBookmark.
type DriveCreateV2UrlsBookmark200JSONResponseBodyBookmarkShareURLState int

// MetricsCreateMetricsJSONBody defines parameters for MetricsCreateMetrics.
type MetricsCreateMetricsJSONBody struct {
	Log   *string `json:"Log,omitempty"`
	Title *string `json:"Title,omitempty"`
}

// PermissionsUpdateV1MembersRolesJSONBody defines parameters for PermissionsUpdateV1MembersRoles.
type PermissionsUpdateV1MembersRolesJSONBody struct {
	Add    *string `json:"Add,omitempty"`
	Remove *string `json:"Remove,omitempty"`
}

// CalendarUpdateV1EventsAcceptJSONRequestBody defines body for CalendarUpdateV1EventsAccept for application/json ContentType.
type CalendarUpdateV1EventsAcceptJSONRequestBody CalendarUpdateV1EventsAcceptJSONBody

// CalendarCreateV1KeysResetJSONRequestBody defines body for CalendarCreateV1KeysReset for application/json ContentType.
type CalendarCreateV1KeysResetJSONRequestBody CalendarCreateV1KeysResetJSONBody

// CalendarCreateV1SubscriptionValidateJSONRequestBody defines body for CalendarCreateV1SubscriptionValidate for application/json ContentType.
type CalendarCreateV1SubscriptionValidateJSONRequestBody CalendarCreateV1SubscriptionValidateJSONBody

// CalendarCreateV1VideoconferencesJSONRequestBody defines body for CalendarCreateV1Videoconferences for application/json ContentType.
type CalendarCreateV1VideoconferencesJSONRequestBody CalendarCreateV1VideoconferencesJSONBody

// CalendarUpdateV1InvitationsAcceptJSONRequestBody defines body for CalendarUpdateV1InvitationsAccept for application/json ContentType.
type CalendarUpdateV1InvitationsAcceptJSONRequestBody CalendarUpdateV1InvitationsAcceptJSONBody

// CalendarCreateV1InvitationsJoinJSONRequestBody defines body for CalendarCreateV1InvitationsJoin for application/json ContentType.
type CalendarCreateV1InvitationsJoinJSONRequestBody CalendarCreateV1InvitationsJoinJSONBody

// CalendarUpdateV1KeyJSONRequestBody defines body for CalendarUpdateV1Key for application/json ContentType.
type CalendarUpdateV1KeyJSONRequestBody CalendarUpdateV1KeyJSONBody

// CalendarCreateV1MembersJSONRequestBody defines body for CalendarCreateV1Members for application/json ContentType.
type CalendarCreateV1MembersJSONRequestBody CalendarCreateV1MembersJSONBody

// CalendarUpdateV1UrlJSONRequestBody defines body for CalendarUpdateV1Url for application/json ContentType.
type CalendarUpdateV1UrlJSONRequestBody CalendarUpdateV1UrlJSONBody

// CoreCreateV4KeysJSONRequestBody defines body for CoreCreateV4Keys for application/json ContentType.
type CoreCreateV4KeysJSONRequestBody CoreCreateV4KeysJSONBody

// CoreCreateV4KeysAddressDeleteJSONRequestBody defines body for CoreCreateV4KeysAddressDelete for application/json ContentType.
type CoreCreateV4KeysAddressDeleteJSONRequestBody CoreCreateV4KeysAddressDeleteJSONBody

// CoreCreateV4KeysMigrateJSONRequestBody defines body for CoreCreateV4KeysMigrate for application/json ContentType.
type CoreCreateV4KeysMigrateJSONRequestBody CoreCreateV4KeysMigrateJSONBody

// CoreUpdateV4KeysPrivateJSONRequestBody defines body for CoreUpdateV4KeysPrivate for application/json ContentType.
type CoreUpdateV4KeysPrivateJSONRequestBody CoreUpdateV4KeysPrivateJSONBody

// CoreCreateV4KeysResetJSONRequestBody defines body for CoreCreateV4KeysReset for application/json ContentType.
type CoreCreateV4KeysResetJSONRequestBody CoreCreateV4KeysResetJSONBody

// CoreCreateV4KeysSetupJSONRequestBody defines body for CoreCreateV4KeysSetup for application/json ContentType.
type CoreCreateV4KeysSetupJSONRequestBody CoreCreateV4KeysSetupJSONBody

// CoreUpdateV4KeysTokensJSONRequestBody defines body for CoreUpdateV4KeysTokens for application/json ContentType.
type CoreUpdateV4KeysTokensJSONRequestBody CoreUpdateV4KeysTokensJSONBody

// CoreCreateV4KeysUserJSONRequestBody defines body for CoreCreateV4KeysUser for application/json ContentType.
type CoreCreateV4KeysUserJSONRequestBody CoreCreateV4KeysUserJSONBody

// CoreUpdateV4KeysUserJSONRequestBody defines body for CoreUpdateV4KeysUser for application/json ContentType.
type CoreUpdateV4KeysUserJSONRequestBody CoreUpdateV4KeysUserJSONBody

// CoreUpdateV4KeyJSONRequestBody defines body for CoreUpdateV4Key for application/json ContentType.
type CoreUpdateV4KeyJSONRequestBody CoreUpdateV4KeyJSONBody

// CoreUpdateV4KeysActivateJSONRequestBody defines body for CoreUpdateV4KeysActivate for application/json ContentType.
type CoreUpdateV4KeysActivateJSONRequestBody CoreUpdateV4KeysActivateJSONBody

// CoreUpdateV4KeysDeleteJSONRequestBody defines body for CoreUpdateV4KeysDelete for application/json ContentType.
type CoreUpdateV4KeysDeleteJSONRequestBody CoreUpdateV4KeysDeleteJSONBody

// CoreUpdateV4KeysFlagsJSONRequestBody defines body for CoreUpdateV4KeysFlags for application/json ContentType.
type CoreUpdateV4KeysFlagsJSONRequestBody CoreUpdateV4KeysFlagsJSONBody

// CoreUpdateV4KeysPrimaryJSONRequestBody defines body for CoreUpdateV4KeysPrimary for application/json ContentType.
type CoreUpdateV4KeysPrimaryJSONRequestBody CoreUpdateV4KeysPrimaryJSONBody

// CoreCreateV4MembersJSONRequestBody defines body for CoreCreateV4Members for application/json ContentType.
type CoreCreateV4MembersJSONRequestBody CoreCreateV4MembersJSONBody

// CoreCreateV4MembersAddressesAvailableJSONRequestBody defines body for CoreCreateV4MembersAddressesAvailable for application/json ContentType.
type CoreCreateV4MembersAddressesAvailableJSONRequestBody CoreCreateV4MembersAddressesAvailableJSONBody

// CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONRequestBody defines body for CoreUpdateV4MembersAddressesPermissionsOrganizationSwitch for application/json ContentType.
type CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONRequestBody CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONBody

// CoreCreateV4MembersInvitationsJSONRequestBody defines body for CoreCreateV4MembersInvitations for application/json ContentType.
type CoreCreateV4MembersInvitationsJSONRequestBody CoreCreateV4MembersInvitationsJSONBody

// CoreUpdateV4MembersInvitationJSONRequestBody defines body for CoreUpdateV4MembersInvitation for application/json ContentType.
type CoreUpdateV4MembersInvitationJSONRequestBody CoreUpdateV4MembersInvitationJSONBody

// CoreCreateV4MembersMeUnprivatizeJSONRequestBody defines body for CoreCreateV4MembersMeUnprivatize for application/json ContentType.
type CoreCreateV4MembersMeUnprivatizeJSONRequestBody CoreCreateV4MembersMeUnprivatizeJSONBody

// CoreUpdateV4MembersPermissionsJSONRequestBody defines body for CoreUpdateV4MembersPermissions for application/json ContentType.
type CoreUpdateV4MembersPermissionsJSONRequestBody CoreUpdateV4MembersPermissionsJSONBody

// CoreCreateV4MembersAddressesJSONRequestBody defines body for CoreCreateV4MembersAddresses for application/json ContentType.
type CoreCreateV4MembersAddressesJSONRequestBody CoreCreateV4MembersAddressesJSONBody

// CoreUpdateV4MembersAddressesOrderJSONRequestBody defines body for CoreUpdateV4MembersAddressesOrder for application/json ContentType.
type CoreUpdateV4MembersAddressesOrderJSONRequestBody CoreUpdateV4MembersAddressesOrderJSONBody

// CoreUpdateV4MembersAiJSONRequestBody defines body for CoreUpdateV4MembersAi for application/json ContentType.
type CoreUpdateV4MembersAiJSONRequestBody CoreUpdateV4MembersAiJSONBody

// CoreCreateV4MembersDevicesResetJSONRequestBody defines body for CoreCreateV4MembersDevicesReset for application/json ContentType.
type CoreCreateV4MembersDevicesResetJSONRequestBody CoreCreateV4MembersDevicesResetJSONBody

// CoreCreateV4MembersKeysJSONRequestBody defines body for CoreCreateV4MembersKeys for application/json ContentType.
type CoreCreateV4MembersKeysJSONRequestBody CoreCreateV4MembersKeysJSONBody

// CoreCreateV4MembersKeysSetupJSONRequestBody defines body for CoreCreateV4MembersKeysSetup for application/json ContentType.
type CoreCreateV4MembersKeysSetupJSONRequestBody CoreCreateV4MembersKeysSetupJSONBody

// CoreCreateV4MembersKeysUnprivatizeJSONRequestBody defines body for CoreCreateV4MembersKeysUnprivatize for application/json ContentType.
type CoreCreateV4MembersKeysUnprivatizeJSONRequestBody CoreCreateV4MembersKeysUnprivatizeJSONBody

// CoreUpdateV4MembersLumoJSONRequestBody defines body for CoreUpdateV4MembersLumo for application/json ContentType.
type CoreUpdateV4MembersLumoJSONRequestBody CoreUpdateV4MembersLumoJSONBody

// CoreUpdateV4MembersRoleJSONRequestBody defines body for CoreUpdateV4MembersRole for application/json ContentType.
type CoreUpdateV4MembersRoleJSONRequestBody CoreUpdateV4MembersRoleJSONBody

// CoreCreateV4MembersUnprivatizeJSONRequestBody defines body for CoreCreateV4MembersUnprivatize for application/json ContentType.
type CoreCreateV4MembersUnprivatizeJSONRequestBody CoreCreateV4MembersUnprivatizeJSONBody

// DomainsCreateDomainsJSONRequestBody defines body for DomainsCreateDomains for application/json ContentType.
type DomainsCreateDomainsJSONRequestBody DomainsCreateDomainsJSONBody

// DriveCreateUrlsAuthJSONRequestBody defines body for DriveCreateUrlsAuth for application/json ContentType.
type DriveCreateUrlsAuthJSONRequestBody DriveCreateUrlsAuthJSONBody

// DriveCreateUrlsBlocksJSONRequestBody defines body for DriveCreateUrlsBlocks for application/json ContentType.
type DriveCreateUrlsBlocksJSONRequestBody DriveCreateUrlsBlocksJSONBody

// DriveCreateUrlsDocumentsJSONRequestBody defines body for DriveCreateUrlsDocuments for application/json ContentType.
type DriveCreateUrlsDocumentsJSONRequestBody DriveCreateUrlsDocumentsJSONBody

// DriveCreateUrlsFileJSONRequestBody defines body for DriveCreateUrlsFile for application/json ContentType.
type DriveCreateUrlsFileJSONRequestBody DriveCreateUrlsFileJSONBody

// DriveCreateUrlsFilesJSONRequestBody defines body for DriveCreateUrlsFiles for application/json ContentType.
type DriveCreateUrlsFilesJSONRequestBody DriveCreateUrlsFilesJSONBody

// DriveCreateUrlsFilesCheckavailablehashesJSONRequestBody defines body for DriveCreateUrlsFilesCheckavailablehashes for application/json ContentType.
type DriveCreateUrlsFilesCheckavailablehashesJSONRequestBody DriveCreateUrlsFilesCheckavailablehashesJSONBody

// DriveUpdateUrlsFilesRevisionJSONRequestBody defines body for DriveUpdateUrlsFilesRevision for application/json ContentType.
type DriveUpdateUrlsFilesRevisionJSONRequestBody DriveUpdateUrlsFilesRevisionJSONBody

// DriveCreateUrlsFoldersJSONRequestBody defines body for DriveCreateUrlsFolders for application/json ContentType.
type DriveCreateUrlsFoldersJSONRequestBody DriveCreateUrlsFoldersJSONBody

// DriveCreateUrlsFoldersDeleteMultipleJSONRequestBody defines body for DriveCreateUrlsFoldersDeleteMultiple for application/json ContentType.
type DriveCreateUrlsFoldersDeleteMultipleJSONRequestBody DriveCreateUrlsFoldersDeleteMultipleJSONBody

// DriveCreateUrlsLinksFetchMetadataJSONRequestBody defines body for DriveCreateUrlsLinksFetchMetadata for application/json ContentType.
type DriveCreateUrlsLinksFetchMetadataJSONRequestBody DriveCreateUrlsLinksFetchMetadataJSONBody

// DriveUpdateUrlsLinksRenameJSONRequestBody defines body for DriveUpdateUrlsLinksRename for application/json ContentType.
type DriveUpdateUrlsLinksRenameJSONRequestBody DriveUpdateUrlsLinksRenameJSONBody

// DriveCreateUrlsSecurityJSONRequestBody defines body for DriveCreateUrlsSecurity for application/json ContentType.
type DriveCreateUrlsSecurityJSONRequestBody DriveCreateUrlsSecurityJSONBody

// DriveCreateV2UrlsBookmarkJSONRequestBody defines body for DriveCreateV2UrlsBookmark for application/json ContentType.
type DriveCreateV2UrlsBookmarkJSONRequestBody DriveCreateV2UrlsBookmarkJSONBody

// MetricsCreateMetricsJSONRequestBody defines body for MetricsCreateMetrics for application/json ContentType.
type MetricsCreateMetricsJSONRequestBody MetricsCreateMetricsJSONBody

// PermissionsUpdateV1MembersRolesJSONRequestBody defines body for PermissionsUpdateV1MembersRoles for application/json ContentType.
type PermissionsUpdateV1MembersRolesJSONRequestBody PermissionsUpdateV1MembersRolesJSONBody
