// Package meetapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package meetapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// MeetCreateV1MeetingsLinksFeedbackWithBody performs a POST /meet/v1/meetings/links/{meetingLinkName}/feedback (the `MeetCreateV1MeetingsLinksFeedback` operationId) request,
	// with any type of body and a specified content type.
	MeetCreateV1MeetingsLinksFeedbackWithBody(ctx context.Context, meetingLinkName string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// MeetCreateV1MeetingsLinksFeedback performs a POST /meet/v1/meetings/links/{meetingLinkName}/feedback (the `MeetCreateV1MeetingsLinksFeedback` operationId) request.
	// Takes a body of the `application/json` content type.
	MeetCreateV1MeetingsLinksFeedback(ctx context.Context, meetingLinkName string, body MeetCreateV1MeetingsLinksFeedbackJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// MeetCreateV1MeetingsLinksLockWithBody performs a POST /meet/v1/meetings/links/{meetingLinkName}/lock (the `MeetCreateV1MeetingsLinksLock` operationId) request,
	// with any type of body and a specified content type.
	MeetCreateV1MeetingsLinksLockWithBody(ctx context.Context, meetingLinkName string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// MeetCreateV1MeetingsLinksLock performs a POST /meet/v1/meetings/links/{meetingLinkName}/lock (the `MeetCreateV1MeetingsLinksLock` operationId) request.
	// Takes a body of the `application/json` content type.
	MeetCreateV1MeetingsLinksLock(ctx context.Context, meetingLinkName string, body MeetCreateV1MeetingsLinksLockJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// MeetCreateV1MeetingsLinksUnlockWithBody performs a POST /meet/v1/meetings/links/{meetingLinkName}/unlock (the `MeetCreateV1MeetingsLinksUnlock` operationId) request,
	// with any type of body and a specified content type.
	MeetCreateV1MeetingsLinksUnlockWithBody(ctx context.Context, meetingLinkName string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// MeetCreateV1MeetingsLinksUnlock performs a POST /meet/v1/meetings/links/{meetingLinkName}/unlock (the `MeetCreateV1MeetingsLinksUnlock` operationId) request.
	// Takes a body of the `application/json` content type.
	MeetCreateV1MeetingsLinksUnlock(ctx context.Context, meetingLinkName string, body MeetCreateV1MeetingsLinksUnlockJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// MeetUpdateV1MeetingsLinksWaitingRoomWithBody performs a PUT /meet/v1/meetings/links/{meetingLinkName}/waiting-room (the `MeetUpdateV1MeetingsLinksWaitingRoom` operationId) request,
	// with any type of body and a specified content type.
	MeetUpdateV1MeetingsLinksWaitingRoomWithBody(ctx context.Context, meetingLinkName string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// MeetUpdateV1MeetingsLinksWaitingRoom performs a PUT /meet/v1/meetings/links/{meetingLinkName}/waiting-room (the `MeetUpdateV1MeetingsLinksWaitingRoom` operationId) request.
	// Takes a body of the `application/json` content type.
	MeetUpdateV1MeetingsLinksWaitingRoom(ctx context.Context, meetingLinkName string, body MeetUpdateV1MeetingsLinksWaitingRoomJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// MeetUpdateV1MeetingsNameWithBody performs a PUT /meet/v1/meetings/{meetingId}/name (the `MeetUpdateV1MeetingsName` operationId) request,
	// with any type of body and a specified content type.
	MeetUpdateV1MeetingsNameWithBody(ctx context.Context, meetingId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// MeetUpdateV1MeetingsName performs a PUT /meet/v1/meetings/{meetingId}/name (the `MeetUpdateV1MeetingsName` operationId) request.
	// Takes a body of the `application/json` content type.
	MeetUpdateV1MeetingsName(ctx context.Context, meetingId string, body MeetUpdateV1MeetingsNameJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// MeetUpdateV1MeetingsScheduleWithBody performs a PUT /meet/v1/meetings/{meetingId}/schedule (the `MeetUpdateV1MeetingsSchedule` operationId) request,
	// with any type of body and a specified content type.
	MeetUpdateV1MeetingsScheduleWithBody(ctx context.Context, meetingId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// MeetUpdateV1MeetingsSchedule performs a PUT /meet/v1/meetings/{meetingId}/schedule (the `MeetUpdateV1MeetingsSchedule` operationId) request.
	// Takes a body of the `application/json` content type.
	MeetUpdateV1MeetingsSchedule(ctx context.Context, meetingId string, body MeetUpdateV1MeetingsScheduleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// MeetCreateV1MeetingsLinksFeedbackWithBody performs a POST /meet/v1/meetings/links/{meetingLinkName}/feedback (the `MeetCreateV1MeetingsLinksFeedback` operationId) request,
// with any type of body and a specified content type.
func (c *Client) MeetCreateV1MeetingsLinksFeedbackWithBody(ctx context.Context, meetingLinkName string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMeetCreateV1MeetingsLinksFeedbackRequestWithBody(c.Server, meetingLinkName, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// MeetCreateV1MeetingsLinksFeedback performs a POST /meet/v1/meetings/links/{meetingLinkName}/feedback (the `MeetCreateV1MeetingsLinksFeedback` operationId) request.
// Takes a body of the `application/json` content type.
func (c *Client) MeetCreateV1MeetingsLinksFeedback(ctx context.Context, meetingLinkName string, body MeetCreateV1MeetingsLinksFeedbackJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMeetCreateV1MeetingsLinksFeedbackRequest(c.Server, meetingLinkName, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// MeetCreateV1MeetingsLinksLockWithBody performs a POST /meet/v1/meetings/links/{meetingLinkName}/lock (the `MeetCreateV1MeetingsLinksLock` operationId) request,
// with any type of body and a specified content type.
func (c *Client) MeetCreateV1MeetingsLinksLockWithBody(ctx context.Context, meetingLinkName string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMeetCreateV1MeetingsLinksLockRequestWithBody(c.Server, meetingLinkName, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// MeetCreateV1MeetingsLinksLock performs a POST /meet/v1/meetings/links/{meetingLinkName}/lock (the `MeetCreateV1MeetingsLinksLock` operationId) request.
// Takes a body of the `application/json` content type.
func (c *Client) MeetCreateV1MeetingsLinksLock(ctx context.Context, meetingLinkName string, body MeetCreateV1MeetingsLinksLockJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMeetCreateV1MeetingsLinksLockRequest(c.Server, meetingLinkName, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// MeetCreateV1MeetingsLinksUnlockWithBody performs a POST /meet/v1/meetings/links/{meetingLinkName}/unlock (the `MeetCreateV1MeetingsLinksUnlock` operationId) request,
// with any type of body and a specified content type.
func (c *Client) MeetCreateV1MeetingsLinksUnlockWithBody(ctx context.Context, meetingLinkName string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMeetCreateV1MeetingsLinksUnlockRequestWithBody(c.Server, meetingLinkName, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// MeetCreateV1MeetingsLinksUnlock performs a POST /meet/v1/meetings/links/{meetingLinkName}/unlock (the `MeetCreateV1MeetingsLinksUnlock` operationId) request.
// Takes a body of the `application/json` content type.
func (c *Client) MeetCreateV1MeetingsLinksUnlock(ctx context.Context, meetingLinkName string, body MeetCreateV1MeetingsLinksUnlockJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMeetCreateV1MeetingsLinksUnlockRequest(c.Server, meetingLinkName, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// MeetUpdateV1MeetingsLinksWaitingRoomWithBody performs a PUT /meet/v1/meetings/links/{meetingLinkName}/waiting-room (the `MeetUpdateV1MeetingsLinksWaitingRoom` operationId) request,
// with any type of body and a specified content type.
func (c *Client) MeetUpdateV1MeetingsLinksWaitingRoomWithBody(ctx context.Context, meetingLinkName string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMeetUpdateV1MeetingsLinksWaitingRoomRequestWithBody(c.Server, meetingLinkName, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// MeetUpdateV1MeetingsLinksWaitingRoom performs a PUT /meet/v1/meetings/links/{meetingLinkName}/waiting-room (the `MeetUpdateV1MeetingsLinksWaitingRoom` operationId) request.
// Takes a body of the `application/json` content type.
func (c *Client) MeetUpdateV1MeetingsLinksWaitingRoom(ctx context.Context, meetingLinkName string, body MeetUpdateV1MeetingsLinksWaitingRoomJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMeetUpdateV1MeetingsLinksWaitingRoomRequest(c.Server, meetingLinkName, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// MeetUpdateV1MeetingsNameWithBody performs a PUT /meet/v1/meetings/{meetingId}/name (the `MeetUpdateV1MeetingsName` operationId) request,
// with any type of body and a specified content type.
func (c *Client) MeetUpdateV1MeetingsNameWithBody(ctx context.Context, meetingId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMeetUpdateV1MeetingsNameRequestWithBody(c.Server, meetingId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// MeetUpdateV1MeetingsName performs a PUT /meet/v1/meetings/{meetingId}/name (the `MeetUpdateV1MeetingsName` operationId) request.
// Takes a body of the `application/json` content type.
func (c *Client) MeetUpdateV1MeetingsName(ctx context.Context, meetingId string, body MeetUpdateV1MeetingsNameJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMeetUpdateV1MeetingsNameRequest(c.Server, meetingId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// MeetUpdateV1MeetingsScheduleWithBody performs a PUT /meet/v1/meetings/{meetingId}/schedule (the `MeetUpdateV1MeetingsSchedule` operationId) request,
// with any type of body and a specified content type.
func (c *Client) MeetUpdateV1MeetingsScheduleWithBody(ctx context.Context, meetingId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMeetUpdateV1MeetingsScheduleRequestWithBody(c.Server, meetingId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// MeetUpdateV1MeetingsSchedule performs a PUT /meet/v1/meetings/{meetingId}/schedule (the `MeetUpdateV1MeetingsSchedule` operationId) request.
// Takes a body of the `application/json` content type.
func (c *Client) MeetUpdateV1MeetingsSchedule(ctx context.Context, meetingId string, body MeetUpdateV1MeetingsScheduleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMeetUpdateV1MeetingsScheduleRequest(c.Server, meetingId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewMeetCreateV1MeetingsLinksFeedbackRequest calls the generic MeetCreateV1MeetingsLinksFeedback builder with application/json body
func NewMeetCreateV1MeetingsLinksFeedbackRequest(server string, meetingLinkName string, body MeetCreateV1MeetingsLinksFeedbackJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewMeetCreateV1MeetingsLinksFeedbackRequestWithBody(server, meetingLinkName, "application/json", bodyReader)
}

// NewMeetCreateV1MeetingsLinksFeedbackRequestWithBody constructs an http.Request for the MeetCreateV1MeetingsLinksFeedback method, with any body, and a specified content type
func NewMeetCreateV1MeetingsLinksFeedbackRequestWithBody(server string, meetingLinkName string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "meetingLinkName", meetingLinkName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/meet/v1/meetings/links/%s/feedback", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewMeetCreateV1MeetingsLinksLockRequest calls the generic MeetCreateV1MeetingsLinksLock builder with application/json body
func NewMeetCreateV1MeetingsLinksLockRequest(server string, meetingLinkName string, body MeetCreateV1MeetingsLinksLockJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewMeetCreateV1MeetingsLinksLockRequestWithBody(server, meetingLinkName, "application/json", bodyReader)
}

// NewMeetCreateV1MeetingsLinksLockRequestWithBody constructs an http.Request for the MeetCreateV1MeetingsLinksLock method, with any body, and a specified content type
func NewMeetCreateV1MeetingsLinksLockRequestWithBody(server string, meetingLinkName string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "meetingLinkName", meetingLinkName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/meet/v1/meetings/links/%s/lock", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewMeetCreateV1MeetingsLinksUnlockRequest calls the generic MeetCreateV1MeetingsLinksUnlock builder with application/json body
func NewMeetCreateV1MeetingsLinksUnlockRequest(server string, meetingLinkName string, body MeetCreateV1MeetingsLinksUnlockJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewMeetCreateV1MeetingsLinksUnlockRequestWithBody(server, meetingLinkName, "application/json", bodyReader)
}

// NewMeetCreateV1MeetingsLinksUnlockRequestWithBody constructs an http.Request for the MeetCreateV1MeetingsLinksUnlock method, with any body, and a specified content type
func NewMeetCreateV1MeetingsLinksUnlockRequestWithBody(server string, meetingLinkName string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "meetingLinkName", meetingLinkName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/meet/v1/meetings/links/%s/unlock", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewMeetUpdateV1MeetingsLinksWaitingRoomRequest calls the generic MeetUpdateV1MeetingsLinksWaitingRoom builder with application/json body
func NewMeetUpdateV1MeetingsLinksWaitingRoomRequest(server string, meetingLinkName string, body MeetUpdateV1MeetingsLinksWaitingRoomJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewMeetUpdateV1MeetingsLinksWaitingRoomRequestWithBody(server, meetingLinkName, "application/json", bodyReader)
}

// NewMeetUpdateV1MeetingsLinksWaitingRoomRequestWithBody constructs an http.Request for the MeetUpdateV1MeetingsLinksWaitingRoom method, with any body, and a specified content type
func NewMeetUpdateV1MeetingsLinksWaitingRoomRequestWithBody(server string, meetingLinkName string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "meetingLinkName", meetingLinkName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/meet/v1/meetings/links/%s/waiting-room", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewMeetUpdateV1MeetingsNameRequest calls the generic MeetUpdateV1MeetingsName builder with application/json body
func NewMeetUpdateV1MeetingsNameRequest(server string, meetingId string, body MeetUpdateV1MeetingsNameJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewMeetUpdateV1MeetingsNameRequestWithBody(server, meetingId, "application/json", bodyReader)
}

// NewMeetUpdateV1MeetingsNameRequestWithBody constructs an http.Request for the MeetUpdateV1MeetingsName method, with any body, and a specified content type
func NewMeetUpdateV1MeetingsNameRequestWithBody(server string, meetingId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "meetingId", meetingId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/meet/v1/meetings/%s/name", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewMeetUpdateV1MeetingsScheduleRequest calls the generic MeetUpdateV1MeetingsSchedule builder with application/json body
func NewMeetUpdateV1MeetingsScheduleRequest(server string, meetingId string, body MeetUpdateV1MeetingsScheduleJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewMeetUpdateV1MeetingsScheduleRequestWithBody(server, meetingId, "application/json", bodyReader)
}

// NewMeetUpdateV1MeetingsScheduleRequestWithBody constructs an http.Request for the MeetUpdateV1MeetingsSchedule method, with any body, and a specified content type
func NewMeetUpdateV1MeetingsScheduleRequestWithBody(server string, meetingId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "meetingId", meetingId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/meet/v1/meetings/%s/schedule", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// MeetCreateV1MeetingsLinksFeedbackWithBodyWithResponse performs a POST /meet/v1/meetings/links/{meetingLinkName}/feedback (the `MeetCreateV1MeetingsLinksFeedback` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	MeetCreateV1MeetingsLinksFeedbackWithBodyWithResponse(ctx context.Context, meetingLinkName string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*MeetCreateV1MeetingsLinksFeedbackResponse, error)

	// MeetCreateV1MeetingsLinksFeedbackWithResponse performs a POST /meet/v1/meetings/links/{meetingLinkName}/feedback (the `MeetCreateV1MeetingsLinksFeedback` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	MeetCreateV1MeetingsLinksFeedbackWithResponse(ctx context.Context, meetingLinkName string, body MeetCreateV1MeetingsLinksFeedbackJSONRequestBody, reqEditors ...RequestEditorFn) (*MeetCreateV1MeetingsLinksFeedbackResponse, error)

	// MeetCreateV1MeetingsLinksLockWithBodyWithResponse performs a POST /meet/v1/meetings/links/{meetingLinkName}/lock (the `MeetCreateV1MeetingsLinksLock` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	MeetCreateV1MeetingsLinksLockWithBodyWithResponse(ctx context.Context, meetingLinkName string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*MeetCreateV1MeetingsLinksLockResponse, error)

	// MeetCreateV1MeetingsLinksLockWithResponse performs a POST /meet/v1/meetings/links/{meetingLinkName}/lock (the `MeetCreateV1MeetingsLinksLock` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	MeetCreateV1MeetingsLinksLockWithResponse(ctx context.Context, meetingLinkName string, body MeetCreateV1MeetingsLinksLockJSONRequestBody, reqEditors ...RequestEditorFn) (*MeetCreateV1MeetingsLinksLockResponse, error)

	// MeetCreateV1MeetingsLinksUnlockWithBodyWithResponse performs a POST /meet/v1/meetings/links/{meetingLinkName}/unlock (the `MeetCreateV1MeetingsLinksUnlock` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	MeetCreateV1MeetingsLinksUnlockWithBodyWithResponse(ctx context.Context, meetingLinkName string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*MeetCreateV1MeetingsLinksUnlockResponse, error)

	// MeetCreateV1MeetingsLinksUnlockWithResponse performs a POST /meet/v1/meetings/links/{meetingLinkName}/unlock (the `MeetCreateV1MeetingsLinksUnlock` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	MeetCreateV1MeetingsLinksUnlockWithResponse(ctx context.Context, meetingLinkName string, body MeetCreateV1MeetingsLinksUnlockJSONRequestBody, reqEditors ...RequestEditorFn) (*MeetCreateV1MeetingsLinksUnlockResponse, error)

	// MeetUpdateV1MeetingsLinksWaitingRoomWithBodyWithResponse performs a PUT /meet/v1/meetings/links/{meetingLinkName}/waiting-room (the `MeetUpdateV1MeetingsLinksWaitingRoom` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	MeetUpdateV1MeetingsLinksWaitingRoomWithBodyWithResponse(ctx context.Context, meetingLinkName string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*MeetUpdateV1MeetingsLinksWaitingRoomResponse, error)

	// MeetUpdateV1MeetingsLinksWaitingRoomWithResponse performs a PUT /meet/v1/meetings/links/{meetingLinkName}/waiting-room (the `MeetUpdateV1MeetingsLinksWaitingRoom` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	MeetUpdateV1MeetingsLinksWaitingRoomWithResponse(ctx context.Context, meetingLinkName string, body MeetUpdateV1MeetingsLinksWaitingRoomJSONRequestBody, reqEditors ...RequestEditorFn) (*MeetUpdateV1MeetingsLinksWaitingRoomResponse, error)

	// MeetUpdateV1MeetingsNameWithBodyWithResponse performs a PUT /meet/v1/meetings/{meetingId}/name (the `MeetUpdateV1MeetingsName` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	MeetUpdateV1MeetingsNameWithBodyWithResponse(ctx context.Context, meetingId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*MeetUpdateV1MeetingsNameResponse, error)

	// MeetUpdateV1MeetingsNameWithResponse performs a PUT /meet/v1/meetings/{meetingId}/name (the `MeetUpdateV1MeetingsName` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	MeetUpdateV1MeetingsNameWithResponse(ctx context.Context, meetingId string, body MeetUpdateV1MeetingsNameJSONRequestBody, reqEditors ...RequestEditorFn) (*MeetUpdateV1MeetingsNameResponse, error)

	// MeetUpdateV1MeetingsScheduleWithBodyWithResponse performs a PUT /meet/v1/meetings/{meetingId}/schedule (the `MeetUpdateV1MeetingsSchedule` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	MeetUpdateV1MeetingsScheduleWithBodyWithResponse(ctx context.Context, meetingId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*MeetUpdateV1MeetingsScheduleResponse, error)

	// MeetUpdateV1MeetingsScheduleWithResponse performs a PUT /meet/v1/meetings/{meetingId}/schedule (the `MeetUpdateV1MeetingsSchedule` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	MeetUpdateV1MeetingsScheduleWithResponse(ctx context.Context, meetingId string, body MeetUpdateV1MeetingsScheduleJSONRequestBody, reqEditors ...RequestEditorFn) (*MeetUpdateV1MeetingsScheduleResponse, error)
}

type MeetCreateV1MeetingsLinksFeedbackResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r MeetCreateV1MeetingsLinksFeedbackResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r MeetCreateV1MeetingsLinksFeedbackResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r MeetCreateV1MeetingsLinksFeedbackResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r MeetCreateV1MeetingsLinksFeedbackResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type MeetCreateV1MeetingsLinksLockResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r MeetCreateV1MeetingsLinksLockResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r MeetCreateV1MeetingsLinksLockResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r MeetCreateV1MeetingsLinksLockResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r MeetCreateV1MeetingsLinksLockResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type MeetCreateV1MeetingsLinksUnlockResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r MeetCreateV1MeetingsLinksUnlockResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r MeetCreateV1MeetingsLinksUnlockResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r MeetCreateV1MeetingsLinksUnlockResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r MeetCreateV1MeetingsLinksUnlockResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type MeetUpdateV1MeetingsLinksWaitingRoomResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r MeetUpdateV1MeetingsLinksWaitingRoomResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r MeetUpdateV1MeetingsLinksWaitingRoomResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r MeetUpdateV1MeetingsLinksWaitingRoomResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r MeetUpdateV1MeetingsLinksWaitingRoomResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type MeetUpdateV1MeetingsNameResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r MeetUpdateV1MeetingsNameResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r MeetUpdateV1MeetingsNameResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r MeetUpdateV1MeetingsNameResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r MeetUpdateV1MeetingsNameResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type MeetUpdateV1MeetingsScheduleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r MeetUpdateV1MeetingsScheduleResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r MeetUpdateV1MeetingsScheduleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r MeetUpdateV1MeetingsScheduleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r MeetUpdateV1MeetingsScheduleResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// MeetCreateV1MeetingsLinksFeedbackWithBodyWithResponse performs a POST /meet/v1/meetings/links/{meetingLinkName}/feedback (the `MeetCreateV1MeetingsLinksFeedback` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) MeetCreateV1MeetingsLinksFeedbackWithBodyWithResponse(ctx context.Context, meetingLinkName string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*MeetCreateV1MeetingsLinksFeedbackResponse, error) {
	rsp, err := c.MeetCreateV1MeetingsLinksFeedbackWithBody(ctx, meetingLinkName, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMeetCreateV1MeetingsLinksFeedbackResponse(rsp)
}

// MeetCreateV1MeetingsLinksFeedbackWithResponse performs a POST /meet/v1/meetings/links/{meetingLinkName}/feedback (the `MeetCreateV1MeetingsLinksFeedback` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) MeetCreateV1MeetingsLinksFeedbackWithResponse(ctx context.Context, meetingLinkName string, body MeetCreateV1MeetingsLinksFeedbackJSONRequestBody, reqEditors ...RequestEditorFn) (*MeetCreateV1MeetingsLinksFeedbackResponse, error) {
	rsp, err := c.MeetCreateV1MeetingsLinksFeedback(ctx, meetingLinkName, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMeetCreateV1MeetingsLinksFeedbackResponse(rsp)
}

// MeetCreateV1MeetingsLinksLockWithBodyWithResponse performs a POST /meet/v1/meetings/links/{meetingLinkName}/lock (the `MeetCreateV1MeetingsLinksLock` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) MeetCreateV1MeetingsLinksLockWithBodyWithResponse(ctx context.Context, meetingLinkName string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*MeetCreateV1MeetingsLinksLockResponse, error) {
	rsp, err := c.MeetCreateV1MeetingsLinksLockWithBody(ctx, meetingLinkName, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMeetCreateV1MeetingsLinksLockResponse(rsp)
}

// MeetCreateV1MeetingsLinksLockWithResponse performs a POST /meet/v1/meetings/links/{meetingLinkName}/lock (the `MeetCreateV1MeetingsLinksLock` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) MeetCreateV1MeetingsLinksLockWithResponse(ctx context.Context, meetingLinkName string, body MeetCreateV1MeetingsLinksLockJSONRequestBody, reqEditors ...RequestEditorFn) (*MeetCreateV1MeetingsLinksLockResponse, error) {
	rsp, err := c.MeetCreateV1MeetingsLinksLock(ctx, meetingLinkName, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMeetCreateV1MeetingsLinksLockResponse(rsp)
}

// MeetCreateV1MeetingsLinksUnlockWithBodyWithResponse performs a POST /meet/v1/meetings/links/{meetingLinkName}/unlock (the `MeetCreateV1MeetingsLinksUnlock` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) MeetCreateV1MeetingsLinksUnlockWithBodyWithResponse(ctx context.Context, meetingLinkName string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*MeetCreateV1MeetingsLinksUnlockResponse, error) {
	rsp, err := c.MeetCreateV1MeetingsLinksUnlockWithBody(ctx, meetingLinkName, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMeetCreateV1MeetingsLinksUnlockResponse(rsp)
}

// MeetCreateV1MeetingsLinksUnlockWithResponse performs a POST /meet/v1/meetings/links/{meetingLinkName}/unlock (the `MeetCreateV1MeetingsLinksUnlock` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) MeetCreateV1MeetingsLinksUnlockWithResponse(ctx context.Context, meetingLinkName string, body MeetCreateV1MeetingsLinksUnlockJSONRequestBody, reqEditors ...RequestEditorFn) (*MeetCreateV1MeetingsLinksUnlockResponse, error) {
	rsp, err := c.MeetCreateV1MeetingsLinksUnlock(ctx, meetingLinkName, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMeetCreateV1MeetingsLinksUnlockResponse(rsp)
}

// MeetUpdateV1MeetingsLinksWaitingRoomWithBodyWithResponse performs a PUT /meet/v1/meetings/links/{meetingLinkName}/waiting-room (the `MeetUpdateV1MeetingsLinksWaitingRoom` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) MeetUpdateV1MeetingsLinksWaitingRoomWithBodyWithResponse(ctx context.Context, meetingLinkName string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*MeetUpdateV1MeetingsLinksWaitingRoomResponse, error) {
	rsp, err := c.MeetUpdateV1MeetingsLinksWaitingRoomWithBody(ctx, meetingLinkName, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMeetUpdateV1MeetingsLinksWaitingRoomResponse(rsp)
}

// MeetUpdateV1MeetingsLinksWaitingRoomWithResponse performs a PUT /meet/v1/meetings/links/{meetingLinkName}/waiting-room (the `MeetUpdateV1MeetingsLinksWaitingRoom` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) MeetUpdateV1MeetingsLinksWaitingRoomWithResponse(ctx context.Context, meetingLinkName string, body MeetUpdateV1MeetingsLinksWaitingRoomJSONRequestBody, reqEditors ...RequestEditorFn) (*MeetUpdateV1MeetingsLinksWaitingRoomResponse, error) {
	rsp, err := c.MeetUpdateV1MeetingsLinksWaitingRoom(ctx, meetingLinkName, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMeetUpdateV1MeetingsLinksWaitingRoomResponse(rsp)
}

// MeetUpdateV1MeetingsNameWithBodyWithResponse performs a PUT /meet/v1/meetings/{meetingId}/name (the `MeetUpdateV1MeetingsName` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) MeetUpdateV1MeetingsNameWithBodyWithResponse(ctx context.Context, meetingId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*MeetUpdateV1MeetingsNameResponse, error) {
	rsp, err := c.MeetUpdateV1MeetingsNameWithBody(ctx, meetingId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMeetUpdateV1MeetingsNameResponse(rsp)
}

// MeetUpdateV1MeetingsNameWithResponse performs a PUT /meet/v1/meetings/{meetingId}/name (the `MeetUpdateV1MeetingsName` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) MeetUpdateV1MeetingsNameWithResponse(ctx context.Context, meetingId string, body MeetUpdateV1MeetingsNameJSONRequestBody, reqEditors ...RequestEditorFn) (*MeetUpdateV1MeetingsNameResponse, error) {
	rsp, err := c.MeetUpdateV1MeetingsName(ctx, meetingId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMeetUpdateV1MeetingsNameResponse(rsp)
}

// MeetUpdateV1MeetingsScheduleWithBodyWithResponse performs a PUT /meet/v1/meetings/{meetingId}/schedule (the `MeetUpdateV1MeetingsSchedule` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) MeetUpdateV1MeetingsScheduleWithBodyWithResponse(ctx context.Context, meetingId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*MeetUpdateV1MeetingsScheduleResponse, error) {
	rsp, err := c.MeetUpdateV1MeetingsScheduleWithBody(ctx, meetingId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMeetUpdateV1MeetingsScheduleResponse(rsp)
}

// MeetUpdateV1MeetingsScheduleWithResponse performs a PUT /meet/v1/meetings/{meetingId}/schedule (the `MeetUpdateV1MeetingsSchedule` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) MeetUpdateV1MeetingsScheduleWithResponse(ctx context.Context, meetingId string, body MeetUpdateV1MeetingsScheduleJSONRequestBody, reqEditors ...RequestEditorFn) (*MeetUpdateV1MeetingsScheduleResponse, error) {
	rsp, err := c.MeetUpdateV1MeetingsSchedule(ctx, meetingId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMeetUpdateV1MeetingsScheduleResponse(rsp)
}

// ParseMeetCreateV1MeetingsLinksFeedbackResponse parses an HTTP response from a MeetCreateV1MeetingsLinksFeedbackWithResponse call
func ParseMeetCreateV1MeetingsLinksFeedbackResponse(rsp *http.Response) (*MeetCreateV1MeetingsLinksFeedbackResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &MeetCreateV1MeetingsLinksFeedbackResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseMeetCreateV1MeetingsLinksLockResponse parses an HTTP response from a MeetCreateV1MeetingsLinksLockWithResponse call
func ParseMeetCreateV1MeetingsLinksLockResponse(rsp *http.Response) (*MeetCreateV1MeetingsLinksLockResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &MeetCreateV1MeetingsLinksLockResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseMeetCreateV1MeetingsLinksUnlockResponse parses an HTTP response from a MeetCreateV1MeetingsLinksUnlockWithResponse call
func ParseMeetCreateV1MeetingsLinksUnlockResponse(rsp *http.Response) (*MeetCreateV1MeetingsLinksUnlockResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &MeetCreateV1MeetingsLinksUnlockResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseMeetUpdateV1MeetingsLinksWaitingRoomResponse parses an HTTP response from a MeetUpdateV1MeetingsLinksWaitingRoomWithResponse call
func ParseMeetUpdateV1MeetingsLinksWaitingRoomResponse(rsp *http.Response) (*MeetUpdateV1MeetingsLinksWaitingRoomResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &MeetUpdateV1MeetingsLinksWaitingRoomResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseMeetUpdateV1MeetingsNameResponse parses an HTTP response from a MeetUpdateV1MeetingsNameWithResponse call
func ParseMeetUpdateV1MeetingsNameResponse(rsp *http.Response) (*MeetUpdateV1MeetingsNameResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &MeetUpdateV1MeetingsNameResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseMeetUpdateV1MeetingsScheduleResponse parses an HTTP response from a MeetUpdateV1MeetingsScheduleWithResponse call
func ParseMeetUpdateV1MeetingsScheduleResponse(rsp *http.Response) (*MeetUpdateV1MeetingsScheduleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &MeetUpdateV1MeetingsScheduleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
