// Package meetapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package meetapi

// MeetCreateV1MeetingsLinksFeedbackJSONBody defines parameters for MeetCreateV1MeetingsLinksFeedback.
type MeetCreateV1MeetingsLinksFeedbackJSONBody struct {
	Feedback *string `json:"Feedback,omitempty"`
	Score    *string `json:"Score,omitempty"`
}

// MeetCreateV1MeetingsLinksLockJSONBody defines parameters for MeetCreateV1MeetingsLinksLock.
type MeetCreateV1MeetingsLinksLockJSONBody struct {
	AccessToken *string `json:"AccessToken,omitempty"`
}

// MeetCreateV1MeetingsLinksUnlockJSONBody defines parameters for MeetCreateV1MeetingsLinksUnlock.
type MeetCreateV1MeetingsLinksUnlockJSONBody struct {
	AccessToken *string `json:"AccessToken,omitempty"`
}

// MeetUpdateV1MeetingsLinksWaitingRoomJSONBody defines parameters for MeetUpdateV1MeetingsLinksWaitingRoom.
type MeetUpdateV1MeetingsLinksWaitingRoomJSONBody struct {
	WaitingRoom *string `json:"WaitingRoom,omitempty"`
}

// MeetUpdateV1MeetingsNameJSONBody defines parameters for MeetUpdateV1MeetingsName.
type MeetUpdateV1MeetingsNameJSONBody struct {
	Name *string `json:"Name,omitempty"`
}

// MeetUpdateV1MeetingsScheduleJSONBody defines parameters for MeetUpdateV1MeetingsSchedule.
type MeetUpdateV1MeetingsScheduleJSONBody struct {
	EndTime   *string `json:"EndTime,omitempty"`
	RRule     *string `json:"RRule,omitempty"`
	StartTime *string `json:"StartTime,omitempty"`
	Timezone  *string `json:"Timezone,omitempty"`
}

// MeetCreateV1MeetingsLinksFeedbackJSONRequestBody defines body for MeetCreateV1MeetingsLinksFeedback for application/json ContentType.
type MeetCreateV1MeetingsLinksFeedbackJSONRequestBody MeetCreateV1MeetingsLinksFeedbackJSONBody

// MeetCreateV1MeetingsLinksLockJSONRequestBody defines body for MeetCreateV1MeetingsLinksLock for application/json ContentType.
type MeetCreateV1MeetingsLinksLockJSONRequestBody MeetCreateV1MeetingsLinksLockJSONBody

// MeetCreateV1MeetingsLinksUnlockJSONRequestBody defines body for MeetCreateV1MeetingsLinksUnlock for application/json ContentType.
type MeetCreateV1MeetingsLinksUnlockJSONRequestBody MeetCreateV1MeetingsLinksUnlockJSONBody

// MeetUpdateV1MeetingsLinksWaitingRoomJSONRequestBody defines body for MeetUpdateV1MeetingsLinksWaitingRoom for application/json ContentType.
type MeetUpdateV1MeetingsLinksWaitingRoomJSONRequestBody MeetUpdateV1MeetingsLinksWaitingRoomJSONBody

// MeetUpdateV1MeetingsNameJSONRequestBody defines body for MeetUpdateV1MeetingsName for application/json ContentType.
type MeetUpdateV1MeetingsNameJSONRequestBody MeetUpdateV1MeetingsNameJSONBody

// MeetUpdateV1MeetingsScheduleJSONRequestBody defines body for MeetUpdateV1MeetingsSchedule for application/json ContentType.
type MeetUpdateV1MeetingsScheduleJSONRequestBody MeetUpdateV1MeetingsScheduleJSONBody
