// Package coreapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package coreapi

// Defines values for CoreCreateV4GroupsJSONBodyGroupVisibility.
const (
	CoreCreateV4GroupsJSONBodyGroupVisibilityN0 CoreCreateV4GroupsJSONBodyGroupVisibility = 0
	CoreCreateV4GroupsJSONBodyGroupVisibilityN1 CoreCreateV4GroupsJSONBodyGroupVisibility = 1
)

// Valid indicates whether the value is a known member of the CoreCreateV4GroupsJSONBodyGroupVisibility enum.
func (e CoreCreateV4GroupsJSONBodyGroupVisibility) Valid() bool {
	switch e {
	case CoreCreateV4GroupsJSONBodyGroupVisibilityN0:
		return true
	case CoreCreateV4GroupsJSONBodyGroupVisibilityN1:
		return true
	default:
		return false
	}
}

// Defines values for CoreCreateV4GroupsJSONBodyPermissions.
const (
	CoreCreateV4GroupsJSONBodyPermissionsN0 CoreCreateV4GroupsJSONBodyPermissions = 0
	CoreCreateV4GroupsJSONBodyPermissionsN1 CoreCreateV4GroupsJSONBodyPermissions = 1
	CoreCreateV4GroupsJSONBodyPermissionsN2 CoreCreateV4GroupsJSONBodyPermissions = 2
	CoreCreateV4GroupsJSONBodyPermissionsN3 CoreCreateV4GroupsJSONBodyPermissions = 3
)

// Valid indicates whether the value is a known member of the CoreCreateV4GroupsJSONBodyPermissions enum.
func (e CoreCreateV4GroupsJSONBodyPermissions) Valid() bool {
	switch e {
	case CoreCreateV4GroupsJSONBodyPermissionsN0:
		return true
	case CoreCreateV4GroupsJSONBodyPermissionsN1:
		return true
	case CoreCreateV4GroupsJSONBodyPermissionsN2:
		return true
	case CoreCreateV4GroupsJSONBodyPermissionsN3:
		return true
	default:
		return false
	}
}

// Defines values for CoreCreateV4GroupsMembersJSONBodyType.
const (
	CoreCreateV4GroupsMembersJSONBodyTypeN0 CoreCreateV4GroupsMembersJSONBodyType = 0
	CoreCreateV4GroupsMembersJSONBodyTypeN1 CoreCreateV4GroupsMembersJSONBodyType = 1
	CoreCreateV4GroupsMembersJSONBodyTypeN2 CoreCreateV4GroupsMembersJSONBodyType = 2
)

// Valid indicates whether the value is a known member of the CoreCreateV4GroupsMembersJSONBodyType enum.
func (e CoreCreateV4GroupsMembersJSONBodyType) Valid() bool {
	switch e {
	case CoreCreateV4GroupsMembersJSONBodyTypeN0:
		return true
	case CoreCreateV4GroupsMembersJSONBodyTypeN1:
		return true
	case CoreCreateV4GroupsMembersJSONBodyTypeN2:
		return true
	default:
		return false
	}
}

// Defines values for CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberState.
const (
	CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberStateN0 CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberState = 0
	CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberStateN1 CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberState = 1
	CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberStateN2 CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberState = 2
	CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberStateN3 CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberState = 3
	CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberStateN4 CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberState = 4
)

// Valid indicates whether the value is a known member of the CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberState enum.
func (e CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberState) Valid() bool {
	switch e {
	case CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberStateN0:
		return true
	case CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberStateN1:
		return true
	case CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberStateN2:
		return true
	case CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberStateN3:
		return true
	case CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberStateN4:
		return true
	default:
		return false
	}
}

// Defines values for CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberType.
const (
	CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberTypeN0 CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberType = 0
	CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberTypeN1 CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberType = 1
	CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberTypeN2 CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberType = 2
)

// Valid indicates whether the value is a known member of the CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberType enum.
func (e CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberType) Valid() bool {
	switch e {
	case CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberTypeN0:
		return true
	case CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberTypeN1:
		return true
	case CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberTypeN2:
		return true
	default:
		return false
	}
}

// Defines values for CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsState.
const (
	CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsStateN0 CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsState = 0
	CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsStateN1 CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsState = 1
	CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsStateN2 CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsState = 2
	CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsStateN3 CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsState = 3
	CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsStateN4 CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsState = 4
)

// Valid indicates whether the value is a known member of the CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsState enum.
func (e CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsState) Valid() bool {
	switch e {
	case CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsStateN0:
		return true
	case CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsStateN1:
		return true
	case CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsStateN2:
		return true
	case CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsStateN3:
		return true
	case CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsStateN4:
		return true
	default:
		return false
	}
}

// Defines values for CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsType.
const (
	CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsTypeN0 CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsType = 0
	CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsTypeN1 CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsType = 1
	CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsTypeN2 CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsType = 2
)

// Valid indicates whether the value is a known member of the CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsType enum.
func (e CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsType) Valid() bool {
	switch e {
	case CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsTypeN0:
		return true
	case CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsTypeN1:
		return true
	case CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsTypeN2:
		return true
	default:
		return false
	}
}

// Defines values for CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsState.
const (
	CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsStateN0 CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsState = 0
	CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsStateN1 CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsState = 1
	CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsStateN2 CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsState = 2
	CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsStateN3 CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsState = 3
	CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsStateN4 CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsState = 4
)

// Valid indicates whether the value is a known member of the CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsState enum.
func (e CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsState) Valid() bool {
	switch e {
	case CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsStateN0:
		return true
	case CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsStateN1:
		return true
	case CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsStateN2:
		return true
	case CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsStateN3:
		return true
	case CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsStateN4:
		return true
	default:
		return false
	}
}

// Defines values for CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsType.
const (
	CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsTypeN0 CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsType = 0
	CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsTypeN1 CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsType = 1
	CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsTypeN2 CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsType = 2
)

// Valid indicates whether the value is a known member of the CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsType enum.
func (e CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsType) Valid() bool {
	switch e {
	case CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsTypeN0:
		return true
	case CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsTypeN1:
		return true
	case CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsTypeN2:
		return true
	default:
		return false
	}
}

// Defines values for CoreGetV4GroupsMember200JSONResponseBodyGroupMemberState.
const (
	CoreGetV4GroupsMember200JSONResponseBodyGroupMemberStateN0 CoreGetV4GroupsMember200JSONResponseBodyGroupMemberState = 0
	CoreGetV4GroupsMember200JSONResponseBodyGroupMemberStateN1 CoreGetV4GroupsMember200JSONResponseBodyGroupMemberState = 1
	CoreGetV4GroupsMember200JSONResponseBodyGroupMemberStateN2 CoreGetV4GroupsMember200JSONResponseBodyGroupMemberState = 2
	CoreGetV4GroupsMember200JSONResponseBodyGroupMemberStateN3 CoreGetV4GroupsMember200JSONResponseBodyGroupMemberState = 3
	CoreGetV4GroupsMember200JSONResponseBodyGroupMemberStateN4 CoreGetV4GroupsMember200JSONResponseBodyGroupMemberState = 4
)

// Valid indicates whether the value is a known member of the CoreGetV4GroupsMember200JSONResponseBodyGroupMemberState enum.
func (e CoreGetV4GroupsMember200JSONResponseBodyGroupMemberState) Valid() bool {
	switch e {
	case CoreGetV4GroupsMember200JSONResponseBodyGroupMemberStateN0:
		return true
	case CoreGetV4GroupsMember200JSONResponseBodyGroupMemberStateN1:
		return true
	case CoreGetV4GroupsMember200JSONResponseBodyGroupMemberStateN2:
		return true
	case CoreGetV4GroupsMember200JSONResponseBodyGroupMemberStateN3:
		return true
	case CoreGetV4GroupsMember200JSONResponseBodyGroupMemberStateN4:
		return true
	default:
		return false
	}
}

// Defines values for CoreGetV4GroupsMember200JSONResponseBodyGroupMemberType.
const (
	CoreGetV4GroupsMember200JSONResponseBodyGroupMemberTypeN0 CoreGetV4GroupsMember200JSONResponseBodyGroupMemberType = 0
	CoreGetV4GroupsMember200JSONResponseBodyGroupMemberTypeN1 CoreGetV4GroupsMember200JSONResponseBodyGroupMemberType = 1
	CoreGetV4GroupsMember200JSONResponseBodyGroupMemberTypeN2 CoreGetV4GroupsMember200JSONResponseBodyGroupMemberType = 2
)

// Valid indicates whether the value is a known member of the CoreGetV4GroupsMember200JSONResponseBodyGroupMemberType enum.
func (e CoreGetV4GroupsMember200JSONResponseBodyGroupMemberType) Valid() bool {
	switch e {
	case CoreGetV4GroupsMember200JSONResponseBodyGroupMemberTypeN0:
		return true
	case CoreGetV4GroupsMember200JSONResponseBodyGroupMemberTypeN1:
		return true
	case CoreGetV4GroupsMember200JSONResponseBodyGroupMemberTypeN2:
		return true
	default:
		return false
	}
}

// Defines values for CoreUpdateV4GroupJSONBodyGroupVisibility.
const (
	CoreUpdateV4GroupJSONBodyGroupVisibilityN0 CoreUpdateV4GroupJSONBodyGroupVisibility = 0
	CoreUpdateV4GroupJSONBodyGroupVisibilityN1 CoreUpdateV4GroupJSONBodyGroupVisibility = 1
)

// Valid indicates whether the value is a known member of the CoreUpdateV4GroupJSONBodyGroupVisibility enum.
func (e CoreUpdateV4GroupJSONBodyGroupVisibility) Valid() bool {
	switch e {
	case CoreUpdateV4GroupJSONBodyGroupVisibilityN0:
		return true
	case CoreUpdateV4GroupJSONBodyGroupVisibilityN1:
		return true
	default:
		return false
	}
}

// Defines values for CoreUpdateV4GroupJSONBodyPermissions.
const (
	CoreUpdateV4GroupJSONBodyPermissionsN0 CoreUpdateV4GroupJSONBodyPermissions = 0
	CoreUpdateV4GroupJSONBodyPermissionsN1 CoreUpdateV4GroupJSONBodyPermissions = 1
	CoreUpdateV4GroupJSONBodyPermissionsN2 CoreUpdateV4GroupJSONBodyPermissions = 2
	CoreUpdateV4GroupJSONBodyPermissionsN3 CoreUpdateV4GroupJSONBodyPermissions = 3
)

// Valid indicates whether the value is a known member of the CoreUpdateV4GroupJSONBodyPermissions enum.
func (e CoreUpdateV4GroupJSONBodyPermissions) Valid() bool {
	switch e {
	case CoreUpdateV4GroupJSONBodyPermissionsN0:
		return true
	case CoreUpdateV4GroupJSONBodyPermissionsN1:
		return true
	case CoreUpdateV4GroupJSONBodyPermissionsN2:
		return true
	case CoreUpdateV4GroupJSONBodyPermissionsN3:
		return true
	default:
		return false
	}
}

// Defines values for CoreListV4GroupsMembers200JSONResponseBodyMembersState.
const (
	CoreListV4GroupsMembers200JSONResponseBodyMembersStateN0 CoreListV4GroupsMembers200JSONResponseBodyMembersState = 0
	CoreListV4GroupsMembers200JSONResponseBodyMembersStateN1 CoreListV4GroupsMembers200JSONResponseBodyMembersState = 1
	CoreListV4GroupsMembers200JSONResponseBodyMembersStateN2 CoreListV4GroupsMembers200JSONResponseBodyMembersState = 2
	CoreListV4GroupsMembers200JSONResponseBodyMembersStateN3 CoreListV4GroupsMembers200JSONResponseBodyMembersState = 3
	CoreListV4GroupsMembers200JSONResponseBodyMembersStateN4 CoreListV4GroupsMembers200JSONResponseBodyMembersState = 4
)

// Valid indicates whether the value is a known member of the CoreListV4GroupsMembers200JSONResponseBodyMembersState enum.
func (e CoreListV4GroupsMembers200JSONResponseBodyMembersState) Valid() bool {
	switch e {
	case CoreListV4GroupsMembers200JSONResponseBodyMembersStateN0:
		return true
	case CoreListV4GroupsMembers200JSONResponseBodyMembersStateN1:
		return true
	case CoreListV4GroupsMembers200JSONResponseBodyMembersStateN2:
		return true
	case CoreListV4GroupsMembers200JSONResponseBodyMembersStateN3:
		return true
	case CoreListV4GroupsMembers200JSONResponseBodyMembersStateN4:
		return true
	default:
		return false
	}
}

// Defines values for CoreListV4GroupsMembers200JSONResponseBodyMembersType.
const (
	CoreListV4GroupsMembers200JSONResponseBodyMembersTypeN0 CoreListV4GroupsMembers200JSONResponseBodyMembersType = 0
	CoreListV4GroupsMembers200JSONResponseBodyMembersTypeN1 CoreListV4GroupsMembers200JSONResponseBodyMembersType = 1
	CoreListV4GroupsMembers200JSONResponseBodyMembersTypeN2 CoreListV4GroupsMembers200JSONResponseBodyMembersType = 2
)

// Valid indicates whether the value is a known member of the CoreListV4GroupsMembers200JSONResponseBodyMembersType enum.
func (e CoreListV4GroupsMembers200JSONResponseBodyMembersType) Valid() bool {
	switch e {
	case CoreListV4GroupsMembers200JSONResponseBodyMembersTypeN0:
		return true
	case CoreListV4GroupsMembers200JSONResponseBodyMembersTypeN1:
		return true
	case CoreListV4GroupsMembers200JSONResponseBodyMembersTypeN2:
		return true
	default:
		return false
	}
}

// Defines values for CoreCreateV4MembersJSONBodyMaxAI.
const (
	CoreCreateV4MembersJSONBodyMaxAIN0 CoreCreateV4MembersJSONBodyMaxAI = 0
	CoreCreateV4MembersJSONBodyMaxAIN1 CoreCreateV4MembersJSONBodyMaxAI = 1
)

// Valid indicates whether the value is a known member of the CoreCreateV4MembersJSONBodyMaxAI enum.
func (e CoreCreateV4MembersJSONBodyMaxAI) Valid() bool {
	switch e {
	case CoreCreateV4MembersJSONBodyMaxAIN0:
		return true
	case CoreCreateV4MembersJSONBodyMaxAIN1:
		return true
	default:
		return false
	}
}

// Defines values for CoreCreateV4MembersJSONBodyMaxLumo.
const (
	CoreCreateV4MembersJSONBodyMaxLumoN0 CoreCreateV4MembersJSONBodyMaxLumo = 0
	CoreCreateV4MembersJSONBodyMaxLumoN1 CoreCreateV4MembersJSONBodyMaxLumo = 1
)

// Valid indicates whether the value is a known member of the CoreCreateV4MembersJSONBodyMaxLumo enum.
func (e CoreCreateV4MembersJSONBodyMaxLumo) Valid() bool {
	switch e {
	case CoreCreateV4MembersJSONBodyMaxLumoN0:
		return true
	case CoreCreateV4MembersJSONBodyMaxLumoN1:
		return true
	default:
		return false
	}
}

// Defines values for CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONBodyPermissions.
const (
	CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONBodyPermissionsN2 CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONBodyPermissions = 2
	CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONBodyPermissionsN8 CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONBodyPermissions = 8
)

// Valid indicates whether the value is a known member of the CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONBodyPermissions enum.
func (e CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONBodyPermissions) Valid() bool {
	switch e {
	case CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONBodyPermissionsN2:
		return true
	case CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONBodyPermissionsN8:
		return true
	default:
		return false
	}
}

// Defines values for CoreCreateV4MembersInvitationsJSONBodyMaxAI.
const (
	CoreCreateV4MembersInvitationsJSONBodyMaxAIN0 CoreCreateV4MembersInvitationsJSONBodyMaxAI = 0
	CoreCreateV4MembersInvitationsJSONBodyMaxAIN1 CoreCreateV4MembersInvitationsJSONBodyMaxAI = 1
)

// Valid indicates whether the value is a known member of the CoreCreateV4MembersInvitationsJSONBodyMaxAI enum.
func (e CoreCreateV4MembersInvitationsJSONBodyMaxAI) Valid() bool {
	switch e {
	case CoreCreateV4MembersInvitationsJSONBodyMaxAIN0:
		return true
	case CoreCreateV4MembersInvitationsJSONBodyMaxAIN1:
		return true
	default:
		return false
	}
}

// Defines values for CoreCreateV4MembersInvitationsJSONBodyMaxLumo.
const (
	CoreCreateV4MembersInvitationsJSONBodyMaxLumoN0 CoreCreateV4MembersInvitationsJSONBodyMaxLumo = 0
	CoreCreateV4MembersInvitationsJSONBodyMaxLumoN1 CoreCreateV4MembersInvitationsJSONBodyMaxLumo = 1
)

// Valid indicates whether the value is a known member of the CoreCreateV4MembersInvitationsJSONBodyMaxLumo enum.
func (e CoreCreateV4MembersInvitationsJSONBodyMaxLumo) Valid() bool {
	switch e {
	case CoreCreateV4MembersInvitationsJSONBodyMaxLumoN0:
		return true
	case CoreCreateV4MembersInvitationsJSONBodyMaxLumoN1:
		return true
	default:
		return false
	}
}

// Defines values for CoreUpdateV4MembersPermissionsJSONBodyAction.
const (
	CoreUpdateV4MembersPermissionsJSONBodyActionN0 CoreUpdateV4MembersPermissionsJSONBodyAction = 0
	CoreUpdateV4MembersPermissionsJSONBodyActionN1 CoreUpdateV4MembersPermissionsJSONBodyAction = 1
)

// Valid indicates whether the value is a known member of the CoreUpdateV4MembersPermissionsJSONBodyAction enum.
func (e CoreUpdateV4MembersPermissionsJSONBodyAction) Valid() bool {
	switch e {
	case CoreUpdateV4MembersPermissionsJSONBodyActionN0:
		return true
	case CoreUpdateV4MembersPermissionsJSONBodyActionN1:
		return true
	default:
		return false
	}
}

// Defines values for CoreUpdateV4MembersPermissionsJSONBodyPermission.
const (
	CoreUpdateV4MembersPermissionsJSONBodyPermissionN1 CoreUpdateV4MembersPermissionsJSONBodyPermission = 1
)

// Valid indicates whether the value is a known member of the CoreUpdateV4MembersPermissionsJSONBodyPermission enum.
func (e CoreUpdateV4MembersPermissionsJSONBodyPermission) Valid() bool {
	switch e {
	case CoreUpdateV4MembersPermissionsJSONBodyPermissionN1:
		return true
	default:
		return false
	}
}

// Defines values for CoreUpdateV4MembersAiJSONBodyMaxAI.
const (
	CoreUpdateV4MembersAiJSONBodyMaxAIN0 CoreUpdateV4MembersAiJSONBodyMaxAI = 0
	CoreUpdateV4MembersAiJSONBodyMaxAIN1 CoreUpdateV4MembersAiJSONBodyMaxAI = 1
)

// Valid indicates whether the value is a known member of the CoreUpdateV4MembersAiJSONBodyMaxAI enum.
func (e CoreUpdateV4MembersAiJSONBodyMaxAI) Valid() bool {
	switch e {
	case CoreUpdateV4MembersAiJSONBodyMaxAIN0:
		return true
	case CoreUpdateV4MembersAiJSONBodyMaxAIN1:
		return true
	default:
		return false
	}
}

// Defines values for CoreUpdateV4MembersLumoJSONBodyMaxLumo.
const (
	CoreUpdateV4MembersLumoJSONBodyMaxLumoN0 CoreUpdateV4MembersLumoJSONBodyMaxLumo = 0
	CoreUpdateV4MembersLumoJSONBodyMaxLumoN1 CoreUpdateV4MembersLumoJSONBodyMaxLumo = 1
)

// Valid indicates whether the value is a known member of the CoreUpdateV4MembersLumoJSONBodyMaxLumo enum.
func (e CoreUpdateV4MembersLumoJSONBodyMaxLumo) Valid() bool {
	switch e {
	case CoreUpdateV4MembersLumoJSONBodyMaxLumoN0:
		return true
	case CoreUpdateV4MembersLumoJSONBodyMaxLumoN1:
		return true
	default:
		return false
	}
}

// AuthDeleteV4Params defines parameters for AuthDeleteV4.
type AuthDeleteV4Params struct {
	AuthDevice *int `form:"AuthDevice,omitempty" json:"AuthDevice,omitempty"`
}

// CalendarCreateV1MembersJSONBody defines parameters for CalendarCreateV1Members.
type CalendarCreateV1MembersJSONBody struct {
	AddressID *string `json:"AddressID,omitempty"`
	Members   *string `json:"Members,omitempty"`
	Signature *string `json:"Signature,omitempty"`
}

// CoreCreateV4AuthJSONBody defines parameters for CoreCreateV4Auth.
type CoreCreateV4AuthJSONBody struct {
	// AuthenticationOptions The same AuthenticationOptions received as a challenge from the server
	AuthenticationOptions *string `json:"AuthenticationOptions,omitempty"`
	ClientEphemeral       *string `json:"ClientEphemeral,omitempty"`
	ClientProof           *string `json:"ClientProof,omitempty"`
	ClientSecret          *string `json:"ClientSecret,omitempty"`

	// CredentialID CredentialID used
	CredentialID      *[]string `json:"CredentialID,omitempty"`
	PersistentCookies *float32  `json:"PersistentCookies,omitempty"`
	SRPSession        *string   `json:"SRPSession,omitempty"`
	SSOResponseToken  *string   `json:"SSOResponseToken,omitempty"`
	Salt              *string   `json:"Salt,omitempty"`
	Signature         *string   `json:"Signature,omitempty"`
	TwoFactorCode     *string   `json:"TwoFactorCode,omitempty"`
	Username          *string   `json:"Username,omitempty"`
}

// CoreCreateV4Auth2faJSONBody defines parameters for CoreCreateV4Auth2fa.
type CoreCreateV4Auth2faJSONBody struct {
	TwoFactorCode *string `json:"TwoFactorCode,omitempty"`
}

// CoreCreateV4AuthCookiesJSONBody defines parameters for CoreCreateV4AuthCookies.
type CoreCreateV4AuthCookiesJSONBody struct {
	GrantType    *string `json:"GrantType,omitempty"`
	Persistent   *string `json:"Persistent,omitempty"`
	ResponseType *string `json:"ResponseType,omitempty"`
}

// CoreCreateV4AuthInfoJSONBody defines parameters for CoreCreateV4AuthInfo.
type CoreCreateV4AuthInfoJSONBody struct {
	Username *string `json:"Username,omitempty"`
}

// CoreCreateV4AuthJwtJSONBody defines parameters for CoreCreateV4AuthJwt.
type CoreCreateV4AuthJwtJSONBody struct {
	Token *string `json:"Token,omitempty"`
}

// CoreGetV4AuthSsoParams defines parameters for CoreGetV4AuthSso.
type CoreGetV4AuthSsoParams struct {
	FinalRedirectBaseUrl *string `form:"FinalRedirectBaseUrl,omitempty" json:"FinalRedirectBaseUrl,omitempty"`
}

// CoreCreateV4GroupsJSONBody defines parameters for CoreCreateV4Groups.
type CoreCreateV4GroupsJSONBody struct {
	Description      *string                                    `json:"Description,omitempty"`
	Email            *string                                    `json:"Email,omitempty"`
	Flags            *float32                                   `json:"Flags,omitempty"`
	GroupVisibility  *CoreCreateV4GroupsJSONBodyGroupVisibility `json:"GroupVisibility,omitempty"`
	MemberVisibility *float32                                   `json:"MemberVisibility,omitempty"`
	Name             *string                                    `json:"Name,omitempty"`
	Permissions      *CoreCreateV4GroupsJSONBodyPermissions     `json:"Permissions,omitempty"`
	GroupParams      *string                                    `json:"groupParams,omitempty"`
}

// CoreCreateV4GroupsJSONBodyGroupVisibility defines parameters for CoreCreateV4Groups.
type CoreCreateV4GroupsJSONBodyGroupVisibility int

// CoreCreateV4GroupsJSONBodyPermissions defines parameters for CoreCreateV4Groups.
type CoreCreateV4GroupsJSONBodyPermissions int

// CoreDeleteV4GroupsExternalParams defines parameters for CoreDeleteV4GroupsExternal.
type CoreDeleteV4GroupsExternalParams struct {
	Jwt     *string `form:"jwt,omitempty" json:"jwt,omitempty"`
	GroupID *string `form:"GroupID,omitempty" json:"GroupID,omitempty"`
}

// CoreUpdateV4GroupsExternalParams defines parameters for CoreUpdateV4GroupsExternal.
type CoreUpdateV4GroupsExternalParams struct {
	Jwt     *string `form:"jwt,omitempty" json:"jwt,omitempty"`
	GroupID *string `form:"GroupID,omitempty" json:"GroupID,omitempty"`
}

// CoreCreateV4GroupsMembersJSONBody defines parameters for CoreCreateV4GroupsMembers.
type CoreCreateV4GroupsMembersJSONBody struct {
	ActivationToken              *string `json:"ActivationToken,omitempty"`
	AddressSignaturePacket       *string `json:"AddressSignaturePacket,omitempty"`
	Email                        *string `json:"Email,omitempty"`
	GroupID                      *string `json:"GroupID,omitempty"`
	GroupMemberAddressPrivateKey *string `json:"GroupMemberAddressPrivateKey,omitempty"`
	ProxyInstances               *struct {
		GroupAddressKeyFingerprint       *string  `json:"GroupAddressKeyFingerprint,omitempty"`
		GroupMemberAddressKeyFingerprint *string  `json:"GroupMemberAddressKeyFingerprint,omitempty"`
		PgpVersion                       *float32 `json:"PgpVersion,omitempty"`
		ProxyParam                       *string  `json:"ProxyParam,omitempty"`
	} `json:"ProxyInstances,omitempty"`
	Signature *string                                `json:"Signature,omitempty"`
	Token     *string                                `json:"Token,omitempty"`
	Type      *CoreCreateV4GroupsMembersJSONBodyType `json:"Type,omitempty"`
}

// CoreCreateV4GroupsMembersJSONBodyType defines parameters for CoreCreateV4GroupsMembers.
type CoreCreateV4GroupsMembersJSONBodyType int

// CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberState defines parameters for CoreCreateV4GroupsMembers.
type CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberState int

// CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberType defines parameters for CoreCreateV4GroupsMembers.
type CoreCreateV4GroupsMembers200JSONResponseBodyGroupMemberType int

// CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsState defines parameters for CoreGetV4GroupsMembersExternal.
type CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsState int

// CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsType defines parameters for CoreGetV4GroupsMembersExternal.
type CoreGetV4GroupsMembersExternal200JSONResponseBodyMembershipsType int

// CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsState defines parameters for CoreListV4GroupsMembersInternal.
type CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsState int

// CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsType defines parameters for CoreListV4GroupsMembersInternal.
type CoreListV4GroupsMembersInternal200JSONResponseBodyMembershipsType int

// CoreGetV4GroupsMember200JSONResponseBodyGroupMemberState defines parameters for CoreGetV4GroupsMember.
type CoreGetV4GroupsMember200JSONResponseBodyGroupMemberState int

// CoreGetV4GroupsMember200JSONResponseBodyGroupMemberType defines parameters for CoreGetV4GroupsMember.
type CoreGetV4GroupsMember200JSONResponseBodyGroupMemberType int

// CoreUpdateV4GroupsMemberJSONBody defines parameters for CoreUpdateV4GroupsMember.
type CoreUpdateV4GroupsMemberJSONBody struct {
	GroupMemberParams *string `json:"groupMemberParams,omitempty"`
}

// CoreCreateV4GroupsOwnersAcceptJSONBody defines parameters for CoreCreateV4GroupsOwnersAccept.
type CoreCreateV4GroupsOwnersAcceptJSONBody struct {
	TokenKeyPacket       *string `json:"TokenKeyPacket,omitempty"`
	TokenSignaturePacket *string `json:"TokenSignaturePacket,omitempty"`
}

// CoreCreateV4GroupsOwnersAddJSONBody defines parameters for CoreCreateV4GroupsOwnersAdd.
type CoreCreateV4GroupsOwnersAddJSONBody struct {
	MemberID             *string `json:"MemberID,omitempty"`
	TokenKeyPacket       *string `json:"TokenKeyPacket,omitempty"`
	TokenSignaturePacket *string `json:"TokenSignaturePacket,omitempty"`
}

// CoreCreateV4GroupsOwnersInvitesJSONBody defines parameters for CoreCreateV4GroupsOwnersInvites.
type CoreCreateV4GroupsOwnersInvitesJSONBody struct {
	EncryptionAddress    *string `json:"EncryptionAddress,omitempty"`
	GroupMemberID        *string `json:"GroupMemberID,omitempty"`
	TokenKeyPacket       *string `json:"TokenKeyPacket,omitempty"`
	TokenSignaturePacket *string `json:"TokenSignaturePacket,omitempty"`
}

// CoreCreateV4GroupsUnsubscribeParams defines parameters for CoreCreateV4GroupsUnsubscribe.
type CoreCreateV4GroupsUnsubscribeParams struct {
	Jwt     *string `form:"jwt,omitempty" json:"jwt,omitempty"`
	GroupID *string `form:"GroupID,omitempty" json:"GroupID,omitempty"`
}

// CoreUpdateV4GroupJSONBody defines parameters for CoreUpdateV4Group.
type CoreUpdateV4GroupJSONBody struct {
	Description      *string                                   `json:"Description,omitempty"`
	Email            *string                                   `json:"Email,omitempty"`
	Flags            *float32                                  `json:"Flags,omitempty"`
	GroupVisibility  *CoreUpdateV4GroupJSONBodyGroupVisibility `json:"GroupVisibility,omitempty"`
	MemberVisibility *float32                                  `json:"MemberVisibility,omitempty"`
	Name             *string                                   `json:"Name,omitempty"`
	Permissions      *CoreUpdateV4GroupJSONBodyPermissions     `json:"Permissions,omitempty"`
	GroupParams      *string                                   `json:"groupParams,omitempty"`
}

// CoreUpdateV4GroupJSONBodyGroupVisibility defines parameters for CoreUpdateV4Group.
type CoreUpdateV4GroupJSONBodyGroupVisibility int

// CoreUpdateV4GroupJSONBodyPermissions defines parameters for CoreUpdateV4Group.
type CoreUpdateV4GroupJSONBodyPermissions int

// CoreListV4GroupsMembersParams defines parameters for CoreListV4GroupsMembers.
type CoreListV4GroupsMembersParams struct {
	PageSize *string `form:"PageSize,omitempty" json:"PageSize,omitempty"`
	Page     *string `form:"Page,omitempty" json:"Page,omitempty"`
}

// CoreListV4GroupsMembers200JSONResponseBodyMembersState defines parameters for CoreListV4GroupsMembers.
type CoreListV4GroupsMembers200JSONResponseBodyMembersState int

// CoreListV4GroupsMembers200JSONResponseBodyMembersType defines parameters for CoreListV4GroupsMembers.
type CoreListV4GroupsMembers200JSONResponseBodyMembersType int

// CoreListV4MembersParams defines parameters for CoreListV4Members.
type CoreListV4MembersParams struct {
	N1               *string `form:"1,omitempty" json:"1,omitempty"`
	IncludeAddresses *string `form:"IncludeAddresses,omitempty" json:"IncludeAddresses,omitempty"`
}

// CoreCreateV4MembersJSONBody defines parameters for CoreCreateV4Members.
type CoreCreateV4MembersJSONBody struct {
	Auth *string `json:"Auth,omitempty"`

	// Invitation Invitation object if created using magic link
	Invitation        *string                             `json:"Invitation,omitempty"`
	MaxAI             *CoreCreateV4MembersJSONBodyMaxAI   `json:"MaxAI,omitempty"`
	MaxLumo           *CoreCreateV4MembersJSONBodyMaxLumo `json:"MaxLumo,omitempty"`
	MaxSpace          *float32                            `json:"MaxSpace,omitempty"`
	MaxVPN            *float32                            `json:"MaxVPN,omitempty"`
	Name              *string                             `json:"Name,omitempty"`
	Private           *float32                            `json:"Private,omitempty"`
	TemporaryPassword *bool                               `json:"TemporaryPassword,omitempty"`

	// Type Either 1=PROTON or 2=MANAGED (default)
	Type     *string `json:"Type,omitempty"`
	Username *string `json:"Username,omitempty"`
}

// CoreCreateV4MembersJSONBodyMaxAI defines parameters for CoreCreateV4Members.
type CoreCreateV4MembersJSONBodyMaxAI int

// CoreCreateV4MembersJSONBodyMaxLumo defines parameters for CoreCreateV4Members.
type CoreCreateV4MembersJSONBodyMaxLumo int

// CoreCreateV4MembersAddressesAvailableJSONBody defines parameters for CoreCreateV4MembersAddressesAvailable.
type CoreCreateV4MembersAddressesAvailableJSONBody struct {
	AddressList *struct {
		Data      *string `json:"Data,omitempty"`
		Signature *string `json:"Signature,omitempty"`
	} `json:"AddressList,omitempty"`
	DisplayName       *string  `json:"DisplayName,omitempty"`
	Domain            *string  `json:"Domain,omitempty"`
	Local             *string  `json:"Local,omitempty"`
	MemberID          *string  `json:"MemberID,omitempty"`
	RequesterMemberId *float32 `json:"RequesterMemberId,omitempty"`
	Signature         *string  `json:"Signature,omitempty"`
}

// CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONBody defines parameters for CoreUpdateV4MembersAddressesPermissionsOrganizationSwitch.
type CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONBody struct {
	// IDs List of encrypted addressIDs
	IDs *[]string `json:"IDs,omitempty"`

	// Permissions Permissions bit to apply
	Permissions *[]CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONBodyPermissions `json:"Permissions,omitempty"`
}

// CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONBodyPermissions defines parameters for CoreUpdateV4MembersAddressesPermissionsOrganizationSwitch.
type CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONBodyPermissions int

// CoreCreateV4MembersInvitationsJSONBody defines parameters for CoreCreateV4MembersInvitations.
type CoreCreateV4MembersInvitationsJSONBody struct {
	Email    *string                                        `json:"Email,omitempty"`
	MaxAI    *CoreCreateV4MembersInvitationsJSONBodyMaxAI   `json:"MaxAI,omitempty"`
	MaxLumo  *CoreCreateV4MembersInvitationsJSONBodyMaxLumo `json:"MaxLumo,omitempty"`
	MaxSpace *float32                                       `json:"MaxSpace,omitempty"`
}

// CoreCreateV4MembersInvitationsJSONBodyMaxAI defines parameters for CoreCreateV4MembersInvitations.
type CoreCreateV4MembersInvitationsJSONBodyMaxAI int

// CoreCreateV4MembersInvitationsJSONBodyMaxLumo defines parameters for CoreCreateV4MembersInvitations.
type CoreCreateV4MembersInvitationsJSONBodyMaxLumo int

// CoreUpdateV4MembersInvitationJSONBody defines parameters for CoreUpdateV4MembersInvitation.
type CoreUpdateV4MembersInvitationJSONBody struct {
	MaxSpace *float32 `json:"MaxSpace,omitempty"`
}

// CoreCreateV4MembersMeUnprivatizeJSONBody defines parameters for CoreCreateV4MembersMeUnprivatize.
type CoreCreateV4MembersMeUnprivatizeJSONBody struct {
	// OrgActivationToken A 32-byte random token encoded as hex and encrypted to the organization key, signed with newly created address key. Context should be set to account.key-token.user-unprivatization
	OrgActivationToken *string `json:"OrgActivationToken,omitempty"`

	// OrgUserKeys The user keys encrypted to the token contained in OrgActivationToken
	OrgUserKeys *string `json:"OrgUserKeys,omitempty"`
}

// CoreUpdateV4MembersPermissionsJSONBody defines parameters for CoreUpdateV4MembersPermissions.
type CoreUpdateV4MembersPermissionsJSONBody struct {
	Action *CoreUpdateV4MembersPermissionsJSONBodyAction `json:"Action,omitempty"`

	// Ids List of MemberIds
	Ids        *[]string                                         `json:"Ids,omitempty"`
	Permission *CoreUpdateV4MembersPermissionsJSONBodyPermission `json:"Permission,omitempty"`
}

// CoreUpdateV4MembersPermissionsJSONBodyAction defines parameters for CoreUpdateV4MembersPermissions.
type CoreUpdateV4MembersPermissionsJSONBodyAction int

// CoreUpdateV4MembersPermissionsJSONBodyPermission defines parameters for CoreUpdateV4MembersPermissions.
type CoreUpdateV4MembersPermissionsJSONBodyPermission int

// CoreListV4MembersSearchParams defines parameters for CoreListV4MembersSearch.
type CoreListV4MembersSearchParams struct {
	Limit    *float32 `form:"Limit,omitempty" json:"Limit,omitempty"`
	Q        *string  `form:"Q,omitempty" json:"Q,omitempty"`
	Keywords *string  `form:"keywords,omitempty" json:"keywords,omitempty"`
}

// CoreListV4MembersSearchSummaryParams defines parameters for CoreListV4MembersSearchSummary.
type CoreListV4MembersSearchSummaryParams struct {
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// CoreGetV4MemberParams defines parameters for CoreGetV4Member.
type CoreGetV4MemberParams struct {
	IncludeAddresses *float32 `form:"IncludeAddresses,omitempty" json:"IncludeAddresses,omitempty"`
}

// CoreListV4MembersAddressesParams defines parameters for CoreListV4MembersAddresses.
type CoreListV4MembersAddressesParams struct {
	Page     *float32 `form:"Page,omitempty" json:"Page,omitempty"`
	PageSize *float32 `form:"PageSize,omitempty" json:"PageSize,omitempty"`
}

// CoreCreateV4MembersAddressesJSONBody defines parameters for CoreCreateV4MembersAddresses.
type CoreCreateV4MembersAddressesJSONBody struct {
	AddressList *struct {
		Data      *string `json:"Data,omitempty"`
		Signature *string `json:"Signature,omitempty"`
	} `json:"AddressList,omitempty"`
	DisplayName       *string  `json:"DisplayName,omitempty"`
	Domain            *string  `json:"Domain,omitempty"`
	Local             *string  `json:"Local,omitempty"`
	MemberID          *string  `json:"MemberID,omitempty"`
	RequesterMemberId *float32 `json:"RequesterMemberId,omitempty"`
	Signature         *string  `json:"Signature,omitempty"`
}

// CoreUpdateV4MembersAddressesOrderJSONBody defines parameters for CoreUpdateV4MembersAddressesOrder.
type CoreUpdateV4MembersAddressesOrderJSONBody struct {
	// AddressIDs Will amend the order of addresses with the order of the corresponding AddressIDs
	AddressIDs *[]string `json:"AddressIDs,omitempty"`
}

// CoreUpdateV4MembersAiJSONBody defines parameters for CoreUpdateV4MembersAi.
type CoreUpdateV4MembersAiJSONBody struct {
	MaxAI *CoreUpdateV4MembersAiJSONBodyMaxAI `json:"MaxAI,omitempty"`
}

// CoreUpdateV4MembersAiJSONBodyMaxAI defines parameters for CoreUpdateV4MembersAi.
type CoreUpdateV4MembersAiJSONBodyMaxAI int

// CoreListV4MembersAuthlogParams defines parameters for CoreListV4MembersAuthlog.
type CoreListV4MembersAuthlogParams struct {
	Page     *string `form:"Page,omitempty" json:"Page,omitempty"`
	PageSize *string `form:"PageSize,omitempty" json:"PageSize,omitempty"`
}

// CoreCreateV4MembersDevicesResetJSONBody defines parameters for CoreCreateV4MembersDevicesReset.
type CoreCreateV4MembersDevicesResetJSONBody struct {
	// AuthDeviceID The member's device making the request
	AuthDeviceID *string `json:"AuthDeviceID,omitempty"`

	// EncryptedSecret base64 encoded AES-GCM encrypted to a random secret
	EncryptedSecret *string `json:"EncryptedSecret,omitempty"`

	// UserKeys List of re-encrypted user keys secret to random generated secret (32 bytes, then hex encoded)
	UserKeys *string `json:"UserKeys,omitempty"`
}

// CoreCreateV4MembersKeysJSONBody defines parameters for CoreCreateV4MembersKeys.
type CoreCreateV4MembersKeysJSONBody struct {
	AddressID    *string  `json:"AddressID,omitempty"`
	OrgSignature *string  `json:"OrgSignature,omitempty"`
	Primary      *float32 `json:"Primary,omitempty"`
	PrivateKey   *string  `json:"PrivateKey,omitempty"`
	Signature    *string  `json:"Signature,omitempty"`
	Token        *string  `json:"Token,omitempty"`
}

// CoreCreateV4MembersKeysSetupJSONBody defines parameters for CoreCreateV4MembersKeysSetup.
type CoreCreateV4MembersKeysSetupJSONBody struct {
	AddressID   *string `json:"AddressID,omitempty"`
	AddressList *struct {
		Data      *string `json:"Data,omitempty"`
		Signature *string `json:"Signature,omitempty"`
	} `json:"AddressList,omitempty"`

	// Auth Null when the member cannot login via password
	Auth         *string `json:"Auth,omitempty"`
	KeySalt      *string `json:"KeySalt,omitempty"`
	OrgSignature *string `json:"OrgSignature,omitempty"`
	PrivateKey   *string `json:"PrivateKey,omitempty"`
	Signature    *string `json:"Signature,omitempty"`
	Token        *string `json:"Token,omitempty"`
	UserKey      *struct {
		OrgPrivateKey *string `json:"OrgPrivateKey,omitempty"`
		OrgToken      *string `json:"OrgToken,omitempty"`
		PrivateKey    *string `json:"PrivateKey,omitempty"`
	} `json:"UserKey,omitempty"`
}

// CoreCreateV4MembersKeysUnprivatizeJSONBody defines parameters for CoreCreateV4MembersKeysUnprivatize.
type CoreCreateV4MembersKeysUnprivatizeJSONBody struct {
	// AddressKeys A token and signature for each address key to access them via the org key
	AddressKeys               *string `json:"AddressKeys,omitempty"`
	OrganizationKeyActivation *struct {
		// Signature Signature of the token key packet by the user key of the member
		Signature *string `json:"Signature,omitempty"`

		// TokenKeyPacket Token key packet encrypted to the user key of the member
		TokenKeyPacket *string `json:"TokenKeyPacket,omitempty"`
	} `json:"OrganizationKeyActivation,omitempty"`
	UserKey *struct {
		OrgPrivateKey *string `json:"OrgPrivateKey,omitempty"`
		OrgToken      *string `json:"OrgToken,omitempty"`
	} `json:"UserKey,omitempty"`

	// UserKeys All active member's user keys, with a signed and encrypted token to access them via the org key
	UserKeys *string `json:"UserKeys,omitempty"`
}

// CoreUpdateV4MembersLumoJSONBody defines parameters for CoreUpdateV4MembersLumo.
type CoreUpdateV4MembersLumoJSONBody struct {
	MaxLumo *CoreUpdateV4MembersLumoJSONBodyMaxLumo `json:"MaxLumo,omitempty"`
}

// CoreUpdateV4MembersLumoJSONBodyMaxLumo defines parameters for CoreUpdateV4MembersLumo.
type CoreUpdateV4MembersLumoJSONBodyMaxLumo int

// CoreUpdateV4MembersRoleJSONBody defines parameters for CoreUpdateV4MembersRole.
type CoreUpdateV4MembersRoleJSONBody struct {
	OrganizationKeyActivation *struct {
		// Signature Signature of the token key packet by the user key of the member
		Signature *string `json:"Signature,omitempty"`

		// TokenKeyPacket Token key packet encrypted to the user key of the member
		TokenKeyPacket *string `json:"TokenKeyPacket,omitempty"`
	} `json:"OrganizationKeyActivation,omitempty"`
	OrganizationKeyInvitation *struct {
		// EncryptionAddressID The address ID of the address to which the token key packet is encrypted to
		EncryptionAddressID *string `json:"EncryptionAddressID,omitempty"`

		// Signature Signature of the token key packet by the inviters address key
		Signature *string `json:"Signature,omitempty"`

		// SignatureAddressID The address ID of the signature address key
		SignatureAddressID *string `json:"SignatureAddressID,omitempty"`

		// TokenKeyPacket Token key packet encrypted to the recipient's address key
		TokenKeyPacket *string `json:"TokenKeyPacket,omitempty"`
	} `json:"OrganizationKeyInvitation,omitempty"`
	Role *float32 `json:"Role,omitempty"`
}

// CoreCreateV4MembersUnprivatizeJSONBody defines parameters for CoreCreateV4MembersUnprivatize.
type CoreCreateV4MembersUnprivatizeJSONBody struct {
	// InvitationSignature The invitation signature
	InvitationSignature *string `json:"InvitationSignature,omitempty"`
}

// CoreListV4MembersVpnParams defines parameters for CoreListV4MembersVpn.
type CoreListV4MembersVpnParams struct {
	Page     *string `form:"Page,omitempty" json:"Page,omitempty"`
	PageSize *string `form:"PageSize,omitempty" json:"PageSize,omitempty"`
}

// PermissionsUpdateV1GroupsRolesJSONBody defines parameters for PermissionsUpdateV1GroupsRoles.
type PermissionsUpdateV1GroupsRolesJSONBody struct {
	Add    *string `json:"Add,omitempty"`
	Remove *string `json:"Remove,omitempty"`
}

// PermissionsUpdateV1MembersRolesJSONBody defines parameters for PermissionsUpdateV1MembersRoles.
type PermissionsUpdateV1MembersRolesJSONBody struct {
	Add    *string `json:"Add,omitempty"`
	Remove *string `json:"Remove,omitempty"`
}

// CalendarCreateV1MembersJSONRequestBody defines body for CalendarCreateV1Members for application/json ContentType.
type CalendarCreateV1MembersJSONRequestBody CalendarCreateV1MembersJSONBody

// CoreCreateV4AuthJSONRequestBody defines body for CoreCreateV4Auth for application/json ContentType.
type CoreCreateV4AuthJSONRequestBody CoreCreateV4AuthJSONBody

// CoreCreateV4Auth2faJSONRequestBody defines body for CoreCreateV4Auth2fa for application/json ContentType.
type CoreCreateV4Auth2faJSONRequestBody CoreCreateV4Auth2faJSONBody

// CoreCreateV4AuthCookiesJSONRequestBody defines body for CoreCreateV4AuthCookies for application/json ContentType.
type CoreCreateV4AuthCookiesJSONRequestBody CoreCreateV4AuthCookiesJSONBody

// CoreCreateV4AuthInfoJSONRequestBody defines body for CoreCreateV4AuthInfo for application/json ContentType.
type CoreCreateV4AuthInfoJSONRequestBody CoreCreateV4AuthInfoJSONBody

// CoreCreateV4AuthJwtJSONRequestBody defines body for CoreCreateV4AuthJwt for application/json ContentType.
type CoreCreateV4AuthJwtJSONRequestBody CoreCreateV4AuthJwtJSONBody

// CoreCreateV4GroupsJSONRequestBody defines body for CoreCreateV4Groups for application/json ContentType.
type CoreCreateV4GroupsJSONRequestBody CoreCreateV4GroupsJSONBody

// CoreCreateV4GroupsMembersJSONRequestBody defines body for CoreCreateV4GroupsMembers for application/json ContentType.
type CoreCreateV4GroupsMembersJSONRequestBody CoreCreateV4GroupsMembersJSONBody

// CoreUpdateV4GroupsMemberJSONRequestBody defines body for CoreUpdateV4GroupsMember for application/json ContentType.
type CoreUpdateV4GroupsMemberJSONRequestBody CoreUpdateV4GroupsMemberJSONBody

// CoreCreateV4GroupsOwnersAcceptJSONRequestBody defines body for CoreCreateV4GroupsOwnersAccept for application/json ContentType.
type CoreCreateV4GroupsOwnersAcceptJSONRequestBody CoreCreateV4GroupsOwnersAcceptJSONBody

// CoreCreateV4GroupsOwnersAddJSONRequestBody defines body for CoreCreateV4GroupsOwnersAdd for application/json ContentType.
type CoreCreateV4GroupsOwnersAddJSONRequestBody CoreCreateV4GroupsOwnersAddJSONBody

// CoreCreateV4GroupsOwnersInvitesJSONRequestBody defines body for CoreCreateV4GroupsOwnersInvites for application/json ContentType.
type CoreCreateV4GroupsOwnersInvitesJSONRequestBody CoreCreateV4GroupsOwnersInvitesJSONBody

// CoreUpdateV4GroupJSONRequestBody defines body for CoreUpdateV4Group for application/json ContentType.
type CoreUpdateV4GroupJSONRequestBody CoreUpdateV4GroupJSONBody

// CoreCreateV4MembersJSONRequestBody defines body for CoreCreateV4Members for application/json ContentType.
type CoreCreateV4MembersJSONRequestBody CoreCreateV4MembersJSONBody

// CoreCreateV4MembersAddressesAvailableJSONRequestBody defines body for CoreCreateV4MembersAddressesAvailable for application/json ContentType.
type CoreCreateV4MembersAddressesAvailableJSONRequestBody CoreCreateV4MembersAddressesAvailableJSONBody

// CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONRequestBody defines body for CoreUpdateV4MembersAddressesPermissionsOrganizationSwitch for application/json ContentType.
type CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONRequestBody CoreUpdateV4MembersAddressesPermissionsOrganizationSwitchJSONBody

// CoreCreateV4MembersInvitationsJSONRequestBody defines body for CoreCreateV4MembersInvitations for application/json ContentType.
type CoreCreateV4MembersInvitationsJSONRequestBody CoreCreateV4MembersInvitationsJSONBody

// CoreUpdateV4MembersInvitationJSONRequestBody defines body for CoreUpdateV4MembersInvitation for application/json ContentType.
type CoreUpdateV4MembersInvitationJSONRequestBody CoreUpdateV4MembersInvitationJSONBody

// CoreCreateV4MembersMeUnprivatizeJSONRequestBody defines body for CoreCreateV4MembersMeUnprivatize for application/json ContentType.
type CoreCreateV4MembersMeUnprivatizeJSONRequestBody CoreCreateV4MembersMeUnprivatizeJSONBody

// CoreUpdateV4MembersPermissionsJSONRequestBody defines body for CoreUpdateV4MembersPermissions for application/json ContentType.
type CoreUpdateV4MembersPermissionsJSONRequestBody CoreUpdateV4MembersPermissionsJSONBody

// CoreCreateV4MembersAddressesJSONRequestBody defines body for CoreCreateV4MembersAddresses for application/json ContentType.
type CoreCreateV4MembersAddressesJSONRequestBody CoreCreateV4MembersAddressesJSONBody

// CoreUpdateV4MembersAddressesOrderJSONRequestBody defines body for CoreUpdateV4MembersAddressesOrder for application/json ContentType.
type CoreUpdateV4MembersAddressesOrderJSONRequestBody CoreUpdateV4MembersAddressesOrderJSONBody

// CoreUpdateV4MembersAiJSONRequestBody defines body for CoreUpdateV4MembersAi for application/json ContentType.
type CoreUpdateV4MembersAiJSONRequestBody CoreUpdateV4MembersAiJSONBody

// CoreCreateV4MembersDevicesResetJSONRequestBody defines body for CoreCreateV4MembersDevicesReset for application/json ContentType.
type CoreCreateV4MembersDevicesResetJSONRequestBody CoreCreateV4MembersDevicesResetJSONBody

// CoreCreateV4MembersKeysJSONRequestBody defines body for CoreCreateV4MembersKeys for application/json ContentType.
type CoreCreateV4MembersKeysJSONRequestBody CoreCreateV4MembersKeysJSONBody

// CoreCreateV4MembersKeysSetupJSONRequestBody defines body for CoreCreateV4MembersKeysSetup for application/json ContentType.
type CoreCreateV4MembersKeysSetupJSONRequestBody CoreCreateV4MembersKeysSetupJSONBody

// CoreCreateV4MembersKeysUnprivatizeJSONRequestBody defines body for CoreCreateV4MembersKeysUnprivatize for application/json ContentType.
type CoreCreateV4MembersKeysUnprivatizeJSONRequestBody CoreCreateV4MembersKeysUnprivatizeJSONBody

// CoreUpdateV4MembersLumoJSONRequestBody defines body for CoreUpdateV4MembersLumo for application/json ContentType.
type CoreUpdateV4MembersLumoJSONRequestBody CoreUpdateV4MembersLumoJSONBody

// CoreUpdateV4MembersRoleJSONRequestBody defines body for CoreUpdateV4MembersRole for application/json ContentType.
type CoreUpdateV4MembersRoleJSONRequestBody CoreUpdateV4MembersRoleJSONBody

// CoreCreateV4MembersUnprivatizeJSONRequestBody defines body for CoreCreateV4MembersUnprivatize for application/json ContentType.
type CoreCreateV4MembersUnprivatizeJSONRequestBody CoreCreateV4MembersUnprivatizeJSONBody

// PermissionsUpdateV1GroupsRolesJSONRequestBody defines body for PermissionsUpdateV1GroupsRoles for application/json ContentType.
type PermissionsUpdateV1GroupsRolesJSONRequestBody PermissionsUpdateV1GroupsRolesJSONBody

// PermissionsUpdateV1MembersRolesJSONRequestBody defines body for PermissionsUpdateV1MembersRoles for application/json ContentType.
type PermissionsUpdateV1MembersRolesJSONRequestBody PermissionsUpdateV1MembersRolesJSONBody
